### ISSUE TITLE
bug with WASM_I64 type

### ISSUE THREAD

**Issue by edmundwz** [bytecodealliance/wasm-micro-runtime#1003]
if (!(ret = wasm_runtime_call_wasm(exec_env, function, num_args, argv)))
        goto fail2;

(wasm_runtime_common.c: line at 1632)

Please check the code above. I just replace the 'num_args' with 'argc' and it works fine with 'WASM_I64' type as passing argument.

**Comment by wenyongh** [comment]
@edmundwz Thanks for reporting the issue! It is really a bug, we have submitted patch #1005 to fix it and updated sample basic to test wasm_runtime_call_wasm_a.
