### ISSUE TITLE
How to check that "app_manager_startup" is ready

### ISSUE THREAD

**Issue by tonibofarull0** [bytecodealliance/wasm-micro-runtime#1004]
The use case that I'm trying to do is similar as in the sample [simple](https://github.com/bytecodealliance/wasm-micro-runtime/tree/main/samples/simple), but **host_tool** and **simple** is the same process.

I am trying to have the server that handles the wasm-apps and the one that receives the requests in the same process. For that, I have to synchronize both threads to know that the app manager has been initialized.

I have the following structure:

```
bool host_init() {
    pthread_cond_signal(&init_server_cond);
    return true;
}

void* init_app_manager(void *args) {
    app_manager_startup(&interface);
    wasm_runtime_destroy();
    return NULL;
}

void run() {
    if (os_thread_create(&tid_app_manager, init_app_manager, NULL, BH_APPLET_PRESERVED_STACK_SIZE) != 0) {
        printf("Error creating the app_manager.\n");
    }
    pthread_mutex_lock(&init_server_mutex);
    pthread_cond_wait(&init_server_cond, &init_server_mutex);
    pthread_mutex_unlock(&init_server_mutex);
}
```

However, if the main thread receives a petition before the server thread is in the [queue loop](https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/core/app-mgr/app-manager/app_manager.c#L358-L398) we can have a problem.

1. Is there an official way to handle this? Do we have a way to check that the server is ready to handle petitions?
2. What's the expected behavior of sending commands to [aee_host_msg_callback](https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/core/app-mgr/app-manager/app_manager_host.c#L221-L262) if the thread has not entered the queue loop?

In the latter case, I think it would be nice to condition the return value according to the output of [am_dispatch_request](https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/core/app-mgr/app-manager/app_manager_host.c#L245).

Thank you very much!

**Comment by wenyongh** [comment]
Hi, it seems that there is not a better way to check whether app-manager is started without modifying the source code. And a method is to add a flag to check, see to patch uploaded, we can keep calling `app_mgr_is_started` to check the status. Thanks.
[app_mgr.zip](https://github.com/bytecodealliance/wasm-micro-runtime/files/8080015/app_mgr.zip)

**Comment by tonibofarull0** [comment]
I see, thanks! Is it ok to merge this approach into main?

**Comment by wenyongh** [comment]
Hi, patch #1011 was merged, please try again, thanks.
