### ISSUE TITLE
Multiple Build Configurations Enabled

### ISSUE THREAD

**Issue by chhokrad** [bytecodealliance/wasm-micro-runtime#1089]
Hi 

I have a question regarding the build options for WAMR, if multiple options such as WAMR_BUILD_INTERP, WAMR_BUILD_JIT, WAMR_FAST_INTERP are enabled, how the final artifact will behave? Is the final behavior deterministic? 

Thanks
Ajay D Chhokra

**Comment by NingW101** [comment]
Hey, if the build options are configured as follows:
```cmake
cmake -DWAMR_BUILD_INTERP=1 -DWAMR_BUILD_JIT=1 -DWAMR_FAST_INTERP=1
```
then it finally will be executed in JIT mode. You can refer to the [code](https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/core/iwasm/common/wasm_runtime_common.c#L764-L772) , the `wasm` file will be loaded as `wasm module` and converted into `aot module`.

Thanks
