### ISSUE TITLE
example in wamr_api.md likely does not compile

### ISSUE THREAD

**Issue by jmgurney** [bytecodealliance/wasm-micro-runtime#1160]
In the document: https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/doc/wamr_api.md

There's an example the defines timer_update as:
```
/* Timer callback */
void timer_update(user_timer_t timer
{
    attr_container_t *event;
```

The missing closing parens means it is likely not able to be compiled.

**Comment by wenyongh** [comment]
Hi, thanks for reporting issue, it should be `void timer_update(user_timer_t timer)`, we will upload a patch to fix it soon.
