### ISSUE TITLE
`sock_accept` had been added in WASI snapshot1

### ISSUE THREAD

**Issue by hangedfish** [bytecodealliance/wasm-micro-runtime#1167]
Hi, I found the definition of `sock_accept` had been added in WASI snapshot1

https://github.com/WebAssembly/WASI/blob/ab030f6639f0de7e87e2fa5bed45c6bd1c324ce7/phases/snapshot/witx/wasi_snapshot_preview1.witx#L476-L485

and wasi-libc has been updated.

https://github.com/WebAssembly/wasi-libc/pull/282
https://github.com/WebAssembly/wasi-libc/pull/287

Shall we update `sock_accept` interface in warm?

**Comment by lum1n0us** [comment]
thanks for reminding us.
