### ISSUE TITLE
is the "unit32" is a typo ?

### ISSUE THREAD

**Issue by yaozhongxiao** [bytecodealliance/wasm-micro-runtime#1211]
If I did not misunderstand, the type unit32 in should be uint32
"https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/doc/embed_wamr.md"

**Comment by xujuntwt95329** [comment]
Hi, thanks a lot for reporting this, we have fixed in PR https://github.com/bytecodealliance/wasm-micro-runtime/pull/1214

**Comment by wenyongh** [comment]
Close this is issue as it was fixed.
