### ISSUE TITLE
Which dir includes the interpreter Mode, JIt and AOT-related codes?

### ISSUE THREAD

**Issue by Zhangyx24** [bytecodealliance/wasm-micro-runtime#1221]
I'm a little confused about which dir includes the Interpreter Mode, JIt and AOT related code？

**Comment by xujuntwt95329** [comment]
Hi @Zhangyx24

Interpreter mode is under:
https://github.com/bytecodealliance/wasm-micro-runtime/tree/main/core/iwasm/interpreter

AoT mode is under:
https://github.com/bytecodealliance/wasm-micro-runtime/tree/main/core/iwasm/aot

JIT mode (and AoT compilation) is under:
https://github.com/bytecodealliance/wasm-micro-runtime/tree/main/core/iwasm/compilation

besides, the common layer provides unified APIs to the embedder:
https://github.com/bytecodealliance/wasm-micro-runtime/tree/main/core/iwasm/common

**Comment by abc767234318** [comment]
> Hi @Zhangyx24
> 
> Interpreter mode is under: https://github.com/bytecodealliance/wasm-micro-runtime/tree/main/core/iwasm/interpreter
> 
> AoT mode is under: https://github.com/bytecodealliance/wasm-micro-runtime/tree/main/core/iwasm/aot
> 
> JIT mode (and AoT compilation) is under: https://github.com/bytecodealliance/wasm-micro-runtime/tree/main/core/iwasm/compilation
> 
> besides, the common layer provides unified APIs to the embedder: https://github.com/bytecodealliance/wasm-micro-runtime/tree/main/core/iwasm/common

I have a question, how does WAMR implement JIT?

**Comment by xujuntwt95329** [comment]
@abc767234318 
By default, WAMR use LLVM's ORC JIT API to implement the JIT compilation, which is known as `lazy mode`, in this mode, the functions will be compiled when they are first invoked.

We also provide an option `WAMR_BUILD_LAZY_JIT=1/0`, when this is set to 0, it will be `eager mode`, in this mode, all the functions will be compiled during startup.

**Comment by abc767234318** [comment]
@xujuntwt95329 Thanks for your answer!

**Comment by hungryzzz** [comment]
> @abc767234318 By default, WAMR use LLVM's ORC JIT API to implement the JIT compilation, which is known as `lazy mode`, in this mode, the functions will be compiled when they are first invoked.
> 
> We also provide an option `WAMR_BUILD_LAZY_JIT=1/0`, when this is set to 0, it will be `eager mode`, in this mode, all the functions will be compiled during startup.

Hi, once the `.wasm` file is compiled to the target machine code, will this target code be optimized during execution? (Just like the multi-tier JIT in JSC)
