### ISSUE TITLE
Redundant zeroing of memory acquired from `mmap`

### ISSUE THREAD

**Issue by lei-april** [bytecodealliance/wasm-micro-runtime#1269]
When hardware bound check is enabled, wasm's linear memory is acquired from `mmap` (or `VirtualAlloc` on Windows), and is then explicitly zeroed by `memset`: https://github.com/bytecodealliance/wasm-micro-runtime/blob/daeb7a42658cc2a7dfe4e4d4e855ac8588c5c565/core/iwasm/aot/aot_runtime.c#L528

According to [Linux manual page](https://man7.org/linux/man-pages/man2/mmap.2.html), memory mapping acquired with flag `MAP_ANONYMOUS` is zeroed by the kernel. And [`VirtualAlloc`](https://docs.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-virtualalloc) on Windows seems to share the same behavior. MacOS's [manual page for mmap](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/mmap.2.html) doesn't specify whether the mapping is zeroed, but it seems so according to my experiments.

This makes the explicit call to `memset` mentioned above redundant. Not only is it redundant, it also has negative impact on performance. When instantiating a wasm module with a large initial memory (mostly zeros), explicitly zeroing the the whole linear memory would result in a large number of page faults.

Fixing this should be simple: just remove the redundant call to `memset` :)

**Comment by wenyongh** [comment]
@lei-april, thanks a lot, we have submitted PR #1273 to fix it.
