### ISSUE TITLE
How to specify the wasm function to execute?

### ISSUE THREAD

**Issue by Zhangyx24** [bytecodealliance/wasm-micro-runtime#1280]
<img width="728" alt="截屏2022-07-09 下午3 23 09" src="https://user-images.githubusercontent.com/28601300/178096214-14411728-af60-4ddf-87e4-33672c353262.png">
I tried to specify a function on mac `iwasm test.wasm -f=func1` but failed.
What is the corrrect usage?

**Comment by xujuntwt95329** [comment]
Hi @Zhangyx24 

As shown in the usage, the `options` should passed in front of the wasm file, otherwise it will be treated as the `args` to your wasm application.

For your case:

``` C
iwasm -f func1 test.wasm
```

**Comment by Zhangyx24** [comment]
Thanks a lot, and how to pass parameters for a function, just put the parameters follow the `iwasm -f func1 test.wasm` in the command ?

**Comment by xujuntwt95329** [comment]
Yes, e.g. `iwasm -f func1 test.wasm 1 2`

The runtime will check the number of arguments

**Comment by Zhangyx24** [comment]
Thanks a lot !
