### ISSUE TITLE
Fail to set the max memory with c-api ?

### ISSUE THREAD

**Issue by Zhangyx24** [bytecodealliance/wasm-micro-runtime#1289]
## Steps to reproduce
I tried to execute the test.wat:
[test.txt](https://github.com/bytecodealliance/wasm-micro-runtime/files/9091706/test.txt) both in command line and c-api. 

#### (1)command line
`iwasm test.wat`

#### (2)c-api
The c file is 
[test-in-c.txt](https://github.com/bytecodealliance/wasm-micro-runtime/files/9091728/test-in-c.txt)
**Interpreter mode :** `cd build; cmake .. ; make; ./test`
**AOT mode :** `cd build; cmake -DWAMR_BUILD_INTERP=0 -DWAMR_BUILD_AOT=1 ..; make; ./test`

## Expected result
Allow the memory of 65536, and don't print error.

#### (2)c-api in **interpreter** mode **failed** and print:
![截屏2022-07-12 下午5 55 41](https://user-images.githubusercontent.com/28601300/178464082-8686fbc2-5a8a-4f3a-a414-2f65b24804e5.png)
**c-api in AOT mode succeed**.

Both macOS and ubuntu got the same result.

**Comment by lum1n0us** [comment]
nice catching! will fix it soon.

**Comment by Zhangyx24** [comment]
Thanks a lot !  Waiting for your fix.

**Comment by lum1n0us** [comment]
After a long discussion, we are going to *keep different* results of interpreter and AOT when setting the memory minimum page count with 65536(4GB) in current phase.

The mainly reason on it is that interpreter and AOT are using different design to manage the linear memory boundary. And we are planing to unite both. And when it's done, both mode shall have same responses to 65536.

So, there will be no fix for the failure of meeting `(memory 65536)` in interpreter.

**Comment by Zhangyx24** [comment]
Do you mean that after unite both, interpreter and AOT will response same to 65536?
Will they both allow 65536 or don't?

**Comment by lum1n0us** [comment]
After uniting both, both interpreter and AOT will allow 65536 pages in the future. But not in the subsequent few releases.

**Comment by lum1n0us** [comment]
https://github.com/bytecodealliance/wasm-micro-runtime/issues/1301

**Comment by Zhangyx24** [comment]
Thanks for your answer!
