### ISSUE TITLE
Calling host functions in c-api error ?

### ISSUE THREAD

**Issue by Zhangyx24** [bytecodealliance/wasm-micro-runtime#1290]
## Steps to reproduce
I tried to execute **test.wat**  
[test.txt](https://github.com/bytecodealliance/wasm-micro-runtime/files/9100940/test.txt)
through c-api in **test-in-api.c** 
[test-in-api.txt](https://github.com/bytecodealliance/wasm-micro-runtime/files/9100941/test-in-api.txt)
.

In test.wat, it **import 2 function from host (c file)** : `assert_eq_i32` and `print_input`. (**This 2 function has 2 different types !**)
## Expected Result
The c api shows error or exception to **alert** that the first function I imported in c file are different from the first import function in wat file in type.

## Actual Result
It alert nothing and regard function `print_input` as function `assert_eq_i32` and regard function `assert_eq_i32` as function `print_input` although they has **different function types** and output unexpected output of wat file.

**Comment by Zhangyx24** [comment]
Thanks a lot ! Waiting for your fixing.

**Comment by lum1n0us** [comment]
we've fixed the issue in the latest commits, dd62b32b201db8e5939e1084757c712145e93264.

**Comment by wenyongh** [comment]
Close this issue as it was fixed.
