### ISSUE TITLE
Fail to load module multiple times ?

### ISSUE THREAD

**Issue by Zhangyx24** [bytecodealliance/wasm-micro-runtime#1304]
## Steps to reproduce
Executing the wat file
[test.txt](https://github.com/bytecodealliance/wasm-micro-runtime/files/9131732/test.txt)
  in C
[test-in-c.txt](https://github.com/bytecodealliance/wasm-micro-runtime/files/9131733/test-in-c.txt)

Try to load and execute it multiple times.

## Expected behavior
Successfully execute.
And wasmer, wasmtime could repeat the load and execution of the wat file for unlimited times.

## Actual behavior 
WAMR can do it once, but can't in 100times or unlimited times.
<img width="823" alt="截屏2022-07-18 下午8 14 06" src="https://user-images.githubusercontent.com/28601300/179508900-ff7c764a-1d5d-48fc-9955-52565fe359ee.png">

**Comment by lum1n0us** [comment]
There are several issues in the test code.

- `wasm_engine_new` and `wasm_store_new` are not pair with `wasm_store_delete` and `wasm_engine_delete`. In wasm-c-api, `wasm_XXX_new` is kind of constructor and `wasm_XXX_delete` is kind of deconstructor. In test code, `wasm_store_t` and `wasm_engine_t` are deleted too many times, and are both invalid in secondary times.

- `wasm_byte_vec_t binary` was destroyed in first loop and become invalid in all next rounds. Still a not paired problem.

- `wasm_byte_vec_t binary` can't be reused. It has to be renewed. In test code, an appropriate way is to `fopen()` and `fclose()` in every loop.

**Comment by Zhangyx24** [comment]
Thanks for your answer !
