### ISSUE TITLE
Fail to get the correct result when calling host function ?

### ISSUE THREAD

**Issue by Zhangyx24** [bytecodealliance/wasm-micro-runtime#1362]
## Steps to  reproduce
[test-wat.txt](https://github.com/bytecodealliance/wasm-micro-runtime/files/9276680/test-wat.txt)
[test-c.txt](https://github.com/bytecodealliance/wasm-micro-runtime/files/9276508/test-c.txt)
test.c is uploaded as test-c.txt, and test.wat is uploaded as test-wat.txt.

(1) interpreter
`cd build`
`cmake ..`
`make`
`./test`

(2)AoT
`cd AOTbuild`
`cmake -DWAMR_BUILD_INTERP=0 -DWAMR_BUILD_AOT=1 ..`
`make`
`./test`

## Environment
WAMR 05-18-2022
macOS10.15
ubuntu20.04

## Expected result
sum_i32_host Results: 3
sum_i32_host Results: 1819017217
sum_i32_host Results: 2124157492

#### macOS
(1)
Initializing...
Loading binary...
Compiling module...
Creating callback...
Instantiating module...
Extracting export...
Export size : 1
Calling test ...
_i32_host Results: -392881592
(2)
Initializing...
Loading binary...
Compiling module...
Creating callback...
Instantiating module...
Extracting export...
Export size : 1
Calling test ...
_i32_host Results: -368068552
unhandled SIGSEGV, si_addr: 0x1e

The result is random.

#### Ubuntu
(1)
./test-wamr526 
Initializing...
Loading binary...
Compiling module...
Creating callback...
Instantiating module...
Extracting export...
Export size : 1
Calling test ...
_i32_host Results: 0
Segmentation fault (core dumped)
(2)
Initializing...
Loading binary...
Compiling module...
Creating callback...
Instantiating module...
Extracting export...
Export size : 1
Calling test ...
_i32_host Results: 0
unhandled SIGSEGV, si_addr: 0x15
Aborted (core dumped)

**Comment by yamt** [comment]
i guess you should enable compiler warnings.

* args/results should be wasm_val_vec_t, not wasm_val_t
* `printf("sum_i32_host Results: %d\n" + s);`: replace `+` with `,`
* i guess your callback function should return `NULL`.

**Comment by Zhangyx24** [comment]
I modify the test.c:

`#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <inttypes.h>

#include "wasm_c_api.h"

#define own


void sum_i32(
    const wasm_val_vec_t* args, wasm_val_vec_t* results
) {
    int x = (args->data[0]).of.i32;
    int y = (args->data[1]).of.i32;
    int s = x + y;
    printf("sum_i32_host Results: %d\n", s);
}



int main(int argc, const char* argv[]) {
    // Initialize.
    printf("Initializing...\n");
    wasm_engine_t* engine = wasm_engine_new();
    wasm_store_t* store = wasm_store_new(engine);

    // Load binary.
    printf("Loading binary...\n");
#if WASM_ENABLE_AOT != 0 && WASM_ENABLE_INTERP == 0
    FILE* file = fopen("test.aot", "rb");
#else
    FILE* file = fopen("test.wasm", "rb");
#endif
    if (!file) {
        printf("> Error loading module!\n");
        return 1;
    }

    int ret = fseek(file, 0L, SEEK_END);
    if (ret == -1) {
        printf("> Error loading module!\n");
        fclose(file);
        return 1;
    }

    long file_size = ftell(file);
    if (file_size == -1) {
        printf("> Error loading module!\n");
        fclose(file);
        return 1;
    }

    ret = fseek(file, 0L, SEEK_SET);
    if (ret == -1) {
        printf("> Error loading module!\n");
        fclose(file);
        return 1;
    }

    wasm_byte_vec_t binary;
    wasm_byte_vec_new_uninitialized(&binary, file_size);
    if (fread(binary.data, file_size, 1, file) != 1) {
        printf("> Error loading module!\n");
        fclose(file);
        return 1;
    }
    fclose(file);

    // Compile.
    printf("Compiling module...\n");
    own wasm_module_t* module = wasm_module_new(store, &binary);
    if (!module) {
        printf("> Error compiling module!\n");
        return 1;
    }

    wasm_byte_vec_delete(&binary);

    // Create external print functions.
    printf("Creating callback...\n");

    own wasm_functype_t* func_type = wasm_functype_new_1_1(wasm_valtype_new_i32(), wasm_valtype_new_i32());
    own wasm_func_t* func = wasm_func_new(store, func_type, sum_i32);

    wasm_functype_delete(func_type);

    // Instantiate.
    printf("Instantiating module...\n");
    wasm_extern_t* externs[] = {
        wasm_func_as_extern(func)
    };


    wasm_extern_vec_t imports = WASM_ARRAY_VEC(externs);
    own wasm_instance_t* instance =
        wasm_instance_new(store, module, &imports, NULL);
    if (!instance) {
        printf("> Error instantiating module!\n");
        return 1;
    }

    printf("Extracting export...\n");
    own wasm_extern_vec_t exports;
    wasm_instance_exports(instance, &exports);
    if (exports.size == 0) {
        printf("> Error accessing exports!\n");
        return 1;
    }else{
        printf("Export size : %zu\n", exports.size);
    }
    const wasm_func_t* func1 = wasm_extern_as_func(exports.data[0]);
    if (func1 == NULL) {
        printf("> Error accessing export!\n");
        return 1;
    }

    printf("Calling test ...\n");
    wasm_val_vec_t args = WASM_EMPTY_VEC;
    wasm_val_vec_t results = WASM_EMPTY_VEC;
    wasm_func_call(func1, &args, &results);



    // Shut down.
    printf("Shutting down...\n");
    wasm_module_delete(module);
    wasm_instance_delete(instance);
    wasm_func_delete(func);
    wasm_store_delete(store);
    wasm_engine_delete(engine);

    // All done.
    printf("Done.\n");
    return 0;
}`

But the actual result is :
Initializing...
Loading binary...
Compiling module...
Creating callback...
Instantiating module...
Extracting export...
Export size : 1
Calling test ...
sum_i32_host Results: 3
Segmentation fault (core dumped)

**Comment by Zhangyx24** [comment]
I modify the test.c:

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <inttypes.h>

#include "wasm_c_api.h"

#define own


void sum_i32(
    const wasm_val_vec_t* args, wasm_val_vec_t* results
) {
    int x = (args->data[0]).of.i32;
    int y = (args->data[1]).of.i32;
    int s = x + y;
    printf("sum_i32_host Results: %d\n", s);
}



int main(int argc, const char* argv[]) {
    // Initialize.
    printf("Initializing...\n");
    wasm_engine_t* engine = wasm_engine_new();
    wasm_store_t* store = wasm_store_new(engine);

    // Load binary.
    printf("Loading binary...\n");
#if WASM_ENABLE_AOT != 0 && WASM_ENABLE_INTERP == 0
    FILE* file = fopen("test-wamr526.aot", "rb");
#else
    FILE* file = fopen("test-wamr526.wasm", "rb");
#endif
    if (!file) {
        printf("> Error loading module!\n");
        return 1;
    }

    int ret = fseek(file, 0L, SEEK_END);
    if (ret == -1) {
        printf("> Error loading module!\n");
        fclose(file);
        return 1;
    }

    long file_size = ftell(file);
    if (file_size == -1) {
        printf("> Error loading module!\n");
        fclose(file);
        return 1;
    }

    ret = fseek(file, 0L, SEEK_SET);
    if (ret == -1) {
        printf("> Error loading module!\n");
        fclose(file);
        return 1;
    }

    wasm_byte_vec_t binary;
    wasm_byte_vec_new_uninitialized(&binary, file_size);
    if (fread(binary.data, file_size, 1, file) != 1) {
        printf("> Error loading module!\n");
        fclose(file);
        return 1;
    }
    fclose(file);

    // Compile.
    printf("Compiling module...\n");
    own wasm_module_t* module = wasm_module_new(store, &binary);
    if (!module) {
        printf("> Error compiling module!\n");
        return 1;
    }

    wasm_byte_vec_delete(&binary);

    // Create external print functions.
    printf("Creating callback...\n");

    own wasm_functype_t* func_type = wasm_functype_new_1_1(wasm_valtype_new_i32(), wasm_valtype_new_i32());
    own wasm_func_t* func = wasm_func_new(store, func_type, sum_i32);

    wasm_functype_delete(func_type);

    // Instantiate.
    printf("Instantiating module...\n");
    wasm_extern_t* externs[] = {
        wasm_func_as_extern(func)
    };


    wasm_extern_vec_t imports = WASM_ARRAY_VEC(externs);
    own wasm_instance_t* instance =
        wasm_instance_new(store, module, &imports, NULL);
    if (!instance) {
        printf("> Error instantiating module!\n");
        return 1;
    }

    printf("Extracting export...\n");
    own wasm_extern_vec_t exports;
    wasm_instance_exports(instance, &exports);
    if (exports.size == 0) {
        printf("> Error accessing exports!\n");
        return 1;
    }else{
        printf("Export size : %zu\n", exports.size);
    }
    const wasm_func_t* func1 = wasm_extern_as_func(exports.data[0]);
    if (func1 == NULL) {
        printf("> Error accessing export!\n");
        return 1;
    }

    printf("Calling test ...\n");
    wasm_val_vec_t args = WASM_EMPTY_VEC;
    wasm_val_vec_t results = WASM_EMPTY_VEC;
    wasm_func_call(func1, &args, &results);



    // Shut down.
    printf("Shutting down...\n");
    wasm_module_delete(module);
    wasm_instance_delete(instance);
    wasm_func_delete(func);
    wasm_store_delete(store);
    wasm_engine_delete(engine);

    // All done.
    printf("Done.\n");
    return 0;
}


But the actual result is :
Initializing...
Loading binary...
Compiling module...
Creating callback...
Instantiating module...
Extracting export...
Export size : 1
Calling test ...
sum_i32_host Results: 3
Segmentation fault (core dumped)

**Comment by lum1n0us** [comment]
need to patch

```c
    // it likes "func (param i32) (result i32)"
    own wasm_functype_t* func_type = wasm_functype_new_1_1(wasm_valtype_new_i32(), wasm_valtype_new_i32());
    own wasm_func_t* func = wasm_func_new(store, func_type, sum_i32);
```
==>
```c
    // it likes "func (param i32 i32)"
    own wasm_functype_t* func_type = wasm_functype_new_2_0(wasm_valtype_new_i32(), wasm_valtype_new_i32());
    own wasm_func_t* func = wasm_func_new(store, func_type, sum_i32);
```

**Comment by Zhangyx24** [comment]
Thanks a lot !
I modify the code according to your reply, but still get the wrong result :

## In macOS
#### (1)interpreter mode
<img width="286" alt="截屏2022-08-10 上午11 37 17" src="https://user-images.githubusercontent.com/28601300/183807739-e4575035-8d68-4056-bd24-26a4799f24f4.png">

#### (2)AoT mode
<img width="318" alt="截屏2022-08-10 上午11 37 26" src="https://user-images.githubusercontent.com/28601300/183807748-181bab1b-bb8e-48df-8cfa-7495ab62c3c2.png">


## In Ubuntu
#### (1)interpreter mode
<img width="297" alt="截屏2022-08-10 上午11 37 37" src="https://user-images.githubusercontent.com/28601300/183807767-79dc1bf5-c350-4c80-8645-9cf3a0f26c2e.png">

#### (2)AoT mode
<img width="323" alt="截屏2022-08-10 上午11 37 46" src="https://user-images.githubusercontent.com/28601300/183807781-a72fe965-a4e4-47c6-8a9a-019ebaa7b5f0.png">

**Comment by lum1n0us** [comment]
My mistake on forgetting to mention that:

`void sum_i32(` should be `wasm_trap_t * sum_i32` and might want to add `return NULL;`  at the end.

Btw, please make sure to fix all compilation warnings.  Usually, they are helpful.

**Comment by Zhangyx24** [comment]
Thanks a lot !
