### ISSUE TITLE
 Unpected Behavior in iwasm

### ISSUE THREAD

**Issue by erxiaozhou** [bytecodealliance/wasm-micro-runtime#1463]
# Build commands
I compile the code with commit id da79e3e9b283272a63ad53b24310d88c640fbd8a.
Platform: Ubuntu 20.04
CPU: amd64 
compile:
```shell
export CC=/usr/bin/clang-14
export CXX=/usr/bin/clang++-14
cd product-mini/platforms/linux/;rm -rf build
cmake  -DWAMR_BUILD_INTERP=1 -DWAMR_BUILD_AOT=0 -DCMAKE_BUILD_TYPE=Debug -DWAMR_BUILD_FAST_INTERP=0 -Bbuild
cd build
make -j40
```
execute:
```shell
iwasm --heap-size=0 -f _start cp907_b1.wasm
```

[cp907_b1.zip](https://github.com/bytecodealliance/wasm-micro-runtime/files/9523519/cp907_b1.zip)

# Expected behavior:
It should raise an exception indicating the "unknown opcode 0xc5 (at offset 0xce)".

# Actual behavior:
On the code with commit id da79e3e9b283272a63ad53b24310d88c640fbd8a , iwasm output:
```
0x3ff570a3:i32
```

Thank you.

**Comment by wenyongh** [comment]
@erxiaozhou Thanks for reporting the issue! I uploaded PR #1464, please try again.

**Comment by wenyongh** [comment]
Close this issue as it was fixed.
