### ISSUE TITLE
Local count check

### ISSUE THREAD

**Issue by erxiaozhou** [bytecodealliance/wasm-micro-runtime#1501]
# Build commands
I compile the code with commit id f5939c7bc1930ecaaa42f5bf332e084753689400.
Platform: Ubuntu 20.04
CPU: amd64 
compile:
```shell
export CC=/usr/bin/clang-14
export CXX=/usr/bin/clang++-14
cd product-mini/platforms/linux/;rm -rf build
cmake  -DWAMR_BUILD_INTERP=1 -DWAMR_BUILD_AOT=0 -DCMAKE_BUILD_TYPE=Debug -DWAMR_BUILD_FAST_INTERP=0 -Bbuild
cd build
make -j40
```
execute:
```shell
iwasm --heap-size=0 -f _start cp907_b5g.wasm
```

[cp907_b5g.zip](https://github.com/bytecodealliance/wasm-micro-runtime/files/9591212/cp907_b5g.zip)

# Expected behavior:
It seems that the module can be executed without exception. Because according to the specification, the value count can be declared as zero.

# Actual behavior:
There is an error: 
```
WASM module load failed: invalid local count
```

Looking forward to your reply.
Thank you.

**Comment by wenyongh** [comment]
@erxiaozhou Thanks a lot, please try #1504.
