### ISSUE TITLE
`__wasi_socket_accept` deceleration conflicted

### ISSUE THREAD

**Issue by lum1n0us** [bytecodealliance/wasm-micro-runtime#1528]
The declaration of `__wasi_socket_accept` in [wasi_socket_ext.h](https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/core/iwasm/libraries/lib-socket/inc/wasi_socket_ext.h#L204) will be conflicted with [api.h](https://github.com/WebAssembly/wasi-libc/blame/05b3b876e63cdc919c79f5127a7ae8dbdb7b095f/libc-bottom-half/headers/public/wasi/api.h#L2015) in *wasi-libc*. 

WASI has supported *soket_accept* since  *wasi-sdk-15*,  and we need to sync up upstream modifications and keep backward compatibility for a while.

P.S.
I can't find any version related macros in [wasi-sdk package](https://github.com/WebAssembly/wasi-sdk/releases/tag/wasi-sdk-16), I guess `#ifdef __WASI_RIGHTS_SOCK_ACCEPT` is one option.

**Comment by lum1n0us** [comment]
@loganek please feel free to let me know your opinion.

**Comment by loganek** [comment]
Yes unfortunately wasi-libc at the moment is not versioned, so if we want to keep the compatibility with older SDKs, probably the `__WASI_RIGHTS_SOCK_ACCEPT` is the right option.

**Comment by lum1n0us** [comment]
@loganek Would you mind arranging the modification?

**Comment by loganek** [comment]
Yes, just opened a CR. Please note we're unable to support both new and old definition at the same time in WASM itself - I decided to move to new signature as I think the socket API isn't that widely used yet. `wasi_socket_ext.c` does support both wasi-sdk >= 15 and wasi-sdk < 15, so we just expect any potential users to recompile their applications with no modifications (if they're written in C) or update `__wasi_sock_accept` host call if they use different langauge.
