### ISSUE TITLE
[CI binary release] add a workflow to generate wamr-lldb

### ISSUE THREAD

**Issue by lum1n0us** [bytecodealliance/wasm-micro-runtime#1537]
Reference:
https://github.com/xujuntwt95329/lldb_release/blob/main/.github/workflows/release.yml

Plus, it might be a one-time job but it consumes hours. Shall we consider cache the binary content or copy binary files from past releases?

**Comment by loganek** [comment]
Our team is looking to improve the debugging experience in WAMR and we can propose a patch for that if you're interested in?

**Comment by lum1n0us** [comment]
- [ ] release on MacOS
- [ ] release on Windows ?
- [ ] reuse binaries from previous releases if there is no modification ?
- [ ] or speed up the compilation ?

**Comment by lum1n0us** [comment]
https://github.com/bytecodealliance/wasm-micro-runtime/pull/1587

**Comment by lum1n0us** [comment]
Using https://github.com/bytecodealliance/wasm-micro-runtime/pull/1605 to speed up.
