### ISSUE TITLE
does wamr support async programing?

### ISSUE THREAD

**Issue by gneworld** [bytecodealliance/wasm-micro-runtime#1570]
If it does, I appreciate your examples, thanks much~

**Comment by wenyongh** [comment]
Hi, WAMR supports multi-thread and pthread library, including `pthread_cond_wait`, `pthread_cond_timedwait`, `pthread_cond_signal` and others, you can refer to the [document](https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/doc/pthread_library.md) and [sample](https://github.com/bytecodealliance/wasm-micro-runtime/tree/main/samples/multi-thread), not sure whether it meets your requirements?
