### ISSUE TITLE
[CI Optimization] Add Fast-JIT into CIs

### ISSUE THREAD

**Issue by lum1n0us** [bytecodealliance/wasm-micro-runtime#1571]
- [x] Add `WAMR_BUILD_FAST_JIT` into iwasm compilation combination test
- [x] Add `WAMR_BULID_FAST_JIT` into wasm-c-api compilation combination test
- [x] Add *fast-jit* into spec test jobs
- [x] Adjust spec test feature combination
- [x] Remove `MC_JIT_BUILD_OPTIONS` from *.github/workflow/compilation_**

**Comment by lum1n0us** [comment]
| OS                 | defulat               | +multi module | +simd      | +thread              |
| ------------------ | --------------------- | ------------- | ---------- | -------------------- |
| ubuntu-2004        | INTERP(2)+JIT(LF)+AOT | INTERP(2)     | JIT(L)+AOT | INTERP(2)+JIT(L)+AOT |
| ubuntu-2004 x86_32 | INTERP(2)+AOT         | NA            | NA         | INTERP(2)+AOT        |
| ubuntu-2004 sgx    | INTERP(2)+AOT         | NA            | AOT        | NA                   |

> - JIT(LF): LLVM JIT and FAST JIT
> - JIT(L): LLVM JIT
> - JIT(F): FAST JIT
> - SGX enables `thread` option by default

**Comment by wenyongh** [comment]
Close as all the tasks were done
