### ISSUE TITLE
Some bugs in the `request.ts` file

### ISSUE THREAD

**Issue by hangedfish** [bytecodealliance/wasm-micro-runtime#1581]
`not_expire` is the same as `is_expire` in the `request.ts` file. This is a bug.

https://github.com/bytecodealliance/wasm-micro-runtime/blob/e53ab91439f1e5d212a650b4b004528880cc0798/assembly-script/wamr_app_lib/request.ts#L125-L141

**Comment by hangedfish** [comment]
another bug in the `request.ts` file.

`COAP_PUT` -> `COAP_DELETE`

https://github.com/bytecodealliance/wasm-micro-runtime/blob/e53ab91439f1e5d212a650b4b004528880cc0798/assembly-script/wamr_app_lib/request.ts#L386-L391

**Comment by xujuntwt95329** [comment]
Thanks a lot for reporting this, we've fixed in #1597
