### ISSUE TITLE
Unable to build the sample socket build api

### ISSUE THREAD

**Issue by jakob999999** [bytecodealliance/wasm-micro-runtime#1629]
I ran into the following issues when I try to build the sample Socket API. Has anyone had the same issues, because it seems like there is something wrong with the declarations of the files provided?

![WAMRSocketApiIssues](https://user-images.githubusercontent.com/107719568/197291860-fa31a6d7-1d77-413c-891e-e77cc8423602.jpg)

**Comment by loganek** [comment]
Hi @jakob999999 , we recently migrated to newer wasi-sdk, and the build most likely fails because you still use older version. Can you please try to install wasi-sdk version 15 or newer?

See https://github.com/bytecodealliance/wasm-micro-runtime/issues/1528 for details.

**Comment by mmathys** [comment]
Had the same issue, fixed it updating wasi-sdk
