### ISSUE TITLE
cannot copy libraries when use linux-sgx as subdirectory in other projects

### ISSUE THREAD

**Issue by jxiao1** [bytecodealliance/wasm-micro-runtime#165]
If I use this repo as a submodule in another project and build linux-sgx like this:
add_subdirectory(wasm/wamr/product-mini/platforms/linux-sgx/)

The following copy action will result in error:
set (copy_libs_cmd cp -a libvmlib.a libextlib.a ../enclave-sample/)
add_custom_target (copy_libs_to_enclave ALL COMMAND ${copy_libs_cmd} DEPENDS vmlib extlib)

I just removed the above "set" line as a workaround

**Comment by jxiao1** [comment]
Another problem is I need to source <SGX_SDK dir>/environment before build linux-sgx,  I suggest to add a default SDX_SDK path value in the linux-sgx/CMakelist.txt file.

**Comment by xwang98** [comment]
@jxiao1 thank you for fixing the problem.
