### ISSUE TITLE
Support for FreeBSD?

### ISSUE THREAD

**Issue by girgen** [bytecodealliance/wasm-micro-runtime#1661]
Could we get WAMR to provide cmake for freebsd. I browsed the source and go as far as that it is just not implemented yet. The interface needs to be implemented for that platform, AFAICS. Copying the Darwin config might be a good start?

See https://github.com/fluent/fluent-bit/issues/6289#issue-1425488799 for details. 

Thanks!
Palle

**Comment by TianlongLiang** [comment]
Thanks for bringing this issue to our attention, I will start looking into it. I will keep you posted on the progress

**Comment by TianlongLiang** [comment]
I finished setting up my FreeBSD environment(FreeBSD newbie here, it took me some time:joy:), and I plan to try [port tutorial](https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/doc/port_wamr.md). Hopefully, I can make it works in the next few days. :smile:

**Comment by TianlongLiang** [comment]
I follow the tutorial I mentioned, get it able to compile on FreeBSD, and push the code [to my fork](https://github.com/TianlongLiang/wasm-micro-runtime/tree/dev/freebsd). I will start some further testing in the next few days. Meanwhile, I would appreciate it if you could try it too and tell me any problem you encounter. @girgen :laughing:

**Comment by TianlongLiang** [comment]
https://github.com/bytecodealliance/wasm-micro-runtime/pull/1825 pr for FreeBSD support was merged, any more suggestions or questions?

**Comment by girgen** [comment]
Looks great, AFAICT. Thanks!
