### ISSUE TITLE
Advice for reducing rust WASM app footprint

### ISSUE THREAD

**Issue by Therdel** [bytecodealliance/wasm-micro-runtime#1694]
[Build WASM applications](https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/doc/build_wasm_app.md) has a paragraph "[How to reduce the footprint?](https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/doc/build_wasm_app.md#2-how-to-reduce-the-footprint)" for building C code with the WASI-SDK.

The Rust part could use equivalent suggestions.
- reduce the (auxiliary?)stack size down from the default 1MB [[source](https://github.com/rustwasm/wasm-bindgen/issues/1345#issuecomment-472872310)] - which is too much for many MCU scenarios.
Passing linker arguments is possible in a `[rust workspace root]/.cargo/config.toml` file.
This reduces said stack-size to 8192Bytes:
```toml
[build]
rustflags = [
  "-C", "link-arg=-zstack-size=8192",
]
```
- Passing other flags suggested for the WASI-SDK also works as rustc uses LLVM, too.
Here with --strip-all, --allow-undefined and --initial-memory:
```toml
[build]
rustflags = [
  "-C", "link-arg=--strip-all",
  "-C", "link-arg=--allow-undefined",
  "-C", "link-arg=--initial-memory=65536",
]
```
- Not using the print-formatting infrastructure reduced my binary size from 22680 to 237 Bytes.

**Comment by wenyongh** [comment]
@Therdel Many thanks for the advice! We will update the document according to you suggestion.

**Comment by Therdel** [comment]
You're welcome!

**Comment by wenyongh** [comment]
@Therdel I updated the document in #1701, thanks.
