### ISSUE TITLE
Unexpected value on the stack (classic interpreter)

### ISSUE THREAD

**Issue by erxiaozhou** [bytecodealliance/wasm-micro-runtime#1728]
# Build commands
I compile the code with commit id f59ffa0d63f832982da1caa524aaac146f3f1422.
Platform: Ubuntu 20.04
CPU: amd64 
compile:
```shell
export CC=/usr/bin/clang-14
export CXX=/usr/bin/clang++-14
cd product-mini/platforms/linux/;rm -rf build
cmake  -DWAMR_BUILD_INTERP=1 -DWAMR_BUILD_AOT=0 -DCMAKE_BUILD_TYPE=Debug -DWAMR_BUILD_FAST_INTERP=0 -Bbuild
cd build
make -j40
```
execute:
```shell
iwasm --heap-size=0 -f to_test <tc_name>
```
[iwasm_nan1.zip](https://github.com/bytecodealliance/wasm-micro-runtime/files/10047806/iwasm_nan1.zip)

# Actual behavior:
The value left on the stack is ['0x39', '0x0', '0x0', '0x0', '0x0', '0x0', '0xf0', '0x7f']

# Expected behavior:
The value left on the stack is ['0x39', '0x0', '0x0', '0x0', '0x0', '0x0', '0xf8', '0x7f'] (The most significant bit of payload is 1)

**Comment by wenyongh** [comment]
Hi, thanks for reporting the issue! I submitted PR #1733 to fix it, could you please help review the patch and try again? Thanks.
