### ISSUE TITLE
Integrate WASI test suite to a WAMR build

### ISSUE THREAD

**Issue by loganek** [bytecodealliance/wasm-micro-runtime#1761]
Bytecode Alliance started a new project for unifying WASI tests; we already have a [repository](https://github.com/WebAssembly/wasi-testsuite) with quite a few test cases (we'll be expanding it over time, contributions are also welcome) and test harness to execute tests.
@yamt already added an adapter for WAMR here: https://github.com/WebAssembly/wasi-testsuite/pull/16 so the runtime can be already validated. The next step is to integrate the test suite with WAMR's CI; this can be done by following the steps in [documentation](https://github.com/WebAssembly/wasi-testsuite#getting-started). I already checked locally, at the moment WAMR passes all of the tests defined in the repository on Linux platform.

WASI test harness also allows executing tests for APIs that are not part of the snapshot, so in the future we can implement and run tests for e.g. pthread library or sockets.

**Comment by wenyongh** [comment]
Done with #1832.
