### ISSUE TITLE
WASM module load failed: invalid section id

### ISSUE THREAD

**Issue by rt21q8** [bytecodealliance/wasm-micro-runtime#1769]
# Issue
I have a basic WASM/WASI application compiled with `tinygo` which when attempted to execute with `iwasm` fails with:
```bash
$ iwasm wasi.wasm
WASM module load failed: invalid section id
```
The same file executes correctly with runtimes like `wasmtime` and `wasmer`.
# Reproduction
## Sample app:
```go
package main

import "fmt"

func main() {
  fmt.Println("hello")
}
```
## Steps to build application:
```bash
$ tinygo version
tinygo version 0.26.0 linux/amd64 (using go version go1.19.3 and LLVM version 14.0.0)
$ tinygo build -o wasi.wasm -target wasi main.go
```
## Running with `iwasm`:
```bash
$ iwasm --version
iwasm 1.1.1
$ iwasm wasi.wasm 
WASM module load failed: invalid section id
```
## Running with other runtimes:
```bash
$ wasmtime wasi.wasm 
hello
$ wasmer wasi.wasm 
hello
```

Are only files build with [Build WASM applications](https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/doc/build_wasm_app.md#build-wasm-applications) supported or is this different issue?

**Comment by TianlongLiang** [comment]
Hi, can you try adding `-DWAMR_BUILD_BULK_MEMORY=1` when building iwasm with CMake and see if that works?
