### ISSUE TITLE
Import/Export mutable globals extension

### ISSUE THREAD

**Issue by Rewbert** [bytecodealliance/wasm-micro-runtime#1782]
Hi!

This runtime has everything that I would need apart from the above mentioned extension, specified here: https://github.com/WebAssembly/mutable-global/blob/master/proposals/mutable-global/Overview.md

I am not too familiar with implementing wasm runtimes though, and was wondering if someone could hint at me how much work it would be to implement this? Or maybe this is something that is already in the works?

Thanks!

**Comment by lum1n0us** [comment]
create two modules

- mA

``` wat
(module
  (global $g1 (export "global-i32") i32 (i32.const 55))
  (global $g2 (export "global-mut-i64") (mut i64) (i64.const 66))

  (func (export "get-g1") (result i32)
    (global.get $g1)
  )

  (func (export "get-g2") (result i64)
    (global.get $g2)
  )

  (func (export "set-g2") (param i64)
    (local.get 0)
    (global.set $g2)
  )
)
```

- mB

``` wat
(module
  (global $g1 (import "mA" "global-i32") i32)
  (global $g2 (import "mA" "global-mut-i64") (mut i64))

  (func (export "get-g1") (result i32)
    (global.get $g1)
  )

  (func (export "get-g2") (result i64)
    (global.get $g2)
  )

  (func (export "set-g2") (param i64)
    (local.get 0)
    (global.set $g2)
  )
)
```

transform .wat to .wasm

run with iwasm

```
$./iwasm  -f get-g2 mB.wasm
0x42:i64
```
