### ISSUE TITLE
Important synchronization issue

### ISSUE THREAD

**Issue by qianyimao** [bytecodealliance/wasm-micro-runtime#1805]
it will miss notification in "os_cond_signal" while "os_cond_wait_internal" updating "korp_cond.wait_list_lock" or there isn't a thread is waiting. windows platform.

**Comment by wenyongh** [comment]
Hi, yes, but it really requires preparation for os_cond_wait to start waiting the notification. Is there any idea from you? Thanks.

**Comment by qianyimao** [comment]
append a "count" field in "korp_cond" which indicates the missed signal count.
increase "count" when "thread_wait_list" is null in os_cond_signal.
check "count" before waiting in os_cond_wait_internal.
maybe it work.

**Comment by qianyimao** [comment]
or limit the ”count” in 0,1.

**Comment by qianyimao** [comment]
1.platform_internal.h
typedef struct korp_cond {
    korp_mutex wait_list_lock;
    os_thread_wait_list thread_wait_list;
    int signaled;
}
 
2.win_thread.c!os_cond_init
cond->thread_wait_list = NULL;
cond->signaled = FALSE;
 
3.win_thread.c!os_cond_wait_internal
os_mutex_lock(&cond->wait_list_lock);
if (cond->signaled) {
    node = NULL;
    cond->signaled = FALSE;
}
else {
    ...
}
os_mutex_unlock(&cond->wait_list_lock);
if (!node) { return BHT_OK; }
 
4.win_thread.c!os_cond_signal
if (cond->thread_wait_list)
    os_sem_signal(&cond->thread_wait_list->sem);
else
    cond->signaled = TRUE;

**Comment by qianyimao** [comment]
maybe the patch work.

**Comment by wenyongh** [comment]
Hi, there may be issue for this patch: the signal thread sets `cond->signaled` to `true` and expects the waiting thread to directly return when it detects that its `cond->signaled` is set to true, but suppose that the waiting thread doesn't call os_cond_wait immediately, instead, it does something for some time (e.g. a loop or sleep(5)), and then calls os_cond_wait the cond, is it correct to return directly in this situation?

My understanding of your concern is that appending the wait node to the end of wait node list may take some time:
```C
        /* Add to end of wait list */
        os_thread_wait_node *p = cond->thread_wait_list;
        while (p->next)
            p = p->next;
        p->next = node;
```
Maybe we can refine the code to append the node quickly, is it OK for you?

**Comment by qianyimao** [comment]
It does not affect the execution of any thread. you just treat the cond as a state.

**Comment by qianyimao** [comment]
appending the wait node is correct because of the mutex.

**Comment by qianyimao** [comment]
@wenyongh any plan to fix the issue?

**Comment by wenyongh** [comment]
@qianyimao Sure, I submitted PR #1853 to refine the related operations, could you help review and test it?

**Comment by qianyimao** [comment]
this did not resolve the issue.reason of issue is that function os_cond_signal doesn’t change state of cond.

**Comment by qianyimao** [comment]
@wenyongh

**Comment by wenyongh** [comment]
@qianyimao Do you mean to apply the patch as you proposed before which adds `signaled` flag to the cond? Wondering why set `signaled` to true when cond_signal, and check it in cond_wait/cond_timedwait? It may cause unexpected behavior.

The [manual](https://linux.die.net/man/3/pthread_cond_signal) of pthread_cond_signal mentions that
```
The pthread_cond_broadcast() and pthread_cond_signal() functions shall have no effect if there are no threads currently blocked on cond.
```
For the app below, the normal behavior is that the current thread is blocked by `pthread_cond_wait`, but if your patch is applied, per my understanding, it won't be blocked by `pthread_cond_wait` since the `signaled` flag is set to true by `pthread_cond_signal`, and then `pthread_cond_wait` returns directly when finding `signaled` is true:
```C
#include <stdio.h>
#include <pthread.h>

int main(int argc, char **argv)
{
    pthread_mutex_t mutex;
    pthread_cond_t cond;

    pthread_mutex_init(&mutex, NULL);
    pthread_cond_init(&cond, NULL);

    pthread_mutex_lock(&mutex);
    printf("##cond signal\n");
    pthread_cond_signal(&cond);
    pthread_mutex_unlock(&mutex);

    pthread_mutex_lock(&mutex);
    printf("##cond wait\n");
    pthread_cond_wait(&cond, &mutex);
    pthread_mutex_unlock(&mutex);

    printf("##return\n");
    return 0;
}
```

**Comment by qianyimao** [comment]
@wenyongh  i misunderstood the usage of pthread_cond_t. it isn't singal safe.
the unsafe leads a other issue, i will describe it at next issue.
no patch needed for this.

**Comment by qianyimao** [comment]
remove PR https://github.com/bytecodealliance/wasm-micro-runtime/pull/1853 please
