### ISSUE TITLE
WASM C API (wasm_instance_new_with_args) fails with empty or null imports

### ISSUE THREAD

**Issue by blackbird1** [bytecodealliance/wasm-micro-runtime#1833]
This assertion is cryptic and hard to understand. It fails with empty or null imports.

https://github.com/bytecodealliance/wasm-micro-runtime/blob/d04f3988c3e456788c72f44cf807b4af35d94968/core/iwasm/common/wasm_c_api.c#L4853

**Comment by wenyongh** [comment]
Thanks for reporting the issue, seems that we had better remove the assertion.

**Comment by lum1n0us** [comment]
@wenyongh  @blackbird1 actually, I am thinking about enhancing the assertion about `wasm_extern_vec_t imports` and preventing `wasm_instance_new` from invalid `imports`. 

from [the spec](https://webassembly.github.io/spec/core/exec/modules.html#instantiation):
> If the number  of imports is not equal to the number  of provided external values then: Fail.

**Comment by wenyongh** [comment]
> @wenyongh @blackbird1 actually, I am thinking about enhancing the assertion about `wasm_extern_vec_t imports` and preventing `wasm_instance_new` from invalid `imports`.
> 
> from [the spec](https://webassembly.github.io/spec/core/exec/modules.html#instantiation):
> 
> > If the number  of imports is not equal to the number  of provided external values then: Fail.

Do you mean we change the assertion like:
```C
    if (import_func_count > 0)
        bh_assert((uint32)(func_import - *p_func_imports) == import_func_count); 
    }
```
Or
```C
    bh_assert(import_func_count == 0
              || (uint32)(func_import - *p_func_imports) == import_func_count); 
```
The above code won't be impacted by the these lines, right?
```C
        if (wasm_extern_kind(in) != WASM_EXTERN_FUNC)
            continue;
```
Since import_count is the total count of imports, and import_func_count is the total count of import functions. And if the latter is larger than 0, all the import functions must be linked, and `(uint32)(func_import - *p_func_imports) == import_func_count)` must be valid.

**Comment by lum1n0us** [comment]
- add a checker at [the beginning](https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/core/iwasm/common/wasm_c_api.c#L4730). If `imports` doesn't match the module requirement, like length, fail.
- https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/core/iwasm/common/wasm_c_api.c#L4853 should be lik `bh_assert(import_func_count == 0 || (uint32)(func_import - *p_func_imports) == import_func_count); `

**Comment by lum1n0us** [comment]
#1843
