### ISSUE TITLE
Llvm clone depth

### ISSUE THREAD

**Issue by Rochet2** [bytecodealliance/wasm-micro-runtime#184]
https://github.com/bytecodealliance/wasm-micro-runtime/blob/2e36149e326dab2374eda01bd7be5810942a5db5/wamr-compiler/build_llvm.sh#L11

Would it be a good idea to restrict clone depth to 1 or similar in the build script?
Downloading all history (200 000 commits) takes forever and is probably unnecessary most of the time I would imagine.

**Comment by xwang98** [comment]
That would be a good idea. Do you know any command/arugment available for downloading the snapshot without history versions? @Rochet2

**Comment by Rochet2** [comment]
One can use `git clone --depth 1 https://github.com/llvm-mirror/llvm.git`
to only get latest commit. Or specify another depth to get more if needed.
Afterwards one can use `git fetch --unshallow` to fetch all history.

**Comment by xwang98** [comment]
Thank you for the comments. I just updated the script. @Rochet2
