### ISSUE TITLE
Is non-SGX still sandboxed?

### ISSUE THREAD

**Issue by rygo6** [bytecodealliance/wasm-micro-runtime#1906]
I notice the main page says `TEE(Trusted Execution Environment) support(SGX/TDX)`
https://bytecodealliance.github.io/wamr.dev/

Does that mean WAMR can only run untrusted code on Intel processors through its SGX support? Or is WAMR still appropriately sandboxed with SGX disabled?

**Comment by wenyongh** [comment]
Hi, WAMR supports many platforms, such as linux, linux-sgx, macos, windows, android and so on, you can build and run WAMR without SGX, refer to: 
https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/doc/build_wamr.md#linux
https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/doc/build_wamr.md#macos

**Comment by xwang98** [comment]
Without SGX, WAMR is still sandbox. @rygo6
