### ISSUE TITLE
Thread stack size error when cross compiling

### ISSUE THREAD

**Issue by arjunr2** [bytecodealliance/wasm-micro-runtime#1976]
When cross-compiling from my x86-64 machine to AARCH64, threads fail on creation at runtime due to not satisfying minimum pthread stack size.

The default thread stack size of application on both x86_64 and AARCH64 = 32K
Minimum size for x86_64 (Linux) = 16K (works properly)
Minimum size for AARCH64 (Linux) = 128K (fails)

Seems like the minimum size is dependent on the architecture, and default thread stack size doesn't adapt correctly to it

**Comment by wenyongh** [comment]
Hi, could you try defining the default app thread stack size in CMakeLists.txt:
```cmake
add_definitions(-DAPP_THREAD_STACK_SIZE_DEFAULT=n)
```
