### ISSUE TITLE
Does WAMR AoT implement atomic.fence?

### ISSUE THREAD

**Issue by arjunr2** [bytecodealliance/wasm-micro-runtime#2010]
It looks like the compiler/interpreter just skips over the bytecode. Correct me if I'm wrong

**Comment by TianlongLiang** [comment]
We supported it in [this recent PR](https://github.com/bytecodealliance/wasm-micro-runtime/pull/2013). Now all running modes except Fast JIT support atomic.fence. Fast JIT is currently implementing the threads opcode and will support atomic.fence once it is finished.
