### ISSUE TITLE
lldb-wasm.patch apply doesn't work on the main branch

### ISSUE THREAD

**Issue by g0djan** [bytecodealliance/wasm-micro-runtime#2035]
https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/doc/source_debugging.md?plain=1#L42

**Comment by xujuntwt95329** [comment]
Hi @g0djan

Thanks for reporting this issue, the document is outdated, I've submitted a PR https://github.com/bytecodealliance/wasm-micro-runtime/pull/2051 to fix it

BTW, currently WAMR will create pre-built lldb binary for every [release](https://github.com/bytecodealliance/wasm-micro-runtime/releases), you can download a binary for your platform directly.
