### ISSUE TITLE
[HELP] remote Debug linux wasm from windows lldb

### ISSUE THREAD

**Issue by xujiesh0510** [bytecodealliance/wasm-micro-runtime#2054]
remote  Debug linux wasm from linux version of lldb(https://github.com/bytecodealliance/wasm-micro-runtime/releases) is ok.

i try to build lldb.exe On windows . follow the instruction(wasm-micro-runtime main branch):
https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/doc/source_debugging.md

build env( from https://lldb.llvm.org/resources/build.html):
[Windows](https://lldb.llvm.org/resources/build.html#id7)
Visual Studio 2019.
The latest Windows SDK.
The Active Template Library (ATL).
[GnuWin32](http://gnuwin32.sourceforge.net/) for CoreUtils and Make.
[Python 3](https://www.python.org/downloads/windows/). Make sure to (1) get the x64 variant if that’s what you’re targetting and (2) install the debug library if you want to build a debug lldb. The standalone installer is the easiest way to get the debug library.
[Python Tools for Visual Studio](https://github.com/Microsoft/PTVS/). If you plan to debug test failures or even write new tests at all, PTVS is an indispensable debugging extension to VS that enables full editing and debugging support for Python (including mixed native/managed debugging).
[SWIG for Windows](http://www.swig.org/download.html)
The steps outlined here describes how to set up your system and install the required dependencies such that they can be found when needed during the build process. They only need to be performed once.

Install Visual Studio with the “Desktop Development with C++” workload and the “Python Development” workload.
Install GnuWin32, making sure <GnuWin32 install dir>\bin is added to your PATH environment variable. Verify that utilities like dirname and make are available from your terminal.
Install SWIG for Windows, making sure <SWIG install dir> is added to your PATH environment variable. Verify that swig is available from your terminal.
Install Python 3 from the standalone installer and include the debug libraries in the install, making sure the Python install path is added to your PATH environment variable.
Register the Debug Interface Access DLLs with the Registry from a privileged terminal.
> regsvr32 "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\DIA SDK\bin\msdia140.dll"
> regsvr32 "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\DIA SDK\bin\amd64\msdia140.dll"

git clone --branch release/13.x --depth=1 https://github.com/llvm/llvm-project
cd llvm-project
git apply ${WAMR_ROOT}/build-scripts/lldb-wasm.patch
mkdir build-lldb
cmake -S ./llvm -B build-lldb \
    -G Ninja \
    -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS="clang;lldb" \
    -DLLVM_TARGETS_TO_BUILD:STRING="X86;WebAssembly" \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DLLVM_BUILD_BENCHMARKS:BOOL=OFF \
    -DLLVM_BUILD_DOCS:BOOL=OFF  -DLLVM_BUILD_EXAMPLES:BOOL=OFF  \
    -DLLVM_BUILD_LLVM_DYLIB:BOOL=OFF  -DLLVM_BUILD_TESTS:BOOL=OFF  \
    -DLLVM_ENABLE_BINDINGS:BOOL=OFF  -DLLVM_INCLUDE_BENCHMARKS:BOOL=OFF  \
    -DLLVM_INCLUDE_DOCS:BOOL=OFF  -DLLVM_INCLUDE_EXAMPLES:BOOL=OFF  \
    -DLLVM_INCLUDE_TESTS:BOOL=OFF -DLLVM_ENABLE_LIBXML2:BOOL=ON
cmake --build build-lldb --target lldb --parallel 8

(lldb) platform select remote-linux
(lldb) process connect -p wasm connect://192.168.139.134:1234

llldb.exe can connect to iwasm in linux ,but breakpoint has no effects

(lldb) platform select remote-linux
  Platform: remote-linux
 Connected: no
(lldb) process connect -p wasm connect://192.168.139.134:1234
Process 1 stopped
* thread #1, name = 'nobody', stop reason = trace
    frame #0: 0x40000000000001e6
->  0x40000000000001e6: block
    0x40000000000001e8: call   20
    0x40000000000001ee: local.tee 0
    0x40000000000001f0: i32.eqz
(lldb) b foo
Breakpoint 1: no locations (pending).
WARNING:  Unable to resolve breakpoint to any actual locations.

using generator Visual Studio 16 2019 still the same :

cmake -S ./llvm -B build-lldb    -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS="clang;lldb"      -DLLVM_INCLUDE_TESTS:BOOL=OFF -DLLVM_ENABLE_LIBXML2:BOOL=ON   -DLLVM_INCLUDE_DOCS:BOOL=OFF  -DLLVM_INCLUDE_EXAMPLES:BOOL=OFF     -DLLVM_ENABLE_BINDINGS:BOOL=OFF  -DLLVM_INCLUDE_BENCHMARKS:BOOL=OFF -DLLVM_BUILD_LLVM_DYLIB:BOOL=OFF  -DLLVM_BUILD_TESTS:BOOL=OFF  -DLLVM_BUILD_DOCS:BOOL=OFF  -DLLVM_BUILD_EXAMPLES:BOOL=OFF  -DLLVM_TARGETS_TO_BUILD:STRING="X86;WebAssembly"  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DLLVM_BUILD_BENCHMARKS:BOOL=OFF

 how to slove this ? what's the right way to build lldb.exe? or  anybody can share the windows version of wasm lldb.exe ?

**Comment by xujuntwt95329** [comment]
Hi, previously I have built a Windows version, you can have a try: 
[debug-windows.zip](https://github.com/bytecodealliance/wasm-micro-runtime/files/11108164/debug-windows.zip)

As for the building instructions, I need to find a Windows environment to verify the steps, I‘ll update later

**Comment by xujiesh0510** [comment]
Thank you very much for your help. It took me days trying  to compile lldb on windows.

**Comment by xujuntwt95329** [comment]
You are welcome, hope the prebuilt binary can help you. 
It's really difficult to build on windows, and I found my previous steps don't work on latest windows, I need some time to figure out the problem
