### ISSUE TITLE
On WAMR-1.2.0's pre-release status

### ISSUE THREAD

**Issue by ZhongRuoyu** [bytecodealliance/wasm-micro-runtime#2063]
Hi! [Homebrew](https://github.com/Homebrew/brew) maintainer here. While packaging WAMR 1.2.0, I noticed that it is currently marked as a pre-release on the [releases page](https://github.com/bytecodealliance/wasm-micro-runtime/releases). So, I'm filing this issue to confirm what that means. Is it not ready for distribution yet?

**Comment by wenyongh** [comment]
Hi, the distribution is basically ready with many tests done, but we hope to do more tests and update some documents (if needed), which requires more time. And some developers may hope to release a version for their internal use, so we create a pre-release first. Refer to: https://github.com/bytecodealliance/wasm-micro-runtime/pull/2052

**Comment by ZhongRuoyu** [comment]
Hi @wenyongh, thanks for your clarification! In that case, let me postpone shipping 1.2.0 until it's fully ready for general usage.

**Comment by wenyongh** [comment]
@ZhongRuoyu WAMR-1.2.1 was released: https://github.com/bytecodealliance/wasm-micro-runtime/releases/tag/WAMR-1.2.1, please have a try, thanks.

**Comment by ZhongRuoyu** [comment]
Thanks @wenyongh. It seems someone did this before me: #127717. Now release 1.2.1 is on Homebrew.
