### ISSUE TITLE
Unexpected `wasm_runtime_module_malloc` behaviour

### ISSUE THREAD

**Issue by csegarragonz** [bytecodealliance/wasm-micro-runtime#2070]
Hi, I have been reading the articles on the WAMR blog. In particular, I was reading the one about the [heap usage](https://bytecodealliance.github.io/wamr.dev/blog/understand-the-wamr-heaps/), and have come accross some inconsistencies in the WAMR behaviour.

I have the following C++ code:

```cpp
// test.cpp
__attribute__((__import_module__("env"), __import_name__("external_malloc")))
int external_malloc(int malloc_size);

int main()
{
    external_malloc(3 * sizeof(int));
    return 0;
}
```

that I cross-compile using WASI-SDK verion 19:

```bash
/opt/wasi-sdk/bin/clang++ \
    --sysroot=/opt/wasi-sdk/share/wasi-sysroot \
    -Wl,--allow-undefined \
    -Wl,--export=malloc \
    -Wl,--export=free \
    test.cpp -o test.wasm
```

I then implement a very simple WASM runtime using WAMR in C++ (note that this a stripped down version of another project, aimed at reproducing the issue we found in a larger experiment):

```cpp
// main.cpp
#include "wasm_export.h"
#include "wasm_runtime_common.h"

#include <boost/program_options.hpp>
#include <iostream>
#include <sys/stat.h>
#include <vector>
#include <unistd.h>

namespace po = boost::program_options;

int32_t external_malloc(wasm_exec_env_t exec_env, int32_t malloc_size)
{
    std::cout << "Hello from external malloc!" << std::endl;
    WASMModuleInstanceCommon* module_inst = wasm_runtime_get_module_inst(exec_env);
    void *native_ptr = nullptr;
    int32_t wasmOffset = wasm_runtime_module_malloc(module_inst, malloc_size, &native_ptr);
    return wasmOffset;
}

po::variables_map parse_cmdline(int argc, char* argv[])
{
    // Define command line arguments
    po::options_description desc("Allowed options");
    desc.add_options()(
      "file", po::value<std::string>(), "WebAssembly function to run");

    po::positional_options_description p;
    p.add("func", 1);

    // Parse command line arguments
    po::variables_map vm;
    po::store(
      po::command_line_parser(argc, argv).options(desc).positional(p).run(),
      vm);
    po::notify(vm);

    return vm;
}

std::vector<uint8_t> load_bytes_from_file(const std::string& path)
{
    // Open file
    FILE* fp = fopen(path.c_str(), "rb");
    if (fp == nullptr) {
        throw std::runtime_error("error");
    }

    // Work-out file size
    struct stat statbuf;
    int staterr = fstat(fileno(fp), &statbuf);
    if (staterr < 0) {
        throw std::runtime_error("Couldn't stat file " + path);
    }
    size_t file_size = statbuf.st_size;
    std::vector<uint8_t> result;
    result.resize(file_size);

    // Load bytes to buffer
    size_t num_read = fread(result.data(), sizeof(uint8_t), file_size, fp);
    if (num_read != file_size) {
        throw std::runtime_error("Read less bytes than expected");
    }

    fclose(fp);
    return result;
}

int main(int argc, char* argv[])
{
    // ------------------
    // Command-Line Argument Parsing
    // ------------------

    auto vm = parse_cmdline(argc, argv);
    std::string func_path = vm["file"].as<std::string>();
    std::vector<uint8_t> func_bytes = load_bytes_from_file(func_path);

    // ------------------
    // Initialise WAMR runtime
    // ------------------

    RuntimeInitArgs init_args;
    memset(&init_args, 0, sizeof(RuntimeInitArgs));

    init_args.mem_alloc_type = Alloc_With_System_Allocator;

    static NativeSymbol native_symbols[] = {
        {"external_malloc", (void*)external_malloc, "(i)i", nullptr}
    };

    // Native symbols need below registration phase
    init_args.n_native_symbols = sizeof(native_symbols) / sizeof(NativeSymbol);
    init_args.native_module_name = "env";
    init_args.native_symbols = native_symbols;

    if (!wasm_runtime_full_init(&init_args)) {
        printf("Init runtime environment failed.\n");
        return -1;
    }

    // ------------------
    // Instantiate WASM module and call function
    // ------------------

    // Load WASM module
    std::string error_buffer(256, '\0');
    auto module_deleter = [&](wasm_module_t mod) {
        if (mod != nullptr) {
            wasm_runtime_unload(mod);
        }
    };
    std::unique_ptr<WASMModuleCommon, decltype(module_deleter)> module(
        wasm_runtime_load(func_bytes.data(),
                          func_bytes.size(),
                          error_buffer.data(),
                          error_buffer.size()),
        module_deleter
    );
    if (module == nullptr) {
        std::cerr << "Error loading WASM module: " << error_buffer << std::endl;
        throw std::runtime_error("Error loading WASM module");
    }

    // Create module instance
    uint32_t stack_size = 8092;
    uint32_t heap_size = 8092;
    auto instance_deleter = [&](wasm_module_inst_t inst) {
        if (inst != nullptr) {
            wasm_runtime_deinstantiate(inst);
        }
    };
    std::unique_ptr<WASMModuleInstanceCommon, decltype(instance_deleter)> module_inst(
        wasm_runtime_instantiate(module.get(),
                                 stack_size,
                                 0, // change to `heap_size` to remove the allocation error
                                 error_buffer.data(),
                                 error_buffer.size()),
        instance_deleter
    );
    if (module_inst == nullptr) {
        std::cerr << "Error instantiating the WASM module: " << error_buffer << std::endl;
        throw std::runtime_error("Error instantiating WASM module");
    }

    bool success = wasm_application_execute_main(module_inst.get(), 0, NULL);
    if (!success) {
        std::cerr << "Error executing main function" << std::endl;
        throw std::runtime_error("Error executing function");
    }

    return 0;
}
```

The runtime can be compiled with this [CMakeLists.txt](https://github.com/bytecodealliance/wasm-micro-runtime/files/11080695/CMakeLists.txt) (the only exotic dependency should be `libboost-program-options-dev`). Also, make sure your `WAMR_ROOT_DIR` is pointing to a WAMR version checked-out to the latest commit.

Once built, you can run it, and it should throw a runtime exception.

```bash
./build/iwasm --file ./test.wasm
```

this should happen both with app-managed and wasi-managed heap.

However, if you change the call to `wasm_runtime_instantiate` and add a heap size (using the host-managed heap instead of the wasi-managed heap), and cross-compile again without exporting `malloc` and `free`, the program runs succesfully.

Another issue I found when replicating this one is that if I remove the return value from the implementation of `external_malloc` (i.e. comment out the `return` line), and build with `-DCMAKE_BUILD_TYPE=Debug`, `./build/iwasm --file ./test.wasm` runs fine with the app-managed heap, but when building in `Release` mode, the same execution throws a segmentation fault.

**Comment by panpaul** [comment]
I had a similar problem. Since 3977f0b, I am not able to allocate memory through `wasm_runtime_module_malloc` or `wasm_runtime_module_dup_data` in native APIs. I have analyzed it roughly and here are some of my understandings:

All malloc request will pass through `wasm_module_malloc` which will set the `exec_env` parameter of `wasm_module_malloc_internal` to `NULL`. Through the call chain, the `NULL` `exec_env` is passed to `execute_malloc_function`. It will create an `exec_env` for calling the `malloc` function in wasm if `exec_env` is `NULL`.

But all function calls will check if the current `exec_env` is the same as `exec_env_tls` of the current thread, which is definitely different, thus raising an exception. `exec_env_tls` is set when the application is first executed, which means in all callbacks (native APIs), `exec_env_tls` is set.

I replaced the `NULL` parameter into `wasm_runtime_get_exec_env_tls()` here (and `core/iwasm/aot/aot_runtime.c` for AOT mode) and it solves this problem (I am not sure if this change is reasonable, but is works :)
https://github.com/bytecodealliance/wasm-micro-runtime/blob/3977f0b22a4b71770ad30bfe8e96757466e962e4/core/iwasm/interpreter/wasm_runtime.c#L2515-L2520

**Comment by wenyongh** [comment]
Hi, thanks for reporting the issue! I submitted PR #2072 to fix it, could you have a try?

**Comment by panpaul** [comment]
Thanks a lot! Now it works on my project :+1:

**Comment by csegarragonz** [comment]
This also fixes my issue! Thanks for the quick fix! :)
