### ISSUE TITLE
Review the job matrix for linux compilation 

### ISSUE THREAD

**Issue by Zzzabiyaka** [bytecodealliance/wasm-micro-runtime#2135]
Currently, for the most recent build we had 221 jobs spawned in matrix for `build_iwasm`(https://github.com/bytecodealliance/wasm-micro-runtime/actions/runs/4732767514) and the github limit is 256, from what I know there is no way to extend it. (https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration).

>Job matrix - A job matrix can generate a maximum of 256 jobs per workflow run. This limit applies to both GitHub-hosted and self-hosted runners.

We need to review the job matrix for `build_iwasm` on linux very carefully as we might shortly see the situation when we'll be blocked on this trying to add a new feature. 

- [] #2267

**Comment by lum1n0us** [comment]
YES. It(hit the limitation) has actually happened several times. 

I am going to list something as candidate solutions:
 
- split all jobs into several groups, like *per-PR* and *nightly*. Each group takes variant combinations and don't cross with others
- reduce compilation options(`WAMR_BUILD_XXX`). Some of them may be merged, some of them may be abandoned
- use pre-defined, meaningful combinations to replace current *exhaustive testing*

**Comment by Zzzabiyaka** [comment]
first suggestion that comes to mind: ubuntu-22 per PR, ubuntu-20 only nightly or vice versa. 

It will already make much difference and looks quite safe
