### ISSUE TITLE
wasm_export.h declares functions using fixed size int types wasm_runtime_common.c defines them using architectur types

### ISSUE THREAD

**Issue by kfessel** [bytecodealliance/wasm-micro-runtime#218]
i encounter this proplem while compilig for 'stm32f7' (ARM-Thumb 32Bit)

    wasm_export.h:
    bool
    wasm_runtime_call_wasm(wasm_exec_env_t exec_env,
                        wasm_function_inst_t function,
                        uint32_t argc, uint32_t argv[]);

    wasm_runtime_common.c:
    bool
    wasm_runtime_call_wasm(WASMExecEnv *exec_env,
                        WASMFunctionInstanceCommon *function,
                        unsigned argc, uint32 argv[])

compile time errors:

    In file included from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_runtime_common.c:10:0:
    Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_runtime_common.h:118:1: error: conflicting types for 'wasm_runtime_call_wasm'
    wasm_runtime_call_wasm(WASMExecEnv *exec_env,
    ^~~~~~~~~~~~~~~~~~~~~~
    In file included from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/shared/utils/bh_platform.h:31:0,
                    from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_runtime_common.c:6:
    Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/include/wasm_export.h:316:1: note: previous declaration of 'wasm_runtime_call_wasm' was here
    wasm_runtime_call_wasm(wasm_exec_env_t exec_env,
    ^~~~~~~~~~~~~~~~~~~~~~
    In file included from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_runtime_common.c:10:0:
    Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_runtime_common.h:129:1: error: conflicting types for 'wasm_application_execute_main'
    wasm_application_execute_main(WASMModuleInstanceCommon *module_inst,
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/shared/utils/bh_platform.h:31:0,
                    from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_runtime_common.c:6:
    Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/include/wasm_export.h:332:1: note: previous declaration of 'wasm_application_execute_main' was here
    wasm_application_execute_main(wasm_module_inst_t module_inst,
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_runtime_common.c:10:0:
    Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_runtime_common.h:134:1: error: conflicting types for 'wasm_application_execute_func'
    wasm_application_execute_func(WASMModuleInstanceCommon *module_inst,
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/shared/utils/bh_platform.h:31:0,
                    from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_runtime_common.c:6:
    Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/include/wasm_export.h:348:1: note: previous declaration of 'wasm_application_execute_func' was here
    wasm_application_execute_func(wasm_module_inst_t module_inst,
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_runtime_common.c:257:1: error: conflicting types for 'wasm_runtime_call_wasm'
    wasm_runtime_call_wasm(WASMExecEnv *exec_env,
    ^~~~~~~~~~~~~~~~~~~~~~
    In file included from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/shared/utils/bh_platform.h:31:0,
                    from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_runtime_common.c:6:
    Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/include/wasm_export.h:316:1: note: previous declaration of 'wasm_runtime_call_wasm' was here
    wasm_runtime_call_wasm(wasm_exec_env_t exec_env,
    ^~~~~~~~~~~~~~~~~~~~~~
    Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_runtime_common.c:1036:1: error: conflicting types for 'wasm_application_execute_main'
    wasm_application_execute_main(WASMModuleInstanceCommon *module_inst,
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/shared/utils/bh_platform.h:31:0,
                    from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_runtime_common.c:6:
    Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/include/wasm_export.h:332:1: note: previous declaration of 'wasm_application_execute_main' was here
    wasm_application_execute_main(wasm_module_inst_t module_inst,
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_runtime_common.c:1210:1: error: conflicting types for 'wasm_application_execute_func'
    wasm_application_execute_func(WASMModuleInstanceCommon *module_inst,
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/shared/utils/bh_platform.h:31:0,
                    from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_runtime_common.c:6:
    Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/include/wasm_export.h:348:1: note: previous declaration of 'wasm_application_execute_func' was here
    wasm_application_execute_func(wasm_module_inst_t module_inst,
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_runtime_common.c: In function 'wasm_application_execute_func':
    Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_runtime_common.c:1270:65: warning: format '%d' expects argument of type 'int', but argument 4 has type 'int32 {aka long int}' [-Wformat=]
                snprintf(buf, sizeof(buf), "invalid input argument %d.", i);
                                                                    ~^
                                                                    %ld
    Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_runtime_common.c:1350:65: warning: format '%d' expects argument of type 'int', but argument 4 has type 'int32 {aka long int}' [-Wformat=]
                snprintf(buf, sizeof(buf), "invalid input argument %d: %s.",
                                                                    ~^
                                                                    %ld
    Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_runtime_common.c:1373:27: warning: format '%x' expects argument of type 'unsigned int', but argument 2 has type 'uint32 {aka long unsigned int}' [-Wformat=]
                os_printf("0x%x:i32", argv1[0]);
                            ~^       ~~~~~~~~
                            %lx
    Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_runtime_common.c: At top level:
    cc1: warning: unrecognized command line option '-Wno-cast-function-type'
    make[2]: *** [Projekt/RIOT/Makefile.base:111: Projekt/iwasmr/bin/nucleo-f767zi/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_runtime_common.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    mkdir -p Projekt/iwasmr/bin/nucleo-f767zi/core/
    In file included from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_exec_env.c:7:0:
    Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_runtime_common.h:118:1: error: conflicting types for 'wasm_runtime_call_wasm'
    wasm_runtime_call_wasm(WASMExecEnv *exec_env,
    ^~~~~~~~~~~~~~~~~~~~~~
    In file included from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/shared/utils/bh_platform.h:31:0,
                    from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/shared/utils/bh_assert.h:9,
                    from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_exec_env.h:9,
                    from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_exec_env.c:6:
    Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/include/wasm_export.h:316:1: note: previous declaration of 'wasm_runtime_call_wasm' was here
    wasm_runtime_call_wasm(wasm_exec_env_t exec_env,
    ^~~~~~~~~~~~~~~~~~~~~~
    In file included from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_exec_env.c:7:0:
    Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_runtime_common.h:129:1: error: conflicting types for 'wasm_application_execute_main'
    wasm_application_execute_main(WASMModuleInstanceCommon *module_inst,
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/shared/utils/bh_platform.h:31:0,
                    from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/shared/utils/bh_assert.h:9,
                    from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_exec_env.h:9,
                    from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_exec_env.c:6:
    Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/include/wasm_export.h:332:1: note: previous declaration of 'wasm_application_execute_main' was here
    wasm_application_execute_main(wasm_module_inst_t module_inst,
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_exec_env.c:7:0:
    Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_runtime_common.h:134:1: error: conflicting types for 'wasm_application_execute_func'
    wasm_application_execute_func(WASMModuleInstanceCommon *module_inst,
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/shared/utils/bh_platform.h:31:0,
                    from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/shared/utils/bh_assert.h:9,
                    from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_exec_env.h:9,
                    from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_exec_env.c:6:
    Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/include/wasm_export.h:348:1: note: previous declaration of 'wasm_application_execute_func' was here
    wasm_application_execute_func(wasm_module_inst_t module_inst,
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    cc1: warning: unrecognized command line option '-Wno-cast-function-type'
    make[2]: *** [Projekt/RIOT/Makefile.base:111: Projekt/iwasmr/bin/nucleo-f767zi/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_exec_env.o] Error 1
    mkdir -p Projekt/iwasmr/bin/nucleo-f767zi/core/
    In file included from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_native.c:7:0:
    Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_runtime_common.h:118:1: error: conflicting types for 'wasm_runtime_call_wasm'
    wasm_runtime_call_wasm(WASMExecEnv *exec_env,
    ^~~~~~~~~~~~~~~~~~~~~~
    In file included from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/shared/utils/bh_platform.h:31:0,
                    from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/shared/utils/bh_common.h:9,
                    from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_native.h:9,
                    from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_native.c:6:
    Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/include/wasm_export.h:316:1: note: previous declaration of 'wasm_runtime_call_wasm' was here
    wasm_runtime_call_wasm(wasm_exec_env_t exec_env,
    ^~~~~~~~~~~~~~~~~~~~~~
    In file included from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_native.c:7:0:
    Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_runtime_common.h:129:1: error: conflicting types for 'wasm_application_execute_main'
    wasm_application_execute_main(WASMModuleInstanceCommon *module_inst,
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/shared/utils/bh_platform.h:31:0,
                    from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/shared/utils/bh_common.h:9,
                    from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_native.h:9,
                    from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_native.c:6:
    Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/include/wasm_export.h:332:1: note: previous declaration of 'wasm_application_execute_main' was here
    wasm_application_execute_main(wasm_module_inst_t module_inst,
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_native.c:7:0:
    Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_runtime_common.h:134:1: error: conflicting types for 'wasm_application_execute_func'
    wasm_application_execute_func(WASMModuleInstanceCommon *module_inst,
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/shared/utils/bh_platform.h:31:0,
                    from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/shared/utils/bh_common.h:9,
                    from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_native.h:9,
                    from Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/common/wasm_native.c:6:
    Projekt/iwasmr/iwasmt/wasm-micro-runtime/core/iwasm/include/wasm_export.h:348:1: note: previous declaration of 'wasm_application_execute_func' was here
    wasm_application_execute_func(wasm_module_inst_t module_inst,

**Comment by wenyongh** [comment]
@kfessel thanks for reporting the issue! We reproduced it recently when building WAMR in some other platform, and found that it is caused by type inconsistent of uint32_t /int32_t and unsigned/int, or, some functions' parameter uses uint32_t in wasm_export.h, while the same parameter uses unsigned in wasm_runtime_common.h, and the compiler treats them as different types. We have fixed the issue in recent patch, could you please pull and try again? thanks.
