### ISSUE TITLE
Drop or fix LLVM 14 support

### ISSUE THREAD

**Issue by yamt** [bytecodealliance/wasm-micro-runtime#2258]
it seems that the recent merge of PGO stuff broke a build with LLVM 14.
we should drop or fix it.
```
...wasm-micro-runtime/core/iwasm/compilation/aot_llvm_extra.cpp:351:13: error: unknown type name 'LICMOptions'
            LICMOptions licm_opt;
            ^
```

**Comment by wenyongh** [comment]
Thanks for reporting the issue! I submitted #2261 to fix it, let's support llvm-13/llvm-14 as possible as we can.

**Comment by yamt** [comment]
fixed by https://github.com/bytecodealliance/wasm-micro-runtime/pull/2261
