### ISSUE TITLE
Request: Rust bindings

### ISSUE THREAD

**Issue by rahul-thakoor** [bytecodealliance/wasm-micro-runtime#230]
Hello, is it possible to provide rust bindings for this library? thanks

**Comment by jmagnuson** [comment]
Looks like @rahul-thakoor created bindings per crate [`wamr-sys`](https://crates.io/crates/wamr-sys).

**Comment by lum1n0us** [comment]
https://github.com/bytecodealliance/wamr-rust-sdk/
