### ISSUE TITLE
Does iwasm support SGX2?

### ISSUE THREAD

**Issue by PeizhongQiu** [bytecodealliance/wasm-micro-runtime#2368]
Hello. I changed MiscSelect and DisableDebug option in product-mini/platforms/linux-sgx/enclave-sample/Enclave/Enclave.config.xml file:
```
<!-- Please refer to User's Guide for the explanation of each field -->
<EnclaveConfiguration>
  <ProdID>0</ProdID>
  <ISVSVN>0</ISVSVN>
  <StackMaxSize>0x100000</StackMaxSize>
  <HeapMaxSize>0x8000000</HeapMaxSize>
  <ReservedMemMaxSize>0x1000000</ReservedMemMaxSize>
  <ReservedMemExecutable>1</ReservedMemExecutable>
  <TCSNum>10</TCSNum>
  <TCSPolicy>1</TCSPolicy>
  <DisableDebug>1</DisableDebug>
  <MiscSelect>1</MiscSelect>
  <MiscMask>0xFFFFFFFF</MiscMask>
</EnclaveConfiguration>
``` 
Then I used command:
```
make SGX_PRERELEASE=1 SGX_DEBUG=0 SGX_MODE=HW
./iwasm ../../../app-samples/hello-world/test.wasm
``` 
then, I got an error:
```
./iwasm ../../../app-samples/hello-world/test.wasm
Failed to create enclave from enclave.signed.so, error code: 8196
Fail to initialize enclave.
``` 
And when I don't change the Enclave.config.xml, which prevent enclave from running on SGX2 platform. The command will get right output.

**Comment by TianlongLiang** [comment]
Hi, can you provide more details:
1. What modes combination can you build and run without modifying the `sample/Enclave/Enclave.config.xml`? For example, Hw & Prerelease, Simulator & Prerelease?
2. Have you tried running other sgx2 apps? Are they working fine in HW mode and prerelease mode?

**Comment by PeizhongQiu** [comment]
First, the original `sample/Enclave/Enclave.config.xml` is as follows:
```
<!-- Please refer to User's Guide for the explanation of each field -->
<EnclaveConfiguration>
  <ProdID>0</ProdID>
  <ISVSVN>0</ISVSVN>
  <StackMaxSize>0x100000</StackMaxSize>
  <HeapMaxSize>0x8000000</HeapMaxSize>
  <ReservedMemMaxSize>0x1000000</ReservedMemMaxSize>
  <ReservedMemExecutable>1</ReservedMemExecutable>
  <TCSNum>10</TCSNum>
  <TCSPolicy>1</TCSPolicy>
  <DisableDebug>0</DisableDebug>
  <MiscSelect>0</MiscSelect>
  <MiscMask>0xFFFFFFFF</MiscMask>
</EnclaveConfiguration>
``` 
I tried these combination: 
1. I didn't modify the `sample/Enclave/Enclave.config.xml`, and used command `make SGX_PRERELEASE=1 SGX_DEBUG=0 SGX_MODE=HW`. The result is no error.
2. I only modified `DisableDebug` option to 1, and used command `make SGX_PRERELEASE=1 SGX_DEBUG=0 SGX_MODE=HW`. The result is as follows:
```
Failed to create enclave from enclave.signed.so, error code: 8196
Fail to initialize enclave.
``` 
3. I only modified `MiscSelect` option to 1, and used command `make SGX_PRERELEASE=1 SGX_DEBUG=0 SGX_MODE=HW`. The result is as follows:
```
Failed to create enclave from enclave.signed.so, error code: 1
Fail to initialize enclave.
``` 
The sgxsdk I used is the version of 2.19. I run the Cxx11SGXDemo in the linux-sgx. I only modified `MiscSelect` option to 1, and used command `make SGX_PRERELEASE=1 SGX_DEBUG=0 SGX_MODE=HW`. The result is no error.
About step2, I recently read a doc which told me that to run in Pre-Release mode, I only need to run the makefile with the following options: SGX_PRERELEASE=1 SGX_DEBUG=0 SGX_MODE=HW. The DisableDebug flag in the enclave config file must remain 0 when running in Pre-release mode.

**Comment by TianlongLiang** [comment]
Would you mind providing the document you read?

For your step 2:

> I only modified DisableDebug option to 1, and used command make SGX_PRERELEASE=1 SGX_DEBUG=0 SGX_MODE=HW. The result is as follows:

You cannot launch the enclave in non-debug mode (also called production mode) without Intel signing the enclave, you can refer to this post:

https://community.intel.com/t5/Intel-Software-Guard-Extensions/sgx-enclave-without-debug/td-p/1378801

For your step 3:

> I only modified MiscSelect option to 1, and used command make SGX_PRERELEASE=1 SGX_DEBUG=0 SGX_MODE=HW. The result is as follows:

In the [document, SGX version 2.19](https://download.01.org/intel-sgx/sgx-linux/2.19/docs/Intel_SGX_Developer_Reference_Linux_2.19_Open_Source.pdf) page 68:

"MiscSelect bit 0, referred to as MiscSelect[0], and MiscMask bit 0, referred to as MiscMask[0] must be set to appropriate values with the rules described below depending on whether UserRegionSize is set. Other bits in MiscSelect and MiscMask are for future functional extensions."

It seems to me that setting MiscSelect option alone is not enough, you may want to try to add more related options following the document.

**Comment by PeizhongQiu** [comment]
In the document you share, I find :

> If UserRegionSize is configured to a non-zero valid value, that is, the user wants to use the EDMM APIs to manage enclave memory, then:
> 
> - MiscSelect[0] and MiscMask[0] must be set to 1 and the enclave needsto be loaded on SGX 2.0 platform.
> 
> If UserRegionSize is not configured, but the heap, stack and thread related configurations have dynamic part, then:
> 
> - If MiscSelect[0] = 0, the enclave will be loaded as it has no dynamic components.
> 
> - if MiscSelect[0] = 1 and MiscMask[0] = 1, the enclave can only be loaded on SGX 2.0 platform.
> 
> - l if MiscSelect[0] = 1 and MiscMask[0] = 0, the enclave can be loaded on SGX 1.0 and 2.0 platform, and on SGX 2.0 platform, it can utilize the dynamic components.
> 
> If UserRegionSize is not configured and the heap, stack and thread configuration only has static components, then:
> 
> - If MiscSelect[0] = 1, the enclave can only be loaded on SGX 2.0 platform.
> 
> - If MiscSelect[0] = 0, the enclave can be loaded on SGX 1.0 and 2.0 platform.

My step 3 is MiscSelect[0] = 1 and MiscMask[0] = 1, which means the enclave can only be loaded on SGX 2.0 platform. Do you have tried iwasm in SGX2? Can you share the configuration with me?

**Comment by TianlongLiang** [comment]
I have never tried this feature before, the lower version of SGX 2.0(say 2.2.0 or 2.5.0 for example) didn't support this feature, MiscSelect is always set to 0. This feature is added along the way of release and I am not sure start from which version. So unfortunately I don't have a configuration for your problem.

**Comment by PeizhongQiu** [comment]
I feel so bad to hear that.

**Comment by TianlongLiang** [comment]
If I were you, I may try to ask for help at https://community.intel.com/t5/Intel-Software-Guard-Extensions/bd-p/software-guard-extensions or https://github.com/intel/linux-sgx/issues. Those forums should have more SGX experts who have tried this feature and could solve your issue

**Comment by JamesMenetrey** [comment]
Hi there,

> Does iwasm support SGX2?

The short answer is yes. I'm currently developing on such platforms. Without changing the enclave configuration file, the enclave can be launched on SGX2 platforms (with debugging enabled). Nonetheless, you'll get this warning:

> INFO: Enclave configuration 'MiscSelect' and 'MiscSelectMask' will prevent enclave from using dynamic features. To use the dynamic features on SGX2 platform, suggest to set MiscMask[0]=0 and MiscSelect[0]=1.

Assuming you would like to use the dynamic features, you'll need to change the two parameters as mentioned in the message.

Similarly, launching an enclave in prerelease mode requires disabling the debugging mode, as you rightfully pointed out by changing the parameter `DisableDebug` and compiling with `SGX_DEBUG=0` and `SGX_PRERELEASE=1`. Doing so will lead to a new warning:

> INFO: Enclave configuration 'MiscSelect' and 'MiscSelectMask' will prevent enclave from running on SGX1 platform. To make it run on SGX1 platform, suggest to set MiscSelect[0]=0.

Note that launching an enclave with these changes may still lead to the error you face (`SGX_ERROR_NDEBUG_ENCLAVE`) if your SGX SDK is somehow compiled with debugging enabled. You can test it by setting the second argument of the calls to the function `sgx_create_enclave` to zero (here: https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/product-mini/platforms/linux-sgx/enclave-sample/App/App.cpp#L133-L138).

For prosperity, here is the content of my enclave configuration file (for prerelease mode):

```
<!-- Please refer to User's Guide for the explanation of each field -->
<EnclaveConfiguration>
  <ProdID>0</ProdID>
  <ISVSVN>0</ISVSVN>
  <StackMaxSize>0x100000</StackMaxSize>
  <HeapMaxSize>0x8000000</HeapMaxSize>
  <ReservedMemMaxSize>0x1000000</ReservedMemMaxSize>
  <ReservedMemExecutable>1</ReservedMemExecutable>
  <TCSNum>10</TCSNum>
  <TCSPolicy>1</TCSPolicy>
  <DisableDebug>1</DisableDebug>
  <MiscSelect>1</MiscSelect>
  <MiscMask>0</MiscMask>
</EnclaveConfiguration>
```

Hope this helps!
Cheers

**Comment by PeizhongQiu** [comment]
Thank you very much!!! It works.
