### ISSUE TITLE
Use the WAMR_BUILD_PERF_PROFILING under llvm-jit

### ISSUE THREAD

**Issue by hungryzzz** [bytecodealliance/wasm-micro-runtime#2372]
Hi, I build `WAMR` using the configuration.
```cmake .. -DWAMR_BUILD_FAST_JIT=1 -DWAMR_BUILD_JIT=1 -DWAMR_BUILD_MEMORY_PROFILING=1 -DWAMR_BUILD_PERF_PROFILING=1```

But when I try to use it under `--llvm-jit` option, there will an error raised as followed.
```WASM module instantiate failed: set instance running mode failed.```

So how can I get the profiling data under llvm-jit?

Thank you!

**Comment by wenyongh** [comment]
@hungryzzz Thanks for reporting the issue! I submitted PR #2384 to fix it, could you please try again?

**Comment by hungryzzz** [comment]
@wenyongh I've tried it and it works well. Thanks!
