### ISSUE TITLE
Would this compile and run on iOS with JIT disabled?

### ISSUE THREAD

**Issue by warvstar** [bytecodealliance/wasm-micro-runtime#240]
Besides the JIT, is there anything preventing WAMR from supporting iOS as a platform?

**Comment by xwang98** [comment]
@warvstar 
please refer to #242, wamr can be running on iOS in interpreter mode.

Please refer to the guideline to add support for iOS:
https://github.com/bytecodealliance/wasm-micro-runtime/blob/master/doc/port_wamr.md
