### ISSUE TITLE
AOT support for iOS platform

### ISSUE THREAD

**Issue by keith2018** [bytecodealliance/wasm-micro-runtime#242]
hi，I have test WAMR on iOS platform, the result shows :

1. the interpreter mode works fine on both iOS simulator and real device
2. AOT mode works fine on simulator (target="x86_64") but fails on real device (target="aarch64")

My device is iPhone 8, iOS 13.3.1

The test wasm is compiled from simple C code

```c
int test(int n) {
    return n + 42;
}
```

[test.wasm.zip](https://github.com/bytecodealliance/wasm-micro-runtime/files/4543059/test.wasm.zip)

```
imports: 
exports:
  [Function] i32 test(i32)
```

AOT compile command
```
./wamrc --target=aarch64 --size-level=0 --opt-level=0 -o test.aot test.wasm
```

Runtime error at file invokeNative_aarch64.s

> thread #9, name = 'WebThread', stop reason = EXC_BAD_ACCESS (code=2, address=0x111488004)

![20200428104759](https://user-images.githubusercontent.com/23111762/80441688-fd114800-893d-11ea-9f40-b1b14227d1d3.jpg)

it seems that the func_ptr is invalid

please help,  thanks

**Comment by xwang98** [comment]
@keith2018 iOS doesn't support mmap for allocating executable memory, right? Then it is probably not able to support AoT on iOS.

**Comment by florianwinterstein** [comment]
> 1. the interpreter mode works fine on both iOS simulator and real device

Keith, would you be so kind and share what you did to get the interpreter to run on iOS?

**Comment by Feyewon** [comment]
@keith2018 would you be so kind and share what you did to get the interpreter to run on iOS?

**Comment by jjqquu** [comment]
Have you tried entitlement of allow execution of JIT-compiled code for your app?

iOS applications, which is usually sandboxed,  cannot use mmap’s MAP_JIT without entitlement (the usual way to create a RWX region for JIT purposes). 

https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_cs_allow-jit
https://support.apple.com/fr-mg/guide/security/sec15bfe098e/web

**Comment by jjqquu** [comment]
> Have you tried entitlement of allow execution of JIT-compiled code for your app?
> 
> iOS applications, which is usually sandboxed, cannot use mmap’s MAP_JIT without entitlement (the usual way to create a RWX region for JIT purposes).
> 
> https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_cs_allow-jit https://support.apple.com/fr-mg/guide/security/sec15bfe098e/web

Here comes the way Apple suggests to port JIT compiler 
https://developer.apple.com/documentation/apple-silicon/porting-just-in-time-compilers-to-apple-silicon
