### ISSUE TITLE
Question about thread safety

### ISSUE THREAD

**Issue by MBkkt** [bytecodealliance/wasm-micro-runtime#2452]
Is it safe to using smart module inst from different threads in parallel?
Or should I create module inst per thread?

Is it safe to call same func_inst from different threads in parallel?
1. with different environments
2. with same environments

**Comment by lum1n0us** [comment]
Cunnently, it is recommended that every thread should have a unique `module_inst` and `func_inst` and `exec_env` including spawning.

**Comment by MBkkt** [comment]
That sounds sad, but ok :(
Thank you

**Comment by MBkkt** [comment]
Maybe one notice, I'm using aot, don't use interpretation or jit
