### ISSUE TITLE
About AOT memory access boundary check

### ISSUE THREAD

**Issue by linzhiping** [bytecodealliance/wasm-micro-runtime#246]
for release: WAMR-04-15-2020
in [core/iwasm/aot/aot_runtime.c](https://github.com/bytecodealliance/wasm-micro-runtime/blob/a661c49cd0036a7bf416bf84a2c6fbe4a6bb0bca/core/iwasm/aot/aot_runtime.c)
![image](https://user-images.githubusercontent.com/24354447/81278748-ab2c9880-9088-11ea-8486-e2aca37d94cc.png)
should it be:
> app_offset < module_inst->heap_base_offset
> app_offset + (int32)size >= (int32)module_inst->memory_data_size)

![image](https://user-images.githubusercontent.com/24354447/81278382-2d688d00-9088-11ea-94b9-f767c798ba96.png)
should it be:
> module_inst->heap_base_offset <= app_offset

Since memory access for [0 -> size -1] is valid, is it right?

**Comment by wenyongh** [comment]
@linzhiping thanks a lot for finding the issue! It is really an issue, and some other codes have the same problem, we will fix them soon.

**Comment by wenyongh** [comment]
@linzhiping the patch has been merged, [#249](https://github.com/bytecodealliance/wasm-micro-runtime/pull/249). Note for second condtion: app_offset + (int32)size > (int32)module_inst->memory_data_size), equal is allowed: suppose that memory_data_size is 65536, app_offset is 65535 and size is 1, it is OK to read one byte from offset 65535, and here app_offset + size == memory_data_size.
