### ISSUE TITLE
wasmtime-micro-runtime in Rust

### ISSUE THREAD

**Issue by redradist** [bytecodealliance/wasm-micro-runtime#247]
Consider to rewrite wasm-micro-runtime on Rust with name wasmtime-micro-runtime !!
Reason, because Rust provide more safer implementation and at the same time it is still as much powerful as C or C++

I beleave, it is possible to get part of wasmtime implementation and reduce it to fit in wasmtime-micro-runtime requirements ...

I could try to help with writing it ...

**Comment by rahul-thakoor** [comment]
I was looking for  Rust bindings as a start here #230 

Are you able to help with that @redradist?

**Comment by redradist** [comment]
@redradist 
> 
> I was looking for Rust bindings as a start here #230
> 
> Are you able to help with that @redradist?

Yeah, I think I can find some time for Rust Bindings ...

Do you have some work done with it ?

**Comment by redradist** [comment]
> 
> 
> I was looking for Rust bindings as a start here #230
> 
> Are you able to help with that @redradist?

**Comment by rahul-thakoor** [comment]
Not really. I'm too familiar with bindgen tbh
