### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by Forever-chardonnay** [bytecodealliance/wasm-micro-runtime#2508]
May I ask if it supports Android arm6-v8a? I have compiled the code on the Android platform, but currently only armeabi-v7a has been compiled. An error occurred while compiling arm64-v8a, and it cannot be compiled

**Comment by TianlongLiang** [comment]
WAMR does support `arm64-v8a`. If I remember correctly, `arm64-v8a` supports instruction sets `AArch64`

You can try to add a CMake flag to see if it works:

```C
cmake -DWAMR_BUILD_TARGET=AArch64
```

You can refer to [this document](https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/doc/build_wamr.md#configure-platform-and-architecture)

> For AARCH64, the format is `<arch>[<sub-arch>]`, VFP is enabled by default. `<sub-arch>` is optional, e.g. AARCH64, AARCH64V8, AARCH64V8.1 and so on.
