### ISSUE TITLE
run jit enabled iwasm on aarch64 raspberrypi

### ISSUE THREAD

**Issue by y-ykcir** [bytecodealliance/wasm-micro-runtime#2573]
Hi, I want to use JIT-mode iwasm on an aarch64 Raspberry Pi. 

First of all, I would like to ask if aarch64 already supports JIT-mode iwasm？
And Is it possible to cross-compile iwasm on x86 hosts or directly on Raspberry Pi?

I try to  use `CC=aarch64-linux-gnu-gcc cmake .. -DWAMR_BUILD_JIT=1 -DWAMR_BUILD_PLATFORM=linux -DWAMR_BUILD_TARGET=AARCH64` but met error when  I `make`:

```
...
Relocations in generic ELF (EM: 183)
CMakeFiles/iwasm.dir/main.c.o: error adding symbols: File in wrong format
...
```

I would be grateful for any advice on iwasm running jit mode on the aarch64 Raspberry Pi, thanks!

**Comment by liangzhupic** [comment]
same problem here. any solution for it?

**Comment by y-ykcir** [comment]
I successfully compiled jit-mode iwasm directly on aarch64 Raspberry PI, but when I ran it, I got the following error:
```
pi@raspberrypi:~/WasmRL-PPO/wasm-rl-ppo/benchmark $ /home/pi/arm-wasm/iwasm --llvm-jit poly.wasm
Invalid thread stack size 65536. Min stack size on Linux = 131072
WASM module load failed: create orcjit compile thread failed

pi@raspberrypi:~/WasmRL-PPO/wasm-rl-ppo/benchmark $ /home/pi/arm-wasm/iwasm_jit --llvm-jit --stack-size=131072 poly.wasm
Invalid thread stack size 65536. Min stack size on Linux = 131072
WASM module load failed: create orcjit compile thread failed
```
@wenyongh Could you please take a look? Thanks a lot.

**Comment by wenyongh** [comment]
@y-ykcir Could you add `add_definitions(-DAPP_THREAD_STACK_SIZE_DEFAULT=131072)` in the CMakeLists.txt?

**Comment by y-ykcir** [comment]
> @y-ykcir Could you add `add_definitions(-DAPP_THREAD_STACK_SIZE_DEFAULT=131072)` and `add_definitions(-DAPP_THREAD_STACK_SIZE_MIN=131072)` in the CMakeLists.txt?

It worked. Thanks a lot. 😀
