### ISSUE TITLE
Update memory_tune.md to provide guidelines for wasi-thread

### ISSUE THREAD

**Issue by lulingar** [bytecodealliance/wasm-micro-runtime#2597]
The [recommendations](https://github.com/bytecodealliance/wasm-micro-runtime/blame/ade73f6142a1a11202053219b840580eeb24750e/doc/memory_tune.md#L16) about when to `-Wl,export`ing `malloc` and `free` and when not to, need to be extended now that wasi-thread has been introduced, with a [different memory model](https://bytecodealliance.github.io/wamr.dev/blog/introduction-to-wamr-wasi-threads/#memory-model) than the one used by WAMR thread.

Also, a question to clarify on the existing document:

> It is recommended to export the malloc/free functions and disable app heap in single thread mode, and for multi-threading, as the libc heap isn't thread-safe

Is it still true that the libc heap isn't thread-safe, and if so, in what way?

**Comment by yamt** [comment]
> Also, a question to clarify on the existing document:
> 
> > It is recommended to export the malloc/free functions and disable app heap in single thread mode, and for multi-threading, as the libc heap isn't thread-safe
> 
> Is it still true that the libc heap isn't thread-safe, and if so, in what way?

the libc heap is thread-safe as far as it's built with a proper options.
if you are using wasi-threads with the wasm32-wasi-threads sysroot provided by wasi-sdk, you don't need to worry.
