### ISSUE TITLE
WAMRC terminator bug

### ISSUE THREAD

**Issue by arjunr2** [bytecodealliance/wasm-micro-runtime#2620]
`wamrc` has a bug in the LLVM compilation flow when a compare instruction precedes a parametrized block. I have attached a sample WASM file below that demonstrates this, where the sign extension instruction is inserted after the terminator.

The compiler is built with default flags: `cmake -B build; make -C build`

[bug.tar.gz](https://github.com/bytecodealliance/wasm-micro-runtime/files/12835365/bug.tar.gz)

**Comment by TianlongLiang** [comment]
Hi, https://github.com/bytecodealliance/wasm-micro-runtime/pull/2622 should fix this issue. Thanks for spotting this issue 😄

**Comment by wenyongh** [comment]
Close this issue since it was fixed.
