### ISSUE TITLE
Different behavior when running llvm-jit and fast-jit

### ISSUE THREAD

**Issue by unicornt** [bytecodealliance/wasm-micro-runtime#2641]
Hi, I build `wamr 1.2.3` on ubuntu 20.04 and found a different behavior when running the same code with `llvm-jit` mode and `fast-jit` mode.
`fast-jit` mode will exit normally while `llvm-jit` mode throw a exception `Exception: integer divide by zero`

I also use other runtimes to run the same code, and it looks like a wrong behavior of `llvm-jit` mode

By the way, I try to replace all `div` in wasm code with `add`. But it turns out to be **useless**.

[code.zip](https://github.com/bytecodealliance/wasm-micro-runtime/files/12908730/code.zip)

<img width="1232" alt="image" src="https://github.com/bytecodealliance/wasm-micro-runtime/assets/18662046/04c85190-147a-4883-b0be-2676055381e4">

**Comment by TianlongLiang** [comment]
Hi, I tested it on the latest main branch, it seems that this issue no longer exists on the latest commit

**Comment by unicornt** [comment]
Thank you! Maybe you can tell me why it happened?

**Comment by TianlongLiang** [comment]
https://github.com/bytecodealliance/wasm-micro-runtime/pull/2627 This PR fixes the problem, it has something to do with the LLVM const( in some scenarios the constant might not be directly available to the LLVM IR builder)
