### ISSUE TITLE
Wrong output of i32.rotl in llvm-jit mode 

### ISSUE THREAD

**Issue by unicornt** [bytecodealliance/wasm-micro-runtime#2667]
### Test Case

[case.zip](https://github.com/bytecodealliance/wasm-micro-runtime/files/13114528/report14.zip)

### Result

The second output in `llvm-jit` mode is  `1536` while the right answer is `-2`.
<img width="1261" alt="image" src="https://github.com/bytecodealliance/wasm-micro-runtime/assets/18662046/b4b029ac-48c1-451c-ad42-f7bcd35b5be1">

### Extra Information

This is a case I extract from other file. The key part is `line 54-71` of `case.wat` file.
![image](https://github.com/bytecodealliance/wasm-micro-runtime/assets/18662046/48f05fd4-9611-48ed-8c0a-37d6af36af51)

`function print` is a print function which needs a i32 for parameter and return the same i32 as result.
`function print` will print the given i32 variable to the stdout.

The different output between `llvm-jit` mode and `fast-jit` mode means the result of `i32.rotl` is wrong in `llvm-jit` mode.

By the way, if I uncomment `line 62` in `case.wat` file, the output will be the same. So I guess maybe it is also a wrong optimization in `llvm-jit` mode.

### Versions and Environment

wamr version : 1.2.3

Operating system: Ubuntu 20.04

Architecture: x86_64

**Comment by wenyongh** [comment]
Hi, thanks for reporting the issue! Please try #2697.

**Comment by unicornt** [comment]
> Hi, thanks for reporting the issue! Please try #2697.

Yes, it really works. Could you please tell me how did you fix it? Is it about `mask` when calculating `Calculate (bits - shift_count) & mask`?

**Comment by wenyongh** [comment]
Yes, the formula should be like the implementation of interpreter:
https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/core/iwasm/interpreter/wasm_interp_classic.c#L122

But here it didn't `and` the `mask` for `(bits - shift_count)`, so the actual shift bits for `>>` may be invalid, e.g. 32 but not 0.

**Comment by unicornt** [comment]
Thank you for the explanation!
