### ISSUE TITLE
JitBitmap seems unused

### ISSUE THREAD

**Issue by yamt** [bytecodealliance/wasm-micro-runtime#2754]

**Comment by yamt** [comment]
@wenyongh is there any plan to use it in fast-jit?
otherwise, i want to move it to core/shared/utils as i want to use it (or something similar) for https://github.com/bytecodealliance/wasm-micro-runtime/issues/2735 to track which segments have been dropped.
cf. https://github.com/yamt/toywasm/blob/fca52a0174eb1644fea9caa3fe1faad598864f6a/lib/type.h#L488-L494

**Comment by wenyongh** [comment]
@yamt no plan to use it fast-jit, please move to core/shared/utils if you want.
