### ISSUE TITLE
Ignorance of "out of bounds memory access" exception

### ISSUE THREAD

**Issue by unicornt** [bytecodealliance/wasm-micro-runtime#2755]
Hi, I found that `llvm-jit` and `wamrc` may ignore "out of bounds memory access" exception.
### Test Case

[case.zip](https://github.com/bytecodealliance/wasm-micro-runtime/files/13331716/report27.zip)

The `_start` function of `case.wasm` is like this.

```wasm
(func (;2;) (type 5)
(local i32)
  loop  ;; label = @1
    i32.const 100
    i32.load8_u offset=1627730432
    i32.const 41
    i32.ne
    local.get 0
    i32.const 65535
    i32.eq
    i32.and
    br_if 0 (;@1;)
  end)
```

### Result 
<img width="1310" alt="image" src="https://github.com/bytecodealliance/wasm-micro-runtime/assets/18662046/4eb6822f-a6b9-4f60-95b1-ef2427338cbe">

### Extra Info
I found that the `i32.eq` instruction before `br_if 0` can't be reduced.

### Versions and Environment

wamr version : 1.2.3

Operating system: Ubuntu 20.04

Architecture: x86_64

**Comment by lum1n0us** [comment]
although `--bound-checks=1` are helpful, there are still concerns.

https://github.com/bytecodealliance/wasm-micro-runtime/issues/2773 explains the root cause and options, please let us know your opinion.
