### ISSUE TITLE
linux-sgx and WASI support

### ISSUE THREAD

**Issue by JamesMenetrey** [bytecodealliance/wasm-micro-runtime#277]
Hey folks !

I'm playing around with the example for `linux-sgx` and it works flawlessly. After inspecting the imported functions of the wasm, I realized it was built by relying on `libc-builtin` provided by WAMR.

As I aim to use WASI in my project, I edited the `CMakeLists.txt` file and enabled the flag `WAMR_BUILD_LIBC_WASI`, in order to support imported WASI functions. Nevertheless, when I build the project using `make`, I receive various errors regarding unknown types and function related to threading. The full error output can be found in the attached file to this issue.

Do you have any idea why I get those errors ?

Thanks !
Cheers

[compilation-errors.log](https://github.com/bytecodealliance/wasm-micro-runtime/files/4759205/compilation-errors.log)

**Comment by xwang98** [comment]
@ZenLulz The WASI support for SGX is a work in progress. Any progress will be updated here.

**Comment by ZenLulz** [comment]
Hello @xwang98, thanks for your answer. I might be interested in contributing to enhance the support of WASI for SGX. Could you please give me more details about the work in progress (what is done, what needs to be done) ?

Many thanks !

**Comment by xwang98** [comment]
@ZenLulz we are evaluating using Occlum or Graphene to support WASI on SGX:
https://github.com/occlum/occlum
https://github.com/oscarlab/graphene

A better way would be adding native SGX based on SGX SDK, but we don't bandwidth to work on shortly. We heard that pthread for SGX is already supported by SGX SDK 2.9. Some other posix APIs like open() still need ecall/ocall implementation.

It would be excellent for you contributing to SGX WASI support! Please kindly share any your thoughts or plans.

**Comment by leyao-daily** [comment]
@ZenLulz 
I want to use SGX in my own .wasm app. Do you know how to utilize linux-sgx into my app? I found there just is a simple demo. But no guide to run our own app in linux-sgx

**Comment by ZenLulz** [comment]
Hello @xwang98 !

I'm currently evaluating and working on the integration of native SGX support based on SGX SDK. At the moment, separated created a similar structure of the existing `libc-builtin` called `libc-wasi` with stubs functions inside, expect some to provide basic output and time information for the running WASM within the enclaves. It works fine and I'm looking forward to provide a pull request once the code base will be stabilized. The architecture offered by WAMR is great and genuinely provide all the tools required to provide that native integration approach. This is why I have chosen it over reusing known tools such as graphene.

@leyao-daily: I suggest you start playing with the samples in the `product-mini` without and with SGX support and read the guidelines available in the docs/ folder. They are very helpful and provide all the information you need to get started.

**Comment by Kevin0626** [comment]
@ZenLulz it is great! Could you share the link of your working repo if it is public? We have done some development on supporting WASI for SGX and should be able to release shortly. Let's see if we have any overlap here.

**Comment by ZenLulz** [comment]
Hello @Kevin0626, unfortunately, the repo is not public yet. Do you have any ETA for releasing WASI support ?

**Comment by mdamgaard-biolib** [comment]
What is the status of the WASI for SGX implementation?

Is there a PR coming or some code that i can take a look at?

**Comment by wenyongh** [comment]
@mdamgaard-biolib SGX WASI support has been enabled with patch #343 , after building, the iwasm binary generated under product-mini/platforms/linux-sgx/enclave-sample/ can run wasm wasi app. For more details, please ref to [build and port WAMR vmcore for Linux SGX](https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/doc/linux_sgx.md).
