### ISSUE TITLE
Rust and opening files

### ISSUE THREAD

**Issue by AlexEne** [bytecodealliance/wasm-micro-runtime#278]
Hello,

I may just miss-understand how this is supposed to be used, but I cannot find a way to get a simple rust program to open a file in wasm32-wasi:

In the host VM:
```cpp
const char* dirs[] = {".", "./"};

// This method isn't super documented (what is env?), but I hope this is the correct way to set the dirs.
wasm_runtime_set_wasi_args(module_handle, dirs, 2, nullptr, 0, nullptr, 0, nullptr, 0);

instance = wasm_runtime_instantiate(module_handle, stack_size, heap_size, ...);

// Then i run the main() function with no args.
```

The rust program:
```rs
#[no_mangle]
extern "C" fn main() {
    println!("Hello world!");
    let f = File::open("myfile.txt").unwrap();
}
```

The error I get:
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "failed to find a preopened file descriptor through which \"myfile.txt\" could be opened" }', src/lib.rs:9:13
```

This is generated by [this file](https://github.com/rust-lang/rust/blob/master/src/libstd/sys/wasi/fs.rs#L629) from rust's libstd.
```rs
        let fd = __wasilibc_find_relpath(p.as_ptr(), &mut ret);
        if fd == -1 {
            let msg = format!(
                "failed to find a preopened file descriptor \
                 through which {:?} could be opened",
                p
            );
            return Err(io::Error::new(io::ErrorKind::Other, msg));
        }
```
I did check that:
1) any other rust programs work just fine (e.g. "Hello world!" is printed).
2) the file is there.
3) I build with wasi support: `set (WAMR_BUILD_LIBC_WASI 1)`
4) I also had to change the env name to `wasi_snapshot_preview1` from it's previous value, as otherwise no functions would be found.

Is there is probably something super silly that I'm missing, but I am running out of ideas, and I am now going deeper and deeper into the depths on the rust std lib and wasi trying to find out how they connect to the WAS implementation from WAMR, and I am sure that there's a simple explanation for why it doesn't work.

**Comment by Weining2019** [comment]
We tracked the calling of all wasm native API in the interpreter and found that only '`fd_write`' was called to print 'Hello world'. And '`fd_write`' returned successfully without exception. But '`path_open`' was not called. So there should be some issues in the wasm app or compiler.

This is the patch to track wasm native API calling:

```
diff --git a/core/iwasm/interpreter/wasm_interp_fast.c b/core/iwasm/interpreter/wasm_interp_fast.c
index 02d0ee57..2a1d0b6d 100644
--- a/core/iwasm/interpreter/wasm_interp_fast.c
+++ b/core/iwasm/interpreter/wasm_interp_fast.c
@@ -809,6 +809,9 @@ wasm_interp_call_func_native(WASMModuleInstance *module_inst,
                                              frame->lp, cur_func->param_cell_num, argv_ret);
     }
 
+    printf("call (%s, %s), native func return: %d, invoke_native return: %d\n",
+           func_import->module_name, func_import->field_name, argv_ret[0], ret);
+
     if (!ret)
         return;

```

**Comment by AlexEne** [comment]
So the expected behaviour is for the app to call path_open in this scenario, I will open an issue on the standard lib as this doesn't happen. Thanks
