### ISSUE TITLE
Unexpected behavior caused by "memory.init"

### ISSUE THREAD

**Issue by erxiaozhou** [bytecodealliance/wasm-micro-runtime#2797]
## Test case
[v19_tcs_memory.init_647.zip](https://github.com/bytecodealliance/wasm-micro-runtime/files/13406029/v19_tcs_memory.init_647.zip)

## Build commands
I compile the code with commit id  0b8a90419309a5db65c65127d7a86aedf36240f1.
Platform: Ubuntu 20.04
CPU: amd64 

## compile:
```shell
export CC=/usr/lib/llvm-16/bin/clang
export CXX=/usr/lib/llvm-16/bin/clang++
install_dir="./install_fast_interpreter"
mkdir -p "$install_dir"
cd "$script_dir/product-mini/platforms/linux/";rm -rf build
cmake  -DWAMR_BUILD_INTERP=1 -DWAMR_BUILD_REF_TYPES=1 -DWASM_ENABLE_SIMD=1 -DWASM_ENABLE_BULK_MEMORY=1 -DCMAKE_INSTALL_PREFIX="$install_dir" -DWAMR_BUILD_AOT=0 -DCMAKE_BUILD_TYPE=Release -DWAMR_BUILD_FAST_INTERP=1 -DWAMR_BUILD_LIBC_WASI=0 -DWAMR_BUILD_LIBC_BUILTIN=1 -Bbuild
cd build
make -j40
```
## execute:
```shell
iwasm --heap-size=0 -f to_test <tc_name>
```

## Expected behavior:
An exception indicating "out of bounds memory access"
## Actual behavior:
No Exception

**Comment by TianlongLiang** [comment]
Hi, thanks for letting us know about this issue, https://github.com/bytecodealliance/wasm-micro-runtime/pull/2798 should fix it
