### ISSUE TITLE
Is there any way to support XIP(execute in place)?

### ISSUE THREAD

**Issue by kk8916** [bytecodealliance/wasm-micro-runtime#285]
Currently, the mode of aot code's relocation is LLVMRelocStatic mode. 

```c
/* Create the target machine */
        if (!(comp_ctx->target_machine =
                    LLVMCreateTargetMachine(target, triple_norm, cpu, features,
                                            opt_level, LLVMRelocStatic,
                                            code_model))) {
            aot_set_last_error("create LLVM target machine failed.");
            goto fail;
        }
```

Because this mode will modify the code when loading, it cannot support XIP. If I want to support XIP, is there any good way? If I want to generate PIC code by LLVMRelocPIC mode, I think I should change some code to support that. Is there any suggestion about that?

**Comment by wenyongh** [comment]
@kk8916 using LLVMRelocPIC mode generates position independent code, but normally it creates GOT related sections and requires the loader to apply address relocation in GOT table, which isn't supported by WAMR currently.

A possible way is to develop a tool to apply relocation to the AOT file previously, meaning that changing the relocation addresses in the machine code of AOT file to the pre-known addresses according to relocation info in AOT file, save the AOT file, and then flash it to ROM.  You might also need to create the plt table, and append it to end of code section of AOT file. And then try to disable or rewrite the executable memory allocation and address relocation in AOT loader. You can have a try, but it might be complex. Thanks.
