### ISSUE TITLE
Question - Security Vulnerability Report

### ISSUE THREAD

**Issue by RootUp** [bytecodealliance/wasm-micro-runtime#2863]
I reported a vulnerability through Github (Security) feature ([GHSA-jp93-gvr4-6j3x](https://github.com/bytecodealliance/wasm-micro-runtime/security/advisories/GHSA-jp93-gvr4-6j3x)) just wondering anyone from team received/reviewed it. Thanks!

**Comment by xujuntwt95329** [comment]
Hi @RootUp thanks for reporting this, we have fixed it in https://github.com/bytecodealliance/wasm-micro-runtime/pull/2866, could you please try again?

**Comment by RootUp** [comment]
Thanks, I confirm its fixed with (#2866)
