### ISSUE TITLE
Windows wamr build error

### ISSUE THREAD

**Issue by louisvangeldrop** [bytecodealliance/wasm-micro-runtime#2870]
The following error occurs when building Wamr for Windows:
CMake Error at CMakeLists.txt:573 (message):
  perf support is available on Linux only.

When I change line 71 of file ...build-scripts\build_llvm.py into 
-DLLVM_USE_PERF:BOOL=OFF", 

it will circumvent the error

**Comment by wenyongh** [comment]
@louisvangeldrop I tried to fix it in PR #2868.

**Comment by louisvangeldrop** [comment]
THX for the fix. It works now
