### ISSUE TITLE
samples/basic/wasm-apps/testapp.c: intToStr was called with wrong length parameter

### ISSUE THREAD

**Issue by hzjun** [bytecodealliance/wasm-micro-runtime#2874]
intToStr((int)fpart, res + i + 1, sizeof(res + i + 1), afterpoint);
should be
intToStr((int)fpart, res + i + 1, res_size - i - 1, afterpoint);

**Comment by wenyongh** [comment]
@hzjun thanks a lot, I fixed it with #2876.
