### ISSUE TITLE
Fail to delete sub directory ?

### ISSUE THREAD

**Issue by Userzxcvbvnm** [bytecodealliance/wasm-micro-runtime#2884]
## Summary
The test program is to delete a subdirectory `Data/tmpdir` in directory `Data`.
However, WAMR fails.

## Steps to reproduce
The c file is uploaded as 
[test-c.txt](https://github.com/bytecodealliance/wasm-micro-runtime/files/13610312/test-c.txt)

The wasm file is uploaded as 
[test-wasm.txt](https://github.com/bytecodealliance/wasm-micro-runtime/files/13610313/test-wasm.txt)

using command `iwasm --dir=./Data test.wasm`

## Expected result
Successfullly get the file fd.
File deleted successfully.

And the sub directory `tmpdir` is deleted.

And this is what wasmer does.

## Actual result
Failed to open the file.
: Is a directory

**Comment by yagehu** [comment]
This is not a bug with WAMR, you just need to change your `O_RDWR` to `O_RDONLY`. This behavior is the same on native Linux and other runtimes.  You can see this is also true in wasi-libc's [`opendir()`](https://github.com/WebAssembly/wasi-libc/blob/a796d874f8c47641c410746a3d4bd6a85d2baac2/libc-top-half/musl/src/dirent/opendir.c#L8).
