### ISSUE TITLE
Segmentation fault on module instance attempting an invalid `free(3)`

### ISSUE THREAD

**Issue by midokura-xavi92** [bytecodealliance/wasm-micro-runtime#2909]
## Host configuration

```
$ uname -a
Linux xavier-midokura 5.14.0-1059-oem #67-Ubuntu SMP Mon Mar 13 14:22:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

$ /opt/wasi-sdk-20.0/bin/clang --version
clang version 16.0.0
Target: wasm32-unknown-wasi
Thread model: posix
InstalledDir: /opt/wasi-sdk-20.0/bin
```

### Commit

[`b5022015fce7dcc97f4ad00997b09448769a7f89`](https://github.com/bytecodealliance/wasm-micro-runtime/tree/b5022015fce7dcc97f4ad00997b09448769a7f89)

## Description

The example attached below shows how an invalid call to `free(3)` raises a segmentation fault on the host runtime:

```c
#include <stdlib.h>
#include <stdint.h>

int main()
{
    free((void *)(intptr_t)(void *)1);
    return EXIT_SUCCESS;
}
```

The project was configured and built with `wasm-micro-runtime`'s default options:

```
$ cmake -B build
$ cmake --build build/ -j$(nproc --all)
```

```
$ gdb --args ./build/test build/badfree.wasm
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./build/test...
(No debugging symbols found in ./build/test)
(gdb) start
Temporary breakpoint 1 at 0x9e08
Starting program: /home/xavier/badfree/build/test build/badfree.wasm
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
c
Temporary breakpoint 1, 0x000055555555de08 in main ()
(gdb) c
Continuing.

Program received signal SIGSEGV, Segmentation fault.
0x00005555555876b5 in wasm_interp_call_func_bytecode ()
```

## Notes

- The segmentation fault goes away if the invalid call to `free(3)` is removed.
- The segmentation fault goes away if `wasm-micro-runtime` is configured with `-DWAMR_BUILD_FAST_INTERP=0`.
- Whereas only a minimal reproducible example is attached on this ticket, we suspect similar issues are causing our proprietary application, which makes use of AOT modules and XIP, to also raise a segmentation fault and crash.

## Tarball

[`badfree.tar.gz`](https://github.com/bytecodealliance/wasm-micro-runtime/files/13683734/badfree.tar.gz)

**Comment by yamt** [comment]
> $ gdb --args ./build/test build/badfree.wasm

can you share this badfree.wasm binary?

**Comment by yamt** [comment]
> > can you share this badfree.wasm binary?
> 
> The build system already builds `badfree.wasm` from `badfree.c`, but I will provide it here anyway. GitHub does not allow uploading `.wasm` files, so I had to create a tarball for it:
> 
> [`badfree-wasm.tar.gz`](https://github.com/bytecodealliance/wasm-micro-runtime/files/13684555/badfree-wasm.tar.gz)

ah, i haven't noticed your tarball contains the embedder and build framework.

does it crash if you run it w/o gdb?
it's normal for wamr to trap SEGV.

**Comment by yamt** [comment]
> > does it crash if you run it w/o gdb?
> 
> No, it keeps running. It does crash on our proprietary application, but we still need to investigate more whether `wasm-micro-runtime` is responsible for this.
> 
> > it's normal for wamr to trap SEGV.
> 
> Could you please provide a rationale? As I explained above, removing the invalid call to `free(3)` fixes the `SEGV`. I also tested with:

wamr traps SEGV to detect out-of-range access to linear memory and translate it to a wasm-level trap.

you can disable the optimization with WAMR_DISABLE_HW_BOUND_CHECK=1 if you want.

or, maybe you might want to change the debugger behavior. on lldb, you can use `process handle` to configure how to handle signals. i guess gdb has an equivalent.

> 
> ```c
> #include <stdlib.h>
> #include <stdint.h>
> 
> int main()
> {
>     int *a = malloc(1);
>     free(a);
>     return 0;
> }
> ```
> 
> And:
> 
> ```c
> #include <stdlib.h>
> #include <stdint.h>
> 
> int main()
> {
>     free(NULL);
>     return 0;
> }
> ```
> 
> None of these raised a `SEGV`.

because they don't perform out-of-range accesses in the first place?
