### ISSUE TITLE
Copy memory content of runtime to application's memory space

### ISSUE THREAD

**Issue by oubotong** [bytecodealliance/wasm-micro-runtime#291]
Let me give an example of my code:
**wasm applicaiton**:
```
int *p=malloc(sizeof(int));
```
**runtime**:
```
int tmp=100;
int *tmpp=&tmp;
```
Can I use either **memcpy** or **bh_memcpy_s** to copy the content from **tmpp** to **p**?
If not, what is the proper way to do it. 
Thanks in advance!

**Comment by xwang98** [comment]
https://github.com/bytecodealliance/wasm-micro-runtime/blob/master/doc/embed_wamr.md#pass-buffer-to-wasm-function

@oubotong could you please check if the above link is useful for your issue?

**Comment by oubotong** [comment]
This seems what I need, let me try it out.
