### ISSUE TITLE
Different behavior between fast-jit and llvm-jit

### ISSUE THREAD

**Issue by unicornt** [bytecodealliance/wasm-micro-runtime#2931]
Hi, I found a case that can cause different behavior between `fast-jit` mode and `llvm-jit` mode.

## Test Case
[case.zip](https://github.com/bytecodealliance/wasm-micro-runtime/files/13769653/case.zip)

## Result
Run `iwasm --fast-jit case.wasm` and `echo $?` to see the return code.
<img width="1277" alt="image" src="https://github.com/bytecodealliance/wasm-micro-runtime/assets/18662046/75335ebb-6046-4c66-9c1a-531e862a8387">

## Extra info
I believe the different return code is caused by `call 0` function at the end of `function 5`. `function 0` is `proc_exit` function.

## Versions and Environment
wamr version : 1.2.3
Operating system: Ubuntu 20.04
Architecture: x86_64

**Comment by TianlongLiang** [comment]
Hi, https://github.com/bytecodealliance/wasm-micro-runtime/pull/2969 should fix this issue, thanks for reporting the issue! 

![image](https://github.com/bytecodealliance/wasm-micro-runtime/assets/111852609/efa58c44-c98f-4192-bd04-975fc2dd67c3)

**Comment by wenyongh** [comment]
Close this issue as it was fixed.
