### ISSUE TITLE
release 1.3.1 ?

### ISSUE THREAD

**Issue by yamt** [bytecodealliance/wasm-micro-runtime#2935]
it seems some users are annoyed much by the bug fixed by https://github.com/bytecodealliance/wasm-micro-runtime/pull/2882.
it might make sense to make a patch release for the fix.
how do you think?

**Comment by wenyongh** [comment]
Yes, agree to release 1.3.1, but just wondering whether we should wait until some other issues are fixed? And we are also planning to merge `dev/gc_refactor` to main, which is a huge change including the AOT ABI (AOT file format and others), after that we can resolve some other AOT ABI issues, do you have any concern? My suggestion is to release 1.3.1 recently, then continue to fix some other issues and release 1.3.2, and the merge `dev/gc_refactor` to main, and then we can release 2.0.0 in the future.

**Comment by yamt** [comment]
> My suggestion is to release 1.3.1 recently, then continue to fix some other issues and release 1.3.2, and the merge `dev/gc_refactor` to main, and then we can release 2.0.0 in the future.

it makes sense.

**Comment by wenyongh** [comment]
@yamt is there any patch to merge to main branch from you? I will do some test and create release 1.3.1 if things go well.

**Comment by yamt** [comment]
> @yamt is there any patch to merge to main branch from you? I will do some test and create release 1.3.1 if things go well.

i don't have anything urgent to block 1.3.1.

**Comment by wenyongh** [comment]
@yamt the release 1.3.1 was created: https://github.com/bytecodealliance/wasm-micro-runtime/releases/tag/WAMR-1.3.1.

**Comment by yamt** [comment]
> @yamt the release 1.3.1 was created: https://github.com/bytecodealliance/wasm-micro-runtime/releases/tag/WAMR-1.3.1.

thank you.
