### ISSUE TITLE
unhandled SIGSEGV in fast interpreter mode

### ISSUE THREAD

**Issue by erxiaozhou** [bytecodealliance/wasm-micro-runtime#2946]
# Build commands
I compile the code with commit id 92bf8547aa64dddad2ecd387a352f89bbc475c88
Platform: Ubuntu 20.04
CPU: amd64 
compile:

```
export CC=/usr/lib/llvm-16/bin/clang
export CXX=/usr/lib/llvm-16/bin/clang++
cd product-mini/platforms/linux/;rm -rf build
cmake  -DWAMR_BUILD_INTERP=1 -DWAMR_BUILD_REF_TYPES=1 -DWAMR_BUILD_SIMD=1 -DWASM_ENABLE_BULK_MEMORY=1 -DWAMR_BUILD_AOT=0 -DCMAKE_BUILD_TYPE=Release -DWAMR_BUILD_FAST_INTERP=1 -DWAMR_BUILD_LIBC_WASI=0 -DWAMR_BUILD_LIBC_BUILTIN=1 -Bbuild
```

execute:
```shell
iwasm --heap-size=0 -f to_test  <tc_name>
```
# Cases

[iwasm_fast_interp_div_zero_unhandled.zip](https://github.com/bytecodealliance/wasm-micro-runtime/files/13800883/iwasm_fast_interp_div_zero_unhandled.zip)

# Actual behavior:

```
unhandled SIGSEGV, si_addr: (nil)
```

# Expected behavior:
An exception indicates that "integer divide by zero"

**Comment by wenyongh** [comment]
Close this issue as it was fixed.
