### ISSUE TITLE
Unexpect excrption (integer overflow) on fast interpreter mode

### ISSUE THREAD

**Issue by erxiaozhou** [bytecodealliance/wasm-micro-runtime#2951]
# Build commands
I compile the code with commit id 92bf8547aa64dddad2ecd387a352f89bbc475c88.
Platform: Ubuntu 20.04
CPU: amd64 
compile:

```
export CC=/usr/lib/llvm-16/bin/clang
export CXX=/usr/lib/llvm-16/bin/clang++
cd product-mini/platforms/linux/;rm -rf build
cmake  -DWAMR_BUILD_INTERP=1 -DWAMR_BUILD_REF_TYPES=1 -DWAMR_BUILD_SIMD=1 -DWASM_ENABLE_BULK_MEMORY=1 -DWAMR_BUILD_AOT=0 -DCMAKE_BUILD_TYPE=Release -DWAMR_BUILD_FAST_INTERP=1 -DWAMR_BUILD_LIBC_WASI=0 -DWAMR_BUILD_LIBC_BUILTIN=1 -Bbuild
```

execute:

```
iwasm --heap-size=0  <tc_name>
```
# Cases

[iwasm_fast_jit_unexpected_int_overflow.zip](https://github.com/bytecodealliance/wasm-micro-runtime/files/13801277/iwasm_fast_jit_unexpected_int_overflow.zip)

# Actual behavior:

```
Exception: integer overflow
```

# Expected behavior:
No exception

**Comment by wenyongh** [comment]
Fast JIT works normal, it should be the issue of fast-interp according to the build command and test result.

**Comment by erxiaozhou** [comment]
> Fast JIT works normal, it should be the issue of fast-interp according to the build command and test result.

Yes, you are right.

**Comment by xujuntwt95329** [comment]
Thanks for reporting this, we've fixed in https://github.com/bytecodealliance/wasm-micro-runtime/pull/2974

**Comment by wenyongh** [comment]
Close this issue since it was fixed.
