### ISSUE TITLE
Unexpect exception (allocate memory failed) on fast interpreter mode

### ISSUE THREAD

**Issue by erxiaozhou** [bytecodealliance/wasm-micro-runtime#2953]
# Build commands
I compile the code with commit id 92bf8547aa64dddad2ecd387a352f89bbc475c88.
Platform: Ubuntu 20.04
CPU: amd64 
compile:

```
export CC=/usr/lib/llvm-16/bin/clang
export CXX=/usr/lib/llvm-16/bin/clang++
cd product-mini/platforms/linux/;rm -rf build
cmake  -DWAMR_BUILD_INTERP=1 -DWAMR_BUILD_REF_TYPES=1 -DWAMR_BUILD_SIMD=1 -DWASM_ENABLE_BULK_MEMORY=1 -DWAMR_BUILD_AOT=0 -DCMAKE_BUILD_TYPE=Release -DWAMR_BUILD_FAST_INTERP=1 -DWAMR_BUILD_LIBC_WASI=0 -DWAMR_BUILD_LIBC_BUILTIN=1 -Bbuild
```

execute:

```
iwasm --heap-size=0  <tc_name>
```
# Cases

[iwasm_fast_interp_unexpected_exception2.zip](https://github.com/bytecodealliance/wasm-micro-runtime/files/13801304/iwasm_fast_interp_unexpected_exception2.zip)

# Actual behavior:

```
Exception: allocate memory failed
```

# Expected behavior:
No exception
```
0x16006d52ce3ebd1a:i64
```

**Comment by xujuntwt95329** [comment]
Thanks for reporting this, we've fixed in https://github.com/bytecodealliance/wasm-micro-runtime/pull/2974

**Comment by wenyongh** [comment]
Close this issue since it was fixed.
