### ISSUE TITLE
Why does appmanager need to remove some sections after loading and init aot/bytecode module?

### ISSUE THREAD

**Issue by dpinthinker** [bytecodealliance/wasm-micro-runtime#298]
AOT sections removing:

https://github.com/bytecodealliance/wasm-micro-runtime/blob/1f6b589c12083df1f9337cc26d41e14f6224839a/core/app-mgr/app-manager/module_wasm_app.c#L627-L635

https://github.com/bytecodealliance/wasm-micro-runtime/blob/1f6b589c12083df1f9337cc26d41e14f6224839a/core/app-mgr/app-manager/module_wasm_app.c#L651-L654

Bytecode sections removing:

https://github.com/bytecodealliance/wasm-micro-runtime/blob/1f6b589c12083df1f9337cc26d41e14f6224839a/core/app-mgr/app-manager/module_wasm_app.c#L690-L704

https://github.com/bytecodealliance/wasm-micro-runtime/blob/1f6b589c12083df1f9337cc26d41e14f6224839a/core/app-mgr/app-manager/module_wasm_app.c#L721-L724

https://github.com/bytecodealliance/wasm-micro-runtime/blob/1f6b589c12083df1f9337cc26d41e14f6224839a/core/app-mgr/app-manager/module_wasm_app.c#L753-L756

While those sections are not be removed in the mini project.

**Comment by xwang98** [comment]
@dpinthinker The intention here is to reduce the memory consumption.

**Comment by dpinthinker** [comment]
Will this cause the lack of some WASM features?

**Comment by xwang98** [comment]
No. After the wasm module is loaded, some sections have been coverted to internal data structures. there is no need to keep the orginal sections.

**Comment by dpinthinker** [comment]
It seems great!
