### ISSUE TITLE
Question about implement os_mmap() to support a new platform

### ISSUE THREAD

**Issue by takoyakiyo** [bytecodealliance/wasm-micro-runtime#300]
I want to use wasm-micro-runtime in a new OS on an embedded device, so I tried to implement the APIs defined in `platform_api_vmcore.h`, but I noticed that `os_mmap()` returned `BH_MALLOC()` which was defined as `wasm_runtime_malloc()` in some examples, so what I want to ask is that `os_mmap()` is used to map memory or malloc memory?

**Comment by xwang98** [comment]
@takoyakiyo If you don't need to support the AoT/JIT, you can just return NULL from the os_mmap(). If it is needed and your OS doesn't have builtin mmap() support, you can just allocate a executable memory in this function and return the memory address.
