### ISSUE TITLE
Unexpected behavior of the instruction `table.init`

### ISSUE THREAD

**Issue by erxiaozhou** [bytecodealliance/wasm-micro-runtime#3021]
# Build commands
I compile the code with commit id 892a94fd05f2e95fc68535d763bf67ab1b8e6263.
Platform: Ubuntu 20.04
CPU: amd64

Here we take the warm on JIT mode for example. This issue also exists in warm on other modes (classic interpreter mode, fast interpreter mode, fast JIT mode, multi JIT mode).
 
compile:
```
export CC=/usr/lib/llvm-16/bin/clang
export CXX=/usr/lib/llvm-16/bin/clang++
cd product-mini/platforms/linux/;rm -rf build
cmake -DWAMR_BUILD_AOT=1 -DWAMR_BUILD_FAST_JIT=1   -DWAMR_BUILD_REF_TYPES=1 -DCMAKE_BUILD_TYPE=Release  -DWASM_ENABLE_BULK_MEMORY=1 -DWAMR_BUILD_LIBC_WASI=0 -DWAMR_BUILD_LIBC_BUILTIN=1 -DWAMR_BUILD_SIMD=1  -Bbuild
```

```
iwasm --heap-size=0  --fast-jit -f to_test <tc_name>
```

# Case

[fast_jit_wamr_table.init_no_exception.zip](https://github.com/bytecodealliance/wasm-micro-runtime/files/13941632/fast_jit_wamr_table.init_no_exception.zip)

# Actual output:
No exception

# Expected output:
There is an exception indicating "out of bounds table access".

**Comment by erxiaozhou** [comment]
In the interpreter mode and fast JIT mode, there is a "memory OOB" exception.

**Comment by wenyongh** [comment]
@erxiaozhou thanks for reporting the issue, please try #3031.

**Comment by wenyongh** [comment]
Close this issue as it was fixed.
