### ISSUE TITLE
Question about Alloc_With_Allocator

### ISSUE THREAD

**Issue by kk8916** [bytecodealliance/wasm-micro-runtime#303]
Referring to some examples  of embedded OS,I ported the WAMR to an embedded OS successfully. It can work my sample of aot file well. I noticed that in some examples of embedded OS, the `mem_alloc_type` is `Alloc_With_Pool` . I used it, too. But when I tried to define the `mem_alloc_type`  as `Alloc_With_Allocator`, something was wrong. I didn't change anything except to  initialize the memory allocation functions for the embedded operating system's functions. Sometimes it prints nothing and sometimes it prints `magic header not detected`. Should I change more code? What scenarios will use the  ` Alloc_With_Allocator` type?

**Comment by wenyongh** [comment]
@kk8916 if you set mem_alloc_type to Alloc_With_Allocator, you should pass the memory malloc/free function pointers to RuntimeInitArgs.mem_alloc_option.allocator structure, for example, we can set them to malloc/free function under Linux platform. If you haven't implemented your memory allocator, please use other options.
