### ISSUE TITLE
how to call a export function by name ?

### ISSUE THREAD

**Issue by panicfrog** [bytecodealliance/wasm-micro-runtime#3072]
I want to call a method in a module by method name. For example, call the `_start` method. So I hope to get `wasm_module_inst_t` from `wasm_instance_t`. But I found that there is no way to do it in the exported header files (`wasm_export.h` and `wasm_c_api.h`).  It seems that a new `wasm_module_inst_t` must be created through `wasm_runtime_instantiate`, and the one in `wasm_instance_t` cannot be reused. Very much looking forward to your replies.

**Comment by lum1n0us** [comment]
If with *wasm_c_api.h*, 

- `wasm_module_exports()` returns a list of all exports kind and name. 
- `wasm_instance_exports()` returns a list of all exports objects. Both lists share the same order.
- Combine two lists, you can implement call an export function by name.
