### ISSUE TITLE
thread_spawn_wrapper  CRASH, exec_env is NULL

### ISSUE THREAD

**Issue by JakeOrange** [bytecodealliance/wasm-micro-runtime#3124]
When I called `_start` in the 
[wasi_threads_exit_main_block.wasm.zip](https://github.com/bytecodealliance/wasm-micro-runtime/files/14155395/wasi_threads_exit_main_block.wasm.zip) on the MacOS and Android， thread_spawn_wrapper  CRASH, exec_env is NULL。 I had setting `WASM_ENABLE_INTERP=1, WASM_ENABLE_FAST_INTERP=1, WASM_ENABLE_LIBC_WASI=1, WASM_ENABLE_LIBC_BUILTIN=1, WASM_ENABLE_REF_TYPES, WASM_ENABLE_LIB_WASI_THREADS=1, WASM_ENABLE_BULK_MEMORY=1, WASM_ENABLE_SHARED_MEMORY=1, WASM_ENABLE_THREAD_MGR=1, CLUSTER_MAX_THREAD_NUM=12, BH_FREE=wasm_runtime_free, BH_MALLOC=wasm_runtime_malloc`.

 How do I use mult-thread?

**Comment by yamt** [comment]
> When I called `_start` in the [wasi_threads_exit_main_block.wasm.zip](https://github.com/bytecodealliance/wasm-micro-runtime/files/14155395/wasi_threads_exit_main_block.wasm.zip) on the MacOS and Android， thread_spawn_wrapper CRASH, exec_env is NULL。 I had setting `WASM_ENABLE_INTERP=1, WASM_ENABLE_FAST_INTERP=1, WASM_ENABLE_LIBC_WASI=1, WASM_ENABLE_LIBC_BUILTIN=1, WASM_ENABLE_REF_TYPES, WASM_ENABLE_LIB_WASI_THREADS=1, WASM_ENABLE_BULK_MEMORY=1, WASM_ENABLE_SHARED_MEMORY=1, WASM_ENABLE_THREAD_MGR=1, CLUSTER_MAX_THREAD_NUM=12, BH_FREE=wasm_runtime_free, BH_MALLOC=wasm_runtime_malloc`.

i couldn't reproduce it with iwasm on macOS x86-64.

**Comment by JakeOrange** [comment]
> i couldn't reproduce it with iwasm on macOS x86-64.

After I instantiated the module, I only call the `_start` function. No any host code. I have no idea. 
Do you have any suggestions for checking?

<img width="1297" alt="截屏2024-02-05 21 15 00" src="https://github.com/bytecodealliance/wasm-micro-runtime/assets/22193485/7be0503c-c670-45ff-b8a1-a07ea4b98321">
<img width="902" alt="截屏2024-02-05 21 18 42" src="https://github.com/bytecodealliance/wasm-micro-runtime/assets/22193485/c4da147b-b586-4112-8838-3371e2ee005e">

**Comment by lum1n0us** [comment]
Also couldn't reproduce it with `iwasm -v=5 -f _start wasi_threads_exit_main_block.wasm`.

Here are some debugging BKMs.

- use `iwasm -f _start` or `iwasm` to reproduce.
- `wasm_runtime_invoke_native()` prepares parameters and stores in `argv1`. please check the value of `argv1`, `fps`, `ints`, `stacks`, `n_ints`, `n_stacks`. especially, values in `ints`. if using lldb, you might want to `memory read -f x --size 4 --count 8 ints`
- after `wasm_runtime_invoke_native()`, goes to *invokeNative_XXX.s*, `XXX` should be *em64* or *em64_simd* depends on if enabling `WAMR_BUILD_SIMD` or not.

**Comment by JakeOrange** [comment]
SIMD open cause the issue. Thank you very much!
