### ISSUE TITLE
How to utilize WAMR with SGX in my own .wasm app？

### ISSUE THREAD

**Issue by leyao-daily** [bytecodealliance/wasm-micro-runtime#318]
For example, I have a rust app and compile to .wasm.
I want run this .wasm in the SGX enclave.
I find the mini-product linux-sgx and samples in it.
But how can I run my app in SGX enclave with WAMR runtime?
Is there any guide or examples? Thanks.

**Comment by leyao-daily** [comment]
And in warmc, I found -sgx feature, it describe "generate SGX code", what doest it mean? Is that means, when i exec iwasm xxx.aot, it will run in SGX enclave?

**Comment by wenyongh** [comment]
@leyao-daily currently the wasm file is statically linked to runtime by byte array, you can replace file product-mini/platforms/linux-sgx/enclave-sample/Enclave/test_wasm.h with your own file by using binarydump to generate it:

    cd test-tools/binarydump-tool
    mkdir build && cd build
    cmake .. && make
    ./binarydump -o test_wasm.h -n wasm_test_file test.wasm
    (or ./binarydump -o test_wasm.h -n wasm_test_file test.aot)
    remove "__aligned(4)" in test_wasm.h
    cp -a test_wasm.h ${WAMR_ROOT}/product-mini/platforms/linux-sgx/enclave-sample/Enclave/
    cd ${WAMR_ROOT}/product-mini/platforms/linux-sgx/enclave-sample
    make clean && make

We have basically implemented running wasm file in host by sending it from host to enclave to execute with sgx ecall, we will submit the patch soon.

For the AoT, yes, wamr supports running aot file in SGX, by default it is disabled, you can use cmake -DWAMR_ENABLE_AOT=1 to enable it when building linux-sgx:

    cd ${WAMR_ROOT}/product-mini/platforms/linux-sgx/
    mkdir build && cd build
    cmake .. -DWAMR_BUILD_AOT=1

**Comment by leyao-daily** [comment]
@wenyongh It is very helpful, Thanks a lot. 👍

**Comment by wenyongh** [comment]
Welcome @leyao-daily , we have submitted a new patch, now the enclave sample is built as binary iwasm, which can run host wasm file or aot file (send to enclave to run), similar to iwasm built in Linux platform, please pull and try again.

**Comment by leyao-daily** [comment]
Excellent! I have tried right now and it works well. 
Another question: I complie .wasm to aot file with warmc, and one with no -sgx and one with warnc -sgx -o xx.aot xx.wasm
Both of them can be run by linux-sgx iwasm. 
So what is the usage of the -sgx in warmc command. It describe "generate SGX code". What is that mean, what code it generates? Thanks again.

**Comment by wenyongh** [comment]
Please had better use -sgx option to generate aot code for SGX platform, or llvm codegen might generate machine code with unsupported relocation type for SGX, and we cannot run that code in SGX.
