### ISSUE TITLE
GC: aot_set_llvm_basic_types causes LLVM assertion failure

### ISSUE THREAD

**Issue by yamt** [bytecodealliance/wasm-micro-runtime#3188]
PointerType to void is not valid.
cf. https://github.com/llvm/llvm-project/blob/7d8b50aaab8e0f935e3cb1f3f397e98b9e3ee241/llvm/lib/IR/Type.cpp#L737

**Comment by yamt** [comment]
i have a local patch to use LLVMPointerTypeInContext.
while it avoids the assertion failue, i don't know if it actually works. (i haven't used GC at all.)
also, LLVMPointerTypeInContext is only available for LLVM >=15.

**Comment by TianlongLiang** [comment]
Hi, I replaced the void type pointer with int8 type pointer in this [patch](https://github.com/bytecodealliance/wasm-micro-runtime/pull/3197), in this way, it should work with the lower version of LLVM too

**Comment by wenyongh** [comment]
Fixed with #3197.
