### ISSUE TITLE
Does wamr support fiber?

### ISSUE THREAD

**Issue by vkensou** [bytecodealliance/wasm-micro-runtime#3219]
I am exploring a fiber-based task scheduler at [FiberTaskingLib](https://aichat.diandian.info/url). I aim to manage tasks for both the host and WebAssembly (wasm) environments. While I have learned how to spawn threads from the host using samples, I lack knowledge about fibers. I understand that there is a WebAssembly proposal for stack switching.
Does wamr support fibers, and can I switch context from the host?

**Comment by wenyongh** [comment]
Hi, WAMR hasn't supported fibers and the stack switching proposal yet, not sure what is your requirements, maybe you can re-rewrite the platform APIs? Notes that the spawn thread API calls os_thread_create, which calls pthread_create in linux platform.
https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/core/shared/platform/common/posix/posix_thread.c#L57-L112

Or do you need the thread suspend/resume/wait related APIs? It was experimented under branch [dev/thread_suspension](https://github.com/bytecodealliance/wasm-micro-runtime/tree/dev/thread_suspension), but more efforts need to take on it:
https://github.com/bytecodealliance/wasm-micro-runtime/blob/dev/thread_suspension/core/iwasm/libraries/thread-mgr/thread_manager.h#L143-L174
