### ISSUE TITLE
Build error: Building samples/basic for AARCH64 target

### ISSUE THREAD

**Issue by xicocana** [bytecodealliance/wasm-micro-runtime#322]
I am trying to build the basic sample for aarch64 target.

On the CMakeLists.txt I have changed the WAMR_BUILD_TARGET from:
```
set (WAMR_BUILD_TARGET "X86_64")
```
to:
```
set (WAMR_BUILD_TARGET "AARCH64")
```

but i get the following build error (log.txt file in attachment) :
```
CMakeFiles/vmlib.dir/build.make:420: recipe for target 'CMakeFiles/vmlib.dir/home/user/wasm_runtimes/wasm-micro-runtime/core/iwasm/common/arch/invokeNative_aarch64.s.o' failed
make[2]: *** [CMakeFiles/vmlib.dir/home/user/wasm_runtimes/wasm-micro-runtime/core/iwasm/common/arch/invokeNative_aarch64.s.o] Error 1
CMakeFiles/Makefile2:97: recipe for target 'CMakeFiles/vmlib.dir/all' failed
make[1]: *** [CMakeFiles/vmlib.dir/all] Error 2
Makefile:103: recipe for target 'all' failed
make: *** [all] Error 2
BUILD_FAIL basic exit as 0\n
```

[log.txt](https://github.com/bytecodealliance/wasm-micro-runtime/files/4991650/log.txt)

Do I need to change something else?
Thanks

**Comment by xujuntwt95329** [comment]
Seems your toolchain doesn't support `aarch64` instructions, have you changed the `CMAKE_C_COMPILER` to your cross-compiler ?
You can use `make VERBOSE=1` to check which compiler you are using.

**Comment by xicocana** [comment]
thanks @xujuntwt95329 ! I indeed forgot about the toolchain. I'll give it a try and report back

**Comment by xicocana** [comment]
I changed the CMAKE_C_COMPILER to my cross compiler toolchain ```aarch64-none-elf-gcc```.
But now I'm having the following problem:
```
aarch64-none-elf-gcc: error: unrecognized command line option '-mindirect-branch-register'

```

Can I remove this command line option so that my toolchain works? Or is it essential? If that's the case could you recommend a different toolchain?

**Comment by xicocana** [comment]
@xujuntwt95329 I have changed the cross compiler toolchain to ```aarch64-none-linux-gnu-gcc``` and all is working fine now. thanks
