### ISSUE TITLE
CMake issues with zlib

### ISSUE THREAD

**Issue by sergiizubchevskyy** [bytecodealliance/wasm-micro-runtime#325]
Good morning!

I was having issues with CMake, during LLVM build. 

Basically in order to proceed I needed to add the following line in the CMakeList.txt:
`find_package(ZLIB REQUIRED)`

CMake version I'm using right now is 3.18.0, and the one that is required is 2.8. 

I think this may cause issues on more modern CMakes.

**Comment by wenyongh** [comment]
@sergiizubchevskyy seems that zlib isn't installed, could you please install it? Try whether the command works:

    sudo apt-get install zlib1g-dev

**Comment by sergiizubchevskyy** [comment]
At the time of the issue I tried this command, it was already installed :smile: 

If it works on your machine with updated CMake and without adding find_package(ZLIB required), please close the issue.

Might be problems on my side, but as I sad, just adding find_package solved it.

**Comment by wenyongh** [comment]
Could you try adding the following line to build_llvm.sh:

    -DLLVM_ENABLE_ZLIB:BOOL=OFF

**Comment by sergiizubchevskyy** [comment]
At the moment I cannot recompile LLVM due to time constraints, sorry

But with the updated version of CMake you don't have any issues?

**Comment by sergiizubchevskyy** [comment]
Actually managed to build LLVM again.

Your suggestion solved the issue!

Is this option should be explicitly disabled as you suggested at your main branch?

**Comment by wenyongh** [comment]
Some options including this were disabled in latest patch to decrease the binary size of llvm library.
