### ISSUE TITLE
Can WAMR work in a bare-metal environment (a physical machine without OS and other software)?

### ISSUE THREAD

**Issue by miraclejzd** [bytecodealliance/wasm-micro-runtime#3257]
I am exploring how Webassembly operates on IoT devices, which are bare metal machines with limited resources so that it is hard to install a complete OS such as Linux on them. Can WAMR work under the circumstances? Is there any guide that I can follow?

**Comment by wenyongh** [comment]
Hi, WAMR is supposed to be able to run in some resource limited environments, may be you can build WAMR with some features enabled or disabled:
- Use global heap: initialize a global byte buffer as a heap allocator and allocate memory from it, so as not to call system malloc/free - `cmake -DWAMR_BUILD_GLOBAL_HEAP_POOL=1`.
- Disable libcwasi: `cmake -DWAMR_BUILD_LIBC_WASI=0`, and even disable libc-builtin if needed: `cmake  -DWAMR_BUILD_LIBC_BUILTIN=0`
- Disable some other features: `cmake -DWAMR_DISABLE_WAKEUP_BLOCKING_OP=1 -DWAMR_DISABLE_HW_BOUND_CHECK=1 -DWAMR_DISABLE_WRITE_GS_BASE=1 -DWAMR_BUILD_QUICK_AOT_ENTRY=0`

For the above options, please refer to: https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/doc/build_wamr.md#wamr-vmcore-cmake-building-configurations

- Add a new platform and implement the vmcore APIs

See https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/doc/port_wamr.md
