### ISSUE TITLE
Unexpected behavior on JIT mode

### ISSUE THREAD

**Issue by erxiaozhou** [bytecodealliance/wasm-micro-runtime#3286]
### Subject of the issue
The WAMR on JIT mode raise on exception on an invalid test case (i.e., a test case with invalid an opcode).
### Test case
[f32x4.add_66_116_17118879201058803.zip](https://github.com/bytecodealliance/wasm-micro-runtime/files/14896222/f32x4.add_66_116_17118879201058803.zip)

### Your environment

* Host OS: Ubuntu 20.04
* Commit Id: 4ef724bbfffab1c7761b2674c483a8e7d7c840b8

### Steps to reproduce
1. build WAMR in JIT mode
```
export CC=/usr/lib/llvm-16/bin/clang
export CXX=/usr/lib/llvm-16/bin/clang++
cd product-mini/platforms/linux/;rm -rf build
cmake -DWAMR_BUILD_AOT=1 -DWAMR_BUILD_FAST_JIT=1   -DWAMR_BUILD_REF_TYPES=1 -DCMAKE_BUILD_TYPE=Release  -DWASM_ENABLE_BULK_MEMORY=1 -DWAMR_BUILD_LIBC_WASI=0 -DWAMR_BUILD_LIBC_BUILTIN=1 -DWAMR_BUILD_SIMD=1  -Bbuild
```
2. execute the command
```
iwasm --heap-size=0 --llvm-jit -f "to_test" <test_case>
```

### Expected behavior
An exception indicating "unknown 0xfd subopcode: 0xa5 (at offset 0x55)"

### Actual behavior
Output
```
<0x7fffffff7fffffff 0x7fffffff7fffffff>:v128
```

**Comment by wenyongh** [comment]
@erxiaozhou Thanks for spotting the issue! it was fixed in #3290, please try again.
