### ISSUE TITLE
macos CI runs failed

### ISSUE THREAD

**Issue by wenyongh** [bytecodealliance/wasm-micro-runtime#3364]
https://github.com/bytecodealliance/wasm-micro-runtime/actions/runs/8841321431
https://github.com/bytecodealliance/wasm-micro-runtime/actions/runs/8842970854

Seems that we had better add `--break-system-packages` flag for all macos OSs in the below command:
`/usr/bin/env python3 -m pip install -r requirements.txt`

**Comment by yamt** [comment]
it seems a bit more complex than that.
our workflows assume macos-latest is intel. but now it's arm64.

**Comment by yamt** [comment]
https://github.com/bytecodealliance/wasm-micro-runtime/pull/3366
