### ISSUE TITLE
Can't access certain wasm-c-api memory related methods

### ISSUE THREAD

**Issue by DiogoCorreiaDev** [bytecodealliance/wasm-micro-runtime#345]
So I was messing around with the wasm-c-api, trying to understand how wamr handles linear memory and I tried calling some methods but I always get an "undefined reference" error when trying to compile. The error occurs for the following methods:

wasm_memory_size
wasm_memory_data_size
wasm_memory_data

I know these methods work with wasmtime, and they seem to also be available in wasm_c_api.h, but not in wasm_c_api.c. Have they not been fully implemented yet, or am I missing something?

In case they're not available yet, is there any time estimate to when they will be?

**Comment by lum1n0us** [comment]
No, you are not missing anything, we haven't implemented memory related APIs  yet.The fully support plan is still under discussion, you will find them as soon as they are finished.
