### ISSUE TITLE
Unexpected behavior on fast interpreter mode

### ISSUE THREAD

**Issue by erxiaozhou** [bytecodealliance/wasm-micro-runtime#3467]
### Subject of the issue
The test case is expected to lead to an exception "unreachable". However, the warm on fast interpreter mode fails to raise the exception. Is it caused by the optimization in the fast interpreter?
### Test case

[tt_unreachable.zip](https://github.com/bytecodealliance/wasm-micro-runtime/files/15418698/tt_unreachable.zip)

### Your environment

* Host OS: Ubuntu 20.04
* Commit Id: f378edc408382b7bcf517b463d4a54948739075b

### Steps to reproduce
1. build WAMR on fast interpreter mode
2. execute the command
```
iwasm --heap-size=0 -f "to_test" <test_case>
```
### Expected behavior
```
Exception: unreachable
```
### Actual behavior

```
-1.861157e+19:f32
```

**Comment by wenyongh** [comment]
@erxiaozhou thanks for spotting the issue! I submitted PR #3482 to fix it, please try again.

**Comment by wenyongh** [comment]
Close the issue as it was fixed.
