### ISSUE TITLE
Request to add vmlib on Android platform to align with Linux platform

### ISSUE THREAD

**Issue by dashuaic** [bytecodealliance/wasm-micro-runtime#3486]
On Linux platform, there is a vmlib build out by default ,
https://github.com/bytecodealliance/wasm-micro-runtime/blob/6067dbb3ab5ed12f704750e5910fe5108cb3933a/product-mini/platforms/linux/CMakeLists.txt#L131
While on Android this is no lib vmlib built.
Requirement to build vmlib on Android platform, so the cross-platform code we can only link with vmlib.

**Comment by wenyongh** [comment]
#3488

**Comment by dashuaic** [comment]
Thanks @wenyongh for your quick update.
