### ISSUE TITLE
Question about the structure definition in wgl

### ISSUE THREAD

**Issue by takoyakiyo** [bytecodealliance/wasm-micro-runtime#351]
I want to ask why used `typedef void lv_obj_t` instead of original definition in `lvgl`? Is it necessary to do this or can I still use the original definition？If I want to use a variable of `lv_style_t` in `wgl app`, set up its internal member variables, pass it into the function like `lv_btn_set_style` as a parameter, and call the corresponding `lvgl` function in native, then can I use the original definition of `lv_style_t` in `lvgl` instead of `void`?

**Comment by xwang98** [comment]
@takoyakiyo some detailed explaination can be found here https://github.com/lvgl/lvgl/issues/1523.

**Comment by takoyakiyo** [comment]
> @takoyakiyo some detailed explaination can be found here [lvgl/lvgl#1523](https://github.com/lvgl/lvgl/issues/1523).

Thanks.
I used serialization to process `style`.  And is there any way `wgl` can support `lvgl task create`?

**Comment by xwang98** [comment]
Could you paste the code sample for `lvgl task create` here or give a link to the reference code? so we can have a look?
