### ISSUE TITLE
confused by ints/fps/stacks in funciton wasm_runtime_invoke_native()

### ISSUE THREAD

**Issue by chinesebear** [bytecodealliance/wasm-micro-runtime#354]
I try compiling iwasm in MSYS2+X86_64+GCC+Windows10.
1.what about the 3 variable ints/fps/stacks? 
> ints = argv1;
    fps = ints + MAX_REG_INTS;
    stacks = fps + MAX_REG_FLOATS;

2.when will windows be supported?

**Comment by xujuntwt95329** [comment]
Hi

> ints = argv1;
fps = ints + MAX_REG_INTS;
stacks = fps + MAX_REG_FLOATS;

These variables are used to control the parameter layout when passing parameters to native functions. 

Different architectures/platforms have different `ABI`, for example, on some platforms, all parameters are passed through the stack, on other platforms, there may be some registers to pass integers and float numbers, so we need to fill the registers at first, and then put the rest of parameters on the stack.

So here, we use `ints` to indicate how many registers are used to pass integers, and `fps` to indicate how many regs are used to pass float/doubles, and we will fill the corresponding registers in the `asm` file for every architecture

> 2.when will windows be supported?

We have enabled the AOT compiler `wamrc` and mini runtime product `iwasm` on windows based on `MSVC`, but it is still under testing. You can follow these steps to have a try:

``` bash
cd ${WAMR_ROOT}/product-mini/platforms/windows
mkdir build && cd build
cmake ..
```
and then open the `iwasm.sln` under `build` dir to build the project

> Note: the windows build is tested on `Windows 10 + Visual Studio 2019`
