### ISSUE TITLE
What is the difference between WAMR_BUILD_LIBC_BUILTIN and WAMR_BUILD_LIBC_WASI?

### ISSUE THREAD

**Issue by dpinthinker** [bytecodealliance/wasm-micro-runtime#362]
I am confused about these two definitions(WAMR_BUILD_LIBC_BUILTIN and WAMR_BUILD_LIBC_WASI).
Are they designed for apps or runtime? How should we config them?

For example, if I want to the app not built-in libc by itself, and use the runtime's libc api. How should I config the definition for runtime?

**Comment by kfessel** [comment]
They configure the runtime in different ways and provide different interfaces for apps to use.

...LIBC_BUILTIN implements a partial standard libc (malloc printf ... its interface is visible in  <wamr>core/iwasm/libraries/libc-builtin /libc_builtin_wrapper.c starting a line 1052)
... LIBC_WASI implements a libc according to the WASI standard which replaces a number of functions for variants that are sandboxable especially things like open that require resorces outside of the sandbox are different from standard libc.
 its interface is visible in  <wamr>/core/iwasm/libraries/libc-wasi/libc_wasi_wrapper.c starting a line 1183)

I think its configurable for a reason you decide either a partial standard libc or a non standard libc that is made specific as a sandboxable WASM system interface.  Who is writing the code you want to run?
