### ISSUE TITLE
CI: ghcr.io login failure

### ISSUE THREAD

**Issue by yamt** [bytecodealliance/wasm-micro-runtime#3636]
eg. https://github.com/bytecodealliance/wasm-micro-runtime/actions/runs/9966644711/job/27539140473?pr=3634
```
  /usr/bin/docker --config /home/runner/work/_temp/.docker_a388664c-fdd5-4313-8559-a06c7cf45f18 login ghcr.io -u yamt --password-stdin
  Warning: Docker login for 'ghcr.io' failed with exit code 1, back off 2.996 seconds before retry.
  /usr/bin/docker --config /home/runner/work/_temp/.docker_a388664c-fdd5-4313-8559-a06c7cf45f18 login ghcr.io -u yamt --password-stdin
  Warning: Docker login for 'ghcr.io' failed with exit code 1, back off 9.564 seconds before retry.
  /usr/bin/docker --config /home/runner/work/_temp/.docker_a388664c-fdd5-4313-8559-a06c7cf45f18 login ghcr.io -u yamt --password-stdin
  Error: Docker login for 'ghcr.io' failed with exit code 1
```

**Comment by yamt** [comment]
@no1wudi
i think it's trying to pull your image.
ghcr.io/no1wudi/nuttx/apache-nuttx-ci-linux@sha256:8c4e00b607d4d6d66ba8f51c4544819a616eac69d3a2ac669e2af2150e2eb0f9
do you have any idea?

**Comment by no1wudi** [comment]
> @no1wudi i think it's trying to pull your image. ghcr.io/no1wudi/nuttx/apache-nuttx-ci-linux@sha256:8c4e00b607d4d6d66ba8f51c4544819a616eac69d3a2ac669e2af2150e2eb0f9 do you have any idea?

Emm, I'm not very familiar with it, this image is public, maybe just temporary network failure?

**Comment by yamt** [comment]
> > @no1wudi i think it's trying to pull your image. ghcr.io/no1wudi/nuttx/apache-nuttx-ci-linux@sha256:8c4e00b607d4d6d66ba8f51c4544819a616eac69d3a2ac669e2af2150e2eb0f9 do you have any idea?
> 
> Emm, I'm not very familiar with it, this image is public, maybe just temporary network failure?

i couldn't pull it locally.
```
spacetanuki% docker pull ghcr.io/apache/nuttx/apache-nuttx-ci-linux@sha256:d9261eacf6c6ebe656c571757751c803e8f04c3ae9b820320a5ea5dd57b7205a
Error response from daemon: Get "https://ghcr.io/v2/apache/nuttx/apache-nuttx-ci-linux/manifests/sha256:d9261eacf6c6ebe656c571757751c803e8f04c3ae9b820320a5ea5dd57b7205a": denied: denied
spacetanuki% 
```

**Comment by yamt** [comment]
> > > @no1wudi i think it's trying to pull your image. ghcr.io/no1wudi/nuttx/apache-nuttx-ci-linux@sha256:8c4e00b607d4d6d66ba8f51c4544819a616eac69d3a2ac669e2af2150e2eb0f9 do you have any idea?
> > 
> > 
> > Emm, I'm not very familiar with it, this image is public, maybe just temporary network failure?
> 
> i couldn't pull it locally.
> 
> ```
> spacetanuki% docker pull ghcr.io/apache/nuttx/apache-nuttx-ci-linux@sha256:d9261eacf6c6ebe656c571757751c803e8f04c3ae9b820320a5ea5dd57b7205a
> Error response from daemon: Get "https://ghcr.io/v2/apache/nuttx/apache-nuttx-ci-linux/manifests/sha256:d9261eacf6c6ebe656c571757751c803e8f04c3ae9b820320a5ea5dd57b7205a": denied: denied
> spacetanuki% 
> spacetanuki% docker pull ghcr.io/no1wudi/nuttx/apache-nuttx-ci-linux@sha256:8c4e00b607d4d6d66ba8f51c4544819a616eac69d3a2ac669e2af2150e2eb0f9
> Error response from daemon: Get "https://ghcr.io/v2/no1wudi/nuttx/apache-nuttx-ci-linux/manifests/sha256:8c4e00b607d4d6d66ba8f51c4544819a616eac69d3a2ac669e2af2150e2eb0f9": denied: denied
> spacetanuki% 
> ```

well, maybe it's just because ghcr.io doesn't allow anonymous access.

i wonder why the github workflow was trying to login with "yamt" user.
maybe something has been changed in the infra?

**Comment by no1wudi** [comment]
@yamt I've tried pull this image on two computer with different network environment, can not reproduce this issue

**Comment by yamt** [comment]
yea, it seems working now. maybe it was a transient error as you said.

can anyone with permission restart the affected jobs?
https://github.com/bytecodealliance/wasm-micro-runtime/pull/3635
https://github.com/bytecodealliance/wasm-micro-runtime/pull/3634

**Comment by no1wudi** [comment]
> can anyone with permission restart the affected jobs? #3635 #3634

@wenyongh

**Comment by wenyongh** [comment]
@no1wudi Sorry I am on vocation today, I re-ran them and they work now.

**Comment by yamt** [comment]
i haven't seen this since then.
