### ISSUE TITLE
An invalid section specifier `.aot_stack_sizes`

### ISSUE THREAD

**Issue by lum1n0us** [bytecodealliance/wasm-micro-runtime#3730]
There is a LLVM ERROR occurring on MacOS/x86-64:

``` log
LLVM ERROR: Global variable '__orc_lcl.aot_stack_sizes.0' has an invalid section specifier '.aot_stack_sizes': mach-o section specifier requires a segment and section separated by a comma.
```

@yamt @wenyongh 

I am uncertain if it's related to this line https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/core/iwasm/compilation/aot_llvm.c#L1693. If so, might we need to consider using a new section name includes a comma?

---
original error: 
- https://github.com/proxy-wasm/proxy-wasm-cpp-host/actions/runs/10437349784/job/28903486958?pr=380

similar problems: 
- https://github.com/rustwasm/wasm-bindgen/pull/548/files
- https://github.com/clangupc/clang-upc/issues/6#issuecomment-14596113

**Comment by yamt** [comment]
> There is a LLVM ERROR occurring on MacOS/x86-64:
> 
> ```
> LLVM ERROR: Global variable '__orc_lcl.aot_stack_sizes.0' has an invalid section specifier '.aot_stack_sizes': mach-o section specifier requires a segment and section separated by a comma.
> ```
> 
> @yamt @wenyongh

i'm sure i've tested the combination. (jit + macOS/x86-64 + software stack boundary check)
so i wonder why it didn't happen at that time. maybe macOS version?
anyway, i will take a look.
