### ISSUE TITLE
AOT_SECTION_TYPE_SIGNATURE

### ISSUE THREAD

**Issue by yamt** [bytecodealliance/wasm-micro-runtime#3744]
what's AOT_SECTION_TYPE_SIGNATURE?

as the loader seems to reject it, i guess it's something not used anymore. right?

**Comment by wenyongh** [comment]
Yes but not so correct, in fact it isn't used yet and is just reserved for future use. One scenario I can image is that maybe in the future developer can append signature into the AOT file and provide the signature check callback function to the aot loader, and when aot loader finds there is signature section, it can call the callback with file buffer and size to check.

**Comment by yamt** [comment]
ok. thank you for explanation.
