### ISSUE TITLE
How much performance is improved by enable labels as values function

### ISSUE THREAD

**Issue by chongyang0515** [bytecodealliance/wasm-micro-runtime#378]
I want to run WAMR on the IAR environment, The WASM_ENABLE_LABELS_AS_VALUES macro definition is used in the file named wasm_interp_classic.c, Unfortunately, the IAR compiler does not support the && symbol, I see that used WASM_ENABLE_LABELS_AS_VALUES is enables to improve the interpreter performance,I want to know how much impact it has on the performance , is there a recommended solution to enable the WASM_ENABLE_LABELS_AS_VALUES on the IAR?

**Comment by wenyongh** [comment]
Hi, normally the Lables-as-Values feature improves performance by ~20%, but it depends, some compilers improve much and some improve less. Seems there is no better solution if the compiler doesn't support it, had better just disable it.
