### ISSUE TITLE
question about the errno usage in wasm_application_execute_func()

### ISSUE THREAD

**Issue by Kevin0626** [bytecodealliance/wasm-micro-runtime#381]
I am not clear the purpose of errno in the wasm_application_execute_func(). 

I am building wamr with the newlib which is libc implemented for embedded environment. Because of some reason, I wish we can have no dependency to the symbol "errno".

I use the ld parameter "-y errno -y __errno" to show all the referrence to errno in the newlib. It shows only sbrkr refers to errno.
libc.a(lib_a-sbrkr.o): reference to errno
libc.a(lib_a-reent.o): definition of errno

So I double the errno is not useful for at least newlib in the function. Should we move the errno usage from this function?

**Comment by wenyongh** [comment]
It was used for some reason before, the wasm_application_execute_func() calls strtoul to convert string to integer, and might set errno, and cause unexpected behavior when continuously run the cases:
   "The implementation may also set errno to EINVAL in case no conversion was performed"

Now the spec case test script was changed, and the error disappeared, we removed the related code with errno with patch #396 .
