### ISSUE TITLE
WAMR with JIT Build Failed For iOS On Xcode

### ISSUE THREAD

**Issue by LittleGentry** [bytecodealliance/wasm-micro-runtime#3849]
HI

I want to use JIT on iOS, then I opened WAMR_BUILD_JIT and generated Xcode project with ios-cmake.

While compiling, error occurred in file "aot_compiler.c" function "aot_emit_object_file". Error is system() not available in iOS. I found out system() not supported anymore since iOS11, then I used nftw() instead of system().
Now, compile success, but link error. 
`
Building for 'iOS', but linking in object file (/MyDir/llvm/build/lib/libLLVMDemangle.a[2](Demangle.cpp.o)) built for 'macOS'
`

Tell me please, is JIT supported for iOS? Link Error means that I need build another LLVM for iOS? I really confused about How build JIT for iOS.

**Comment by LittleGentry** [comment]
I worked on release/1.3.x

**Comment by wenyongh** [comment]
Hi, did you build the LLVM by yourself? Could you build it again under iOS? You can try removing the folder `core/deps/llvm` if it exists, and then `cd product-mini/platforms/linux` and `./build_jit.sh`. It will clone llvm to `core/deps` and build it.

**Comment by LittleGentry** [comment]
> Hi, did you build the LLVM by yourself? Could you build it again under iOS? You can try removing the folder `core/deps/llvm` if it exists, and then `cd product-mini/platforms/linux` and `./build_jit.sh`. It will clone llvm to `core/deps` and build it.

I'm sure that I built the LLVM by myself using `warm-compiler/build_llvm.sh`. And `product-mini/platforms/linux/build_jit.sh` doesn't build llvm on branch release/1.3.x. And I work on MacOS, so need I use `product-mini/platforms/darwin/build_llvm.sh` to build llvm again?

**Comment by LittleGentry** [comment]
> Hi, did you build the LLVM by yourself? Could you build it again under iOS? You can try removing the folder `core/deps/llvm` if it exists, and then `cd product-mini/platforms/linux` and `./build_jit.sh`. It will clone llvm to `core/deps` and build it.

I think the key point is that llvm built by macOS doesn't work for iOS with .a file linking error. Maybe our target platform isn't correct, while building llvm by `build_llvm.sh` on macOS.

**Comment by wenyongh** [comment]
> > Hi, did you build the LLVM by yourself? Could you build it again under iOS? You can try removing the folder `core/deps/llvm` if it exists, and then `cd product-mini/platforms/linux` and `./build_jit.sh`. It will clone llvm to `core/deps` and build it.
> 
> I think the key point is that llvm built by macOS doesn't work for iOS with .a file linking error. Maybe our target platform isn't correct, while building llvm by `build_llvm.sh` on macOS.

Yes, I think the compiler should be the same, wondering why not build llvm in iOS?

**Comment by LittleGentry** [comment]
> > > Hi, did you build the LLVM by yourself? Could you build it again under iOS? You can try removing the folder `core/deps/llvm` if it exists, and then `cd product-mini/platforms/linux` and `./build_jit.sh`. It will clone llvm to `core/deps` and build it.
> > 
> > 
> > I think the key point is that llvm built by macOS doesn't work for iOS with .a file linking error. Maybe our target platform isn't correct, while building llvm by `build_llvm.sh` on macOS.
> 
> Yes, I think the compiler should be the same, wondering why not build llvm in iOS?

Sir, I confused about "build llvm in iOS". Do you mean that I should use ios-cmake to configure llvm-project? What I know is that things run on iOS should be built in macOS by Xcode with ios-cmake tool.

**Comment by wenyongh** [comment]
Sorry I am not familiar with how to compile things in iOS, sounds a little complex if we need build things in macOS by Xcode with ios-cmake tool. But in build llvm scripts, seems it doesn't set the target to macOS, you can see the config in the dumped log, somewhat like:
```bash
Config command: cmake -DCMAKE_BUILD_TYPE:STRING="Release" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DLLVM_APPEND_VC_REV:BOOL=ON -DLLVM_BUILD_EXAMPLES:BOOL=OFF -DLLVM_BUILD_LLVM_DYLIB:BOOL=OFF -DLLVM_ENABLE_BINDINGS:BOOL=OFF -DLLVM_ENABLE_IDE:BOOL=OFF -DLLVM_ENABLE_LIBEDIT=OFF -DLLVM_ENABLE_TERMINFO:BOOL=OFF -DLLVM_ENABLE_ZLIB:BOOL=ON -DLLVM_INCLUDE_BENCHMARKS:BOOL=OFF -DLLVM_INCLUDE_DOCS:BOOL=OFF -DLLVM_INCLUDE_EXAMPLES:BOOL=OFF -DLLVM_INCLUDE_UTILS:BOOL=OFF -DLLVM_INCLUDE_TESTS:BOOL=OFF -DLLVM_OPTIMIZED_TABLEGEN:BOOL=ON -DLLVM_CCACHE_BUILD:BOOL=ON -DLLVM_USE_PERF:BOOL=ON -DLLVM_ENABLE_LIBXML2:BOOL=OFF -DLLVM_TARGETS_TO_BUILD:STRING="AArch64;ARM;Mips;RISCV;X86"  -DLLVM_INCLUDE_TOOLS:BOOL=OFF  ../llvm -G'Ninja'
```

I am not sure whether you should add some flags for cmake? e.g. `-DCMAKE_OSX_SYSROOT=iphoneos -DCMAKE_OSX_ARCHITECTURES=arm64 -DCMAKE_TOOLCHAIN_FILE=/path/to/iOS/toolchain.cmake`. If needed, you can add them to CONFIG_CMD in build_llvm.py:
https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/build-scripts/build_llvm.py#L151-L160

And had better use lipo tool to check the architecture of the library: lipo -info /MyDir/llvm/build/lib/libLLVMDemangle.a

**Comment by LittleGentry** [comment]
> Sorry I am not familiar with how to compile things in iOS, sounds a little complex if we need build things in macOS by Xcode with ios-cmake tool. But in build llvm scripts, seems it doesn't set the target to macOS, you can see the config in the dumped log, somewhat like:
> 
> ```shell
> Config command: cmake -DCMAKE_BUILD_TYPE:STRING="Release" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DLLVM_APPEND_VC_REV:BOOL=ON -DLLVM_BUILD_EXAMPLES:BOOL=OFF -DLLVM_BUILD_LLVM_DYLIB:BOOL=OFF -DLLVM_ENABLE_BINDINGS:BOOL=OFF -DLLVM_ENABLE_IDE:BOOL=OFF -DLLVM_ENABLE_LIBEDIT=OFF -DLLVM_ENABLE_TERMINFO:BOOL=OFF -DLLVM_ENABLE_ZLIB:BOOL=ON -DLLVM_INCLUDE_BENCHMARKS:BOOL=OFF -DLLVM_INCLUDE_DOCS:BOOL=OFF -DLLVM_INCLUDE_EXAMPLES:BOOL=OFF -DLLVM_INCLUDE_UTILS:BOOL=OFF -DLLVM_INCLUDE_TESTS:BOOL=OFF -DLLVM_OPTIMIZED_TABLEGEN:BOOL=ON -DLLVM_CCACHE_BUILD:BOOL=ON -DLLVM_USE_PERF:BOOL=ON -DLLVM_ENABLE_LIBXML2:BOOL=OFF -DLLVM_TARGETS_TO_BUILD:STRING="AArch64;ARM;Mips;RISCV;X86"  -DLLVM_INCLUDE_TOOLS:BOOL=OFF  ../llvm -G'Ninja'
> ```
> 
> I am not sure whether you should add some flags for cmake? e.g. `-DCMAKE_OSX_SYSROOT=iphoneos -DCMAKE_OSX_ARCHITECTURES=arm64 -DCMAKE_TOOLCHAIN_FILE=/path/to/iOS/toolchain.cmake`. If needed, you can add them to CONFIG_CMD in build_llvm.py: https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/build-scripts/build_llvm.py#L151-L160
> 
> And had better use lipo tool to check the architecture of the library: lipo -info /MyDir/llvm/build/lib/libLLVMDemangle.a

Yes, I found llvm official docs in its git branch, developer can use config to configure llvm for iOS. I think this maybe help you add iOS platform support after. 
Docs give config :
 `cmake -G "Ninja" -DCMAKE_OSX_ARCHITECTURES="armv7;armv7s;arm64"
    -DCMAKE_TOOLCHAIN_FILE=<PATH_TO_LLVM>/cmake/platforms/iOS.cmake
    -DCMAKE_BUILD_TYPE=Release -DLLVM_BUILD_RUNTIME=Off -DLLVM_INCLUDE_TESTS=Off
    -DLLVM_INCLUDE_EXAMPLES=Off -DLLVM_ENABLE_BACKTRACES=Off [options]
    <PATH_TO_LLVM>` 
Now WAMR start running in my iPhone, but stuck in error ".aot_stack_sizes". I know this issue has been asked by others, and fixed commit has been merged to branch main. But branch release is still stucking. I guess that fixed commit has not been merged to branch release yet? Should I switch to main branch?

**Comment by wenyongh** [comment]
Glad to know that the llvm build issue was fixed. Yes, it is better to switch to main branch.

**Comment by LittleGentry** [comment]
> Glad to know that the llvm build issue was fixed. Yes, it is better to switch to main branch.

OK, right now I run JIT in iPhone successfully. Hope you merge the ".aot_stack_sizes"  fix to release branch as soon as possible. Thanks for your answer and accompany. God bless you.
