### ISSUE TITLE
WAMR behaves differently compared to other runtimes for a particular test case.

### ISSUE THREAD

**Issue by ihayet** [bytecodealliance/wasm-micro-runtime#3929]
### Subject of the issue
WAMR behaves differently compared to other runtimes for a particular test case.

### Test case
Uploaded files.zip contains the wat code, the wasm binary, and the aot file. [files.zip](https://github.com/user-attachments/files/17898202/files.zip)

### Your environment
* WAMR version (2.2.0), platform (Darwin/Linux), cpu architecture (X86_64), running mode (AOT).

### Steps to reproduce
Run `wat2wasm 14.wat` to produce `14.wasm`
Run `wamrc --bounds-checks=1 -o 14.aot 14.wasm` to generate `14.aot`
Run `iwasm -f main 14.aot` to manifest the crash

### Expected behavior
Outputs from the other runtimes are as follows:

wasmtime output:
```
NaN
0.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000009303770844854126
340282366920899777837155946497432354815
```

wasmer output:
```
NaN 0.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000009303770844854126 340282366920899777837155946497432354815
```

wasmedge output:
```
-nan
9.303770844854126e-209
340282366920899777837155946497432354815
```

### Actual behavior
Outputs from `wamrc` and `iwasm` are as follows:

wamrc output:
```
Create AoT compiler with:
  target:        x86_64
  target cpu:    skylake
  target triple: x86_64-pc-linux-gnu
  cpu features:  
  opt level:     3
  size level:    1
  output format: AoT file
Compile success, file 14.aot was generated.
```

iwasm output:
```
unhandled SIGSEGV, si_addr: 0x0
```

Can you confirm if this is a bug? Thanks in advance.

**Comment by TianlongLiang** [comment]
Thanks for reporting it, it's a bug, and I will fix it ASAP. Keep you updated

**Comment by TianlongLiang** [comment]
https://github.com/bytecodealliance/wasm-micro-runtime/pull/3955 should be able to fix it, now on my machine:
```bash
❯ $IWASM_CMD -f main 14.aot                            
-nan:f32,9.303771e-209:f64,<0x001fffffffffffff 0xffffffffffe00000>:v128
```

128-bit integer: 340282366920899777837155946497432354815
Hexadecimal representation: 0xffffffffffe00000001fffffffffffff

**Comment by ihayet** [comment]
Confirming the fix. Closing the issue. Thanks for your prompt response.
