### ISSUE TITLE
Missing Table Type Validation in call_indirect Instruction

### ISSUE THREAD

**Issue by Q1IQ** [bytecodealliance/wasm-micro-runtime#3992]
### Subject of the issue

iwasm fails to validate the type of the table used in the `call_indirect` instruction. According to the [WebAssembly specification](https://webassembly.github.io/spec/core/valid/instructions.html#valid-call-indirect), the table associated with `call_indirect` must have a `funcref` type. 

### Test case

```wasm
(module
  (type (func (param i32 i32) (result i32)))

  (func $func1 (type 0) (param i32 i32) (result i32)
    local.get 0
    local.get 1
    i32.add)

  (func $func2 (type 0) (param i32 i32) (result i32)
    local.get 0
    local.get 1
    i32.sub)

  (table 2 externref)
  (elem (i32.const 0) $func1 $func2)

  (func $main (result i32)
    i32.const 0x12341234
    i32.const 0x1234
    i32.const 1
    call_indirect (type 0)
    )

  (export "main" (func $main))
)
```

### Your environment

* OS: Ubuntu 20.04
* CPU: amd64
* WAMR version: iwasm 1.2.3
* Commands:
```
iwasm  --interp -f main ./program.wasm
iwasm --fast-jit -f main ./program.wasm
iwasm --llvm-jit -f main ./program.wasm
iwasm --multi-tier-jit -f main./program.wasm
```

### Actual behavior

The iwasm proceeds to execute the module without raising any validation error, despite the table having an invalid type (externref) for use in the call_indirect instruction. The observed output in all execution modes is:

```
0x12340000:i32
```

### Expected behavior

The WebAssembly specification mandates that the table used in the call_indirect instruction must be of type funcref. Tables of type externref cannot hold function references and are invalid for call_indirect. The runtime should fail validation and report an error similar to:

```
Validation error: Table 0 must have type 'funcref' to have an element section.
```

**Comment by lum1n0us** [comment]
Can reproduce the result like *0x12340000:i32*.

Could you please provide more details?
- Which build of iwasm are you using? If it's built from source, which branch and commit are you on and your compilation combination?
- What toolchain are you using to convert .wat files to .wasm?

Here are my steps:
- Using main branch, commit 04f1071f1c08b47d734acf0e74511bfeef7c5568
- `cmake -S . -B build`
- `/opt/wabt-1.0.36/bin/wat2wasm --no-check  ./test.wat -o test.wasm`
- `$ /workspaces/wasm-micro-runtime/product-mini/platforms/linux/build/iwasm -f main ./test.wasm` -> WASM module load failed: type mismatch
