### ISSUE TITLE
Can I pass parameter with string/ArrayBuffer type when calling a WASM function from native?

### ISSUE THREAD

**Issue by JavanZhu** [bytecodealliance/wasm-micro-runtime#411]
My WASM TypeScript code:
```TypeScript
// called by native
export function call_by_native_c(strValue: ArrayBuffer): void {  // ArrayBuffer or string?
  console.log("call_by_native_c called: strValue = [" + strValue + "]");
}
```
Hi, I know we can pass parameter with i32 type to wasm function from native. I am wondering if it's possible to pass string type, or it is just not supported now?

**Comment by xujuntwt95329** [comment]
Hi,

The `ArrayBuffer` is an object managed by AssemblyScript Runtime, see memory layout [here](https://www.assemblyscript.org/memory.html#internals). 
It's hard to construct the object from native directly, but we can construct the `ArrayBuffer` in AssemblyScript side:

https://github.com/bytecodealliance/wasm-micro-runtime/blob/c83a5713f9b7bc33cbb0f94d75a35e4b2e35ca89/assembly-script/wamr_app_lib/request.ts#L465-L474

In this code we pass the `buffer_offset` from native to AssemblyScript, the `buffer_offset` is the address of a string in linear memory, it's allocated by API `wasm_runtime_module_malloc` in native, please refer to [passing buffer to wasm function](https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/doc/embed_wamr.md#pass-buffer-to-wasm-function). 
In AssemblyScript we use `new ArrayBuffer(size)` to construct an ArrayBuffer and fill it with content from `buffer_offset`.

Hope this can help you.
