### ISSUE TITLE
Sample for multi-thread can't run

### ISSUE THREAD

**Issue by newbeeXin** [bytecodealliance/wasm-micro-runtime#412]
Hello, developer. When I try the multi-thread sample in linux platform according to the guidance [https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/doc/pthread_library.md](url), an error message is displayed.
“WASM module load failed: unknown data segment”. How can i fix it?

**Comment by xujuntwt95329** [comment]
This should be a bug related to `wasi-sdk` since version 9, the generated wasm file with `-pthread` enabled is wrong.

Could you please download `wasi-sdk` 7 or 8 and try again ?

**Comment by newbeeXin** [comment]
Thank you. My problem has been solved.
