### ISSUE TITLE
In chapter Pass structured data or class object is hard to understand

### ISSUE THREAD

**Issue by deserttime** [bytecodealliance/wasm-micro-runtime#434]
For Pass structured data or class object，How can i achieve it step by step？
there only two methods，Which file do I need to add to compile

**Comment by xujuntwt95329** [comment]
Hi, you can refer [here](https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/doc/export_native_api.md#pass-structured-data-or-class-object), it's an example to show how we pass the structured data.

If you want to use the `restful API` or the serialization library `attribute container`, you may need to add some macro in `CMakeLists.txt` when building runtime:
``` cmake
set (WAMR_BUILD_APP_FRAMEWORK 1)
set (WAMR_BUILD_APP_LIST WAMR_APP_BUILD_BASE)
```

Note that the serialization library is separately compiled into WASM and runtime. So you also need to compile files under [core/app-framework/app-native-shared](https://github.com/bytecodealliance/wasm-micro-runtime/tree/main/core/app-framework/app-native-shared) into wasm app. You can add these source files manually, or you can use WAMR's SDK to create the library and link it:
``` bash
cd ${WAMR_ROOT}/wamr-sdk
./build_sdk.sh     # this will build the default sdk
```
Then you will get the SDK under `out/default/app-sdk/wamr-app-framework/` (we call it `${sdk_root}`), the static library is  `${sdk_root}/lib/libapp_framework.a`, you can link it with your app code; the header file is under `${sdk_root}/bi-inc`, you can include these files in your app code

The [samples/simple](https://github.com/bytecodealliance/wasm-micro-runtime/tree/main/samples/simple) use the WAMR SDK to build both runtime and app, you can refer to it.
