### ISSUE TITLE
Differences between fast interpreter and classic interpreter ?

### ISSUE THREAD

**Issue by keith2018** [bytecodealliance/wasm-micro-runtime#437]
is there any brief description ?

**Comment by wenyongh** [comment]
Hi, there isn't a lot of description yet, but it should be simple to understand: the classic interpreter is classical/traditional interpreter, it handles the WebAssembly bytecodes one by one; the fast interpreter pre-compiles the WebAssembly bytecodes into another optimized bytecodes to improve the performance. So the performance of fast interpreter is better than classic interpreter, while the memory usage may be larger. You can ref to the [performance](https://github.com/bytecodealliance/wasm-micro-runtime/wiki/Performance) wiki page for more detail. Thanks.
