### ISSUE TITLE
Ask some questions about SGX and arm

### ISSUE THREAD

**Issue by CanYouGiveMeAName** [bytecodealliance/wasm-micro-runtime#453]
I developed a project on SGX platform with reference to linux-sgx, and then other colleagues developed the same function on ARM platform. Now we want to unify it into one code, but we find that there are some big differences between the platforms, and we don't understand some usages on the SGX platform. We hope to help you.
1) In the app part of SGX, libvmlib_untrusted.a needs to be introduced. But the function of app part is that calls the enclave code through the EDL method. There is no method call related to the WAMR library. On the arm platform, the untrusted part does not need to refer to this .a, so I don't understand the function of this package.
2) In edl file, I don't understand the function of `from "sgx_wamr.edl" import *;`.  On ARM platform, how to realize the same function of this edl.

Thanks very much.

**Comment by wustwn** [comment]
Hi, 

There are two parts, trusted part (SGX enclave) and untrusted space (OS host), which can call each other's functions by ECALL and OCALL respectively. The host can enter the enclave with an ECALL. Once in the enclave, if it need to do something like I/O accessing, then it can use an OCALL to call a function in untrusted space. And when the function returns, it comes back to the enclave.

In Enclave.ed, ecall_iwasm_main function is defined, host can enter the enclave with this ECALL function, and the libvmlib_untrusted.a contains the specific implementation of OCALL functions. 
For example, to implement the open operation:
`enclave sgx_file.c, open ——> enclave_t.c, ocall_open  —— > untrusted/file.c, ocall_open ——> host libc open 
`
Among them, untrusted/ocall_open is compiled in the libvmlib_untruted.a library, and the open operation cannot be implemented normally without it.

sgx_wamr.edl's path is core/shared/platform/linux-sgx. The wasi api OCALL functions are defined internally, such as ocall_open. If the wasm program needs to call IO and other system resources through the wasi api, you must import the edl file. 

I have no idea with SGX on ARM, here are some contents resource about SGX which may give you a hand.
Chinese:
	 https://software.intel.com/content/www/cn/zh/develop/articles/sgx-development-guide-part-3.html
English:
	https://software.intel.com/content/www/us/en/develop/download/sgx-sdk-developer-reference-windows.html
	https://software.intel.com/content/www/us/en/develop/articles/intel-sgx-web-based-training.html

Thanks.

**Comment by CanYouGiveMeAName** [comment]
thanks ！
