### ISSUE TITLE
Crash in WAMR Android platform when enable simd

### ISSUE THREAD

**Issue by newbeeXin** [bytecodealliance/wasm-micro-runtime#486]
I add -DWAMR_BUILD_SIMD to build Android platform runtime iwasm. And when i use "wasm_application_execute_main" or "wasm_runtime_call_wasm" to call a wasm or aot funtion will going to crash. And detele the -DWAMR_BUILD_SIMD in runtime, no exception occurs during running. Is SIMD not supported on WAMR Android platform yet?

**Comment by xujuntwt95329** [comment]
Hi, are you using ARM architecture? Currently, SIMD is only supported on the x86 platform.

**Comment by newbeeXin** [comment]
Yes, i use aarch64 architecture. Expect the SIMD feature of WAMR on the Android platform.
