### ISSUE TITLE
AOT of samples/wasm-c-api exits with error

### ISSUE THREAD

**Issue by Rashow** [bytecodealliance/wasm-micro-runtime#490]
Hi there,
its my first post on a format like this so bare me if i'm not follow some manners ^^ 

Im trying to run the wasm-c-api under samples. It works fine under "interpreter" mode. If i try to run the AOT mode, it exits with an error.

My OS is ubuntu 20.04.

running
 cmake -DWAMR_BUILD_INTERP=0 -DWAMR_BUILD_AOT=1 .. 
gives me:
>  -- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Configuring done
-- Generating done
-- Build files have been written to: /home/weiland/util/wasm-micro-runtime/samples/wasm-c-api/build <

Running make gives me

>
Scanning dependencies of target hello_WASM
[  0%] Built target hello_WASM
Scanning dependencies of target globalexportimport-1_WASM
[  0%] Built target globalexportimport-1_WASM
Scanning dependencies of target globalexportimport-0_WASM
[  0%] Built target globalexportimport-0_WASM
Scanning dependencies of target callback_WASM
[  0%] Built target callback_WASM
Scanning dependencies of target global_WASM
[  0%] Built target global_WASM
Scanning dependencies of target vmlib
[  2%] Building C object CMakeFiles/vmlib.dir/home/weiland/util/wasm-micro-runtime/core/shared/platform/linux/platform_init.c.o
[  4%] Building C object CMakeFiles/vmlib.dir/home/weiland/util/wasm-micro-runtime/core/shared/platform/common/posix/posix_malloc.c.o
[  6%] Building C object CMakeFiles/vmlib.dir/home/weiland/util/wasm-micro-runtime/core/shared/platform/common/posix/posix_memmap.c.o
[  8%] Building C object CMakeFiles/vmlib.dir/home/weiland/util/wasm-micro-runtime/core/shared/platform/common/posix/posix_thread.c.o
[ 10%] Building C object CMakeFiles/vmlib.dir/home/weiland/util/wasm-micro-runtime/core/shared/platform/common/posix/posix_time.c.o
[ 12%] Building C object CMakeFiles/vmlib.dir/home/weiland/util/wasm-micro-runtime/core/shared/mem-alloc/ems/ems_alloc.c.o
[ 14%] Building C object CMakeFiles/vmlib.dir/home/weiland/util/wasm-micro-runtime/core/shared/mem-alloc/ems/ems_hmu.c.o
[ 16%] Building C object CMakeFiles/vmlib.dir/home/weiland/util/wasm-micro-runtime/core/shared/mem-alloc/ems/ems_kfc.c.o
[ 18%] Building C object CMakeFiles/vmlib.dir/home/weiland/util/wasm-micro-runtime/core/shared/mem-alloc/mem_alloc.c.o
[ 20%] Building C object CMakeFiles/vmlib.dir/home/weiland/util/wasm-micro-runtime/core/shared/utils/bh_assert.c.o
[ 22%] Building C object CMakeFiles/vmlib.dir/home/weiland/util/wasm-micro-runtime/core/shared/utils/bh_common.c.o
[ 24%] Building C object CMakeFiles/vmlib.dir/home/weiland/util/wasm-micro-runtime/core/shared/utils/bh_hashmap.c.o
[ 26%] Building C object CMakeFiles/vmlib.dir/home/weiland/util/wasm-micro-runtime/core/shared/utils/bh_list.c.o
[ 28%] Building C object CMakeFiles/vmlib.dir/home/weiland/util/wasm-micro-runtime/core/shared/utils/bh_log.c.o
[ 30%] Building C object CMakeFiles/vmlib.dir/home/weiland/util/wasm-micro-runtime/core/shared/utils/bh_queue.c.o
[ 32%] Building C object CMakeFiles/vmlib.dir/home/weiland/util/wasm-micro-runtime/core/shared/utils/bh_vector.c.o
[ 34%] Building C object CMakeFiles/vmlib.dir/home/weiland/util/wasm-micro-runtime/core/shared/utils/runtime_timer.c.o
[ 36%] Building C object CMakeFiles/vmlib.dir/home/weiland/util/wasm-micro-runtime/core/iwasm/libraries/libc-builtin/libc_builtin_wrapper.c.o
[ 38%] Building C object CMakeFiles/vmlib.dir/home/weiland/util/wasm-micro-runtime/core/iwasm/common/wasm_c_api.c.o
[ 40%] Building C object CMakeFiles/vmlib.dir/home/weiland/util/wasm-micro-runtime/core/iwasm/common/wasm_exec_env.c.o
[ 42%] Building C object CMakeFiles/vmlib.dir/home/weiland/util/wasm-micro-runtime/core/iwasm/common/wasm_memory.c.o
[ 44%] Building C object CMakeFiles/vmlib.dir/home/weiland/util/wasm-micro-runtime/core/iwasm/common/wasm_native.c.o
[ 46%] Building C object CMakeFiles/vmlib.dir/home/weiland/util/wasm-micro-runtime/core/iwasm/common/wasm_runtime_common.c.o
[ 48%] Building C object CMakeFiles/vmlib.dir/home/weiland/util/wasm-micro-runtime/core/iwasm/common/wasm_shared_memory.c.o
[ 51%] Building ASM object CMakeFiles/vmlib.dir/home/weiland/util/wasm-micro-runtime/core/iwasm/common/arch/invokeNative_em64.s.o
[ 53%] Building C object CMakeFiles/vmlib.dir/home/weiland/util/wasm-micro-runtime/core/iwasm/aot/aot_loader.c.o
[ 55%] Building C object CMakeFiles/vmlib.dir/home/weiland/util/wasm-micro-runtime/core/iwasm/aot/aot_runtime.c.o
[ 57%] Building C object CMakeFiles/vmlib.dir/home/weiland/util/wasm-micro-runtime/core/iwasm/aot/arch/aot_reloc_x86_64.c.o
[ 59%] Linking C static library libvmlib.a
[ 59%] Built target vmlib
Scanning dependencies of target globalexportimport
[ 61%] Building C object CMakeFiles/globalexportimport.dir/src/globalexportimport.c.o
[ 63%] Building C object CMakeFiles/globalexportimport.dir/home/weiland/util/wasm-micro-runtime/core/shared/utils/uncommon/bh_getopt.c.o
[ 65%] Building C object CMakeFiles/globalexportimport.dir/home/weiland/util/wasm-micro-runtime/core/shared/utils/uncommon/bh_read_file.c.o
[ 67%] Building C object CMakeFiles/globalexportimport.dir/src/utils/multi_module_utils.c.o
[ 69%] Linking C executable globalexportimport
[ 69%] Built target globalexportimport
Scanning dependencies of target hello
[ 71%] Building C object CMakeFiles/hello.dir/src/hello.c.o
[ 73%] Building C object CMakeFiles/hello.dir/home/weiland/util/wasm-micro-runtime/core/shared/utils/uncommon/bh_getopt.c.o
[ 75%] Building C object CMakeFiles/hello.dir/home/weiland/util/wasm-micro-runtime/core/shared/utils/uncommon/bh_read_file.c.o
[ 77%] Building C object CMakeFiles/hello.dir/src/utils/multi_module_utils.c.o
[ 79%] Linking C executable hello
[ 79%] Built target hello
Scanning dependencies of target global
[ 81%] Building C object CMakeFiles/global.dir/src/global.c.o
[ 83%] Building C object CMakeFiles/global.dir/home/weiland/util/wasm-micro-runtime/core/shared/utils/uncommon/bh_getopt.c.o
[ 85%] Building C object CMakeFiles/global.dir/home/weiland/util/wasm-micro-runtime/core/shared/utils/uncommon/bh_read_file.c.o
[ 87%] Building C object CMakeFiles/global.dir/src/utils/multi_module_utils.c.o
[ 89%] Linking C executable global
[ 89%] Built target global
Scanning dependencies of target callback
[ 91%] Building C object CMakeFiles/callback.dir/src/callback.c.o
[ 93%] Building C object CMakeFiles/callback.dir/home/weiland/util/wasm-micro-runtime/core/shared/utils/uncommon/bh_getopt.c.o
[ 95%] Building C object CMakeFiles/callback.dir/home/weiland/util/wasm-micro-runtime/core/shared/utils/uncommon/bh_read_file.c.o
[ 97%] Building C object CMakeFiles/callback.dir/src/utils/multi_module_utils.c.o
[100%] Linking C executable callback
[100%] Built target callback
<

and then:
>
./hello 
Initializing...
[05:17:23:068 - 99ACF740]: running under mode 2
Loading binary...
> Error loading module!
<

I dont know what you else need to know. 

thank you in advance.

**Comment by wenyongh** [comment]
Hi, the samples load aot file instead of wasm file when AOT mode is enabled and interpreter mode is disabled, e.g. in hello.c:
```C
#if WASM_ENABLE_AOT != 0 && WASM_ENABLE_INTERP == 0
  FILE* file = fopen("hello.aot", "rb");
#else
  FILE* file = fopen("hello.wasm", "rb");
#endif
```
so please build wamrc firstly, ref to [build-wamrc](https://github.com/bytecodealliance/wasm-micro-runtime#build-wamrc-aot-compiler), and then compile the wasm file to aot file in the build folder, e.g.
```
wamrc -o hello.aot hello.wasm
```
and then run again. Thanks.
