### ISSUE TITLE
On Windows X86_64 platform, the fourth parameter of the native function  always is 0

### ISSUE THREAD

**Issue by leehee7** [bytecodealliance/wasm-micro-runtime#509]
On Windows X86_64 platform, after registered the native API, when call the native function, the fourth parameter always is 0.
debug it, and the bug is 
core/iwasm/common/arch/invokeNative_em64.asm
; store stack args
**lea r9, qword ptr [rax + rcx * 8 + 64]**
sub r9, rsp ; offset

it is should be rcx * 8 + 56

please fix it

**Comment by xujuntwt95329** [comment]
fixed in PR #511 , thanks a lot !
