### ISSUE TITLE
In wasi-12.0，compiling  C++ source code with string type  will report error

### ISSUE THREAD

**Issue by leehee7** [bytecodealliance/wasm-micro-runtime#515]
In wasi-12.0，compiling  C++ source code with string type  will report error
error:
undefined symbol: std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> >::basic_string(std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> > const&)

**Comment by wenyongh** [comment]
Hi, how do you build the wasm application with wasi-sdk-12.0? We tested a simple c++ source:
```C
  std::cout << "Hello world!"  << std::endl;
  std::string str("1234");
  std::cout << "Hi str:" << str << std::endl;

  const char *s = str.c_str();
  printf("str: %s, size: %d\n", s, (int)str.size());
```
And build it with wasi-sdk-12.0:
```bash
/opt/wasi-sdk/bin/clang++ -O3 \
    -z stack-size=4096 -Wl,--initial-memory=131072 \
    -Wl,--export=malloc -Wl,--export=free \
    -o test.wasm main.cpp
```
It works, the running result:
```bash
Hello world!
Hi str:1234
str: 1234, size: 4
```
