### ISSUE TITLE
I got two problems when try to build wamr in android 

### ISSUE THREAD

**Issue by xingkaiyu** [bytecodealliance/wasm-micro-runtime#520]
1- if I build it directly, I will got the error info like this:
   core/iwasm/libraries/libc-wasi/sandboxed-system-primitives/src/posix.c:2142:19: error: use of undeclared identifier '__syscall_slong_t'
  out->tv_nsec = (__syscall_slong_t)(in % 1000000000)
  So, I change __syscall_slong_t to long and It is ok.
  But I don't know whether it is the right way and hope you can fix it.
2- I only can build android iwamr when I set the android version higher than or equals to 28.
  when I set android version between 24 and 27, I will got error info like this:
  error: undefined symbol: getrandom(core/iwasm/libraries/libc-wasi/sandboxed-system-primitives/src/random.c:30)
  when I set android version equals to 23, I will got two more error info like this:
  error: undefined symbol: preadv(core/iwasm/libraries/libc-wasi/sandboxed-system-primitives/src/posix.c:846)
  error: undefined symbol: pwritev(core/iwasm/libraries/libc-wasi/sandboxed-system-primitives/src/posix.c:918)
  when the android version less than 23, I will again got two more error info:
  error: undefined symbol: seekdir(core/iwasm/libraries/libc-wasi/sandboxed-system-primitives/src/posix.c:1968)
  error: undefined symbol: telldir(core/iwasm/libraries/libc-wasi/sandboxed-system-primitives/src/posix.c:1982)
  I want to use wamr in android phone since the android version 19. So is there any way to solve it?

**Comment by xujuntwt95329** [comment]
For question 1: yes, you can re-define the __syscall_slong_t as long int.

For question 2:
Currently we haven't supported WASI on Android platform, if you want to use WASI on Android, you can refer to this [commit](https://github.com/xujuntwt95329/wasm-micro-runtime/commit/f6d1d4be1af55e09b524355c1c25931d8de749b8) for reference.

> Note: This commit is not well tested, and some features in WASI may be lost.
