### ISSUE TITLE
Incorrect f32/i64 value sent to C API and only reproducible on hardware

### ISSUE THREAD

**Issue by AfflatusX** [bytecodealliance/wasm-micro-runtime#521]
Hi all - 

I ran into a super weird problem. I have a simple C API exposed to WASM (AS): 
```
static void f32_i64_test(wasm_exec_env_t exec_env, float a, int64_t b) {
  printf("interop value: %f, %lld\n", a, b);
}
```

The symbol is defined as the following code: 
```{ "sys_util.f32_i64_test", f32_i64_test, "(fI)" }```

AssemblyScript definition:

```export function f32_i64_test(a: f32, b: i64): void;```

Simply calling the function with:

```
const fValue: f32 = 9.4235;
const longValue: i64 = 524893248938;
sys_util.f32_i64_test(fValue, longValue);
```

yields: `interop value: 0.000000, 389656108840517632`

I can only reproduce this on actual hardware (cortex-m33, interop), but if I use x86_32 emulator it works correctly.

Any idea how to debug this further? Thanks!

**Comment by wenyongh** [comment]
Hi, this might be caused by ABI inconsistent issue, could you please add _VFP suffix to WAMR_BUILD_TARGET? e.g. ARM_VFP, ARMV7T_VFP?
