### ISSUE TITLE
Question: how to run an AoT binary with ELF object flag enabled

### ISSUE THREAD

**Issue by JamesMenetrey** [bytecodealliance/wasm-micro-runtime#527]
Dear WAMR developers,

I'm working with a restricted environment where I cannot use the traditional AoT file format produced by wamrc since it requires the underlying system to expose an equivalent to mmap for allocating executable memory segments.

After checking the options of WAMR, it seems it provides a way to compile AoT into an ELF object file (with `--format=object`), which seems to solve my issue, as I assume the code segments are handled by the operating system loader and not by WAMR. Nonetheless, there is no documentation about the usage of the binaries produced when using this flag, but I assume I can then link that executable code with another program. Is it correct?

If so, I'm unable to find a way to launch the runtime. What API should I use for that purpose? As an example, I use `test.c` as provided in the documentation [Prepare WASM building environments](https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/doc/build_wasm_app.md). I compiled it into a WebAssembly binary using this command-line:

```
/opt/wasi-sdk/bin/clang -o test.wasm test.c
```

Afterward, I compiled it using wamrc:

```
wamrc -o test.o --format=object test.wasm
```

This produces the object file `test.o`. Could you please provide the next steps to execute it afterward? I would expect to write an application that links this file, but I cannot find any suitable exported symbols:

```
$ readelf -Ws test.o
Symbol table '.symtab' contains 73 entries:
   Num:    Value          Size Type    Bind   Vis      Ndx Name
     0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND 
     1: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS WASM Module
     2: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT    4 .LCPI20_0
     3: 0000000000000010     0 NOTYPE  LOCAL  DEFAULT    4 .LCPI20_1
     4: 0000000000000038     0 NOTYPE  LOCAL  DEFAULT    5 .LCPI20_10
     5: 0000000000000040     0 NOTYPE  LOCAL  DEFAULT    5 .LCPI20_11
     6: 0000000000000048     0 NOTYPE  LOCAL  DEFAULT    5 .LCPI20_12
     7: 0000000000000050     0 NOTYPE  LOCAL  DEFAULT    5 .LCPI20_13
     8: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT    5 .LCPI20_2
     9: 0000000000000008     0 NOTYPE  LOCAL  DEFAULT    5 .LCPI20_3
    10: 0000000000000010     0 NOTYPE  LOCAL  DEFAULT    5 .LCPI20_4
    11: 0000000000000018     0 NOTYPE  LOCAL  DEFAULT    5 .LCPI20_5
    12: 0000000000000020     0 NOTYPE  LOCAL  DEFAULT    5 .LCPI20_6
    13: 0000000000000028     0 NOTYPE  LOCAL  DEFAULT    5 .LCPI20_7
    14: 0000000000000030     0 NOTYPE  LOCAL  DEFAULT    5 .LCPI20_8
    15: 0000000000000058     0 NOTYPE  LOCAL  DEFAULT    5 .LCPI49_0
    16: 0000000000000000     0 SECTION LOCAL  DEFAULT    2 
    17: 0000000000000000     0 SECTION LOCAL  DEFAULT    4 
    18: 0000000000000000     0 SECTION LOCAL  DEFAULT    6 
    19: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND aot_call_indirect
    20: 0000000000000000     1 FUNC    GLOBAL DEFAULT    2 aot_func#0
    21: 0000000000000010   114 FUNC    GLOBAL DEFAULT    2 aot_func#1
    22: 0000000000002280   132 FUNC    GLOBAL DEFAULT    2 aot_func#10
    23: 0000000000002310    41 FUNC    GLOBAL DEFAULT    2 aot_func#11
    24: 0000000000002340   382 FUNC    GLOBAL DEFAULT    2 aot_func#12
    25: 00000000000024c0    21 FUNC    GLOBAL DEFAULT    2 aot_func#13
[..]
    69: 0000000000002270    14 FUNC    GLOBAL DEFAULT    2 aot_func#9
    70: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND aot_invoke_native
    71: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND aot_set_exception_with_id
    72: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND wasm_runtime_enlarge_memory
```

Many thanks for your time!

Cheers

**Comment by wenyongh** [comment]
Hi, currently the object file is just for debug purpose, wasm runtime cannot load and run the object file yet. The object file itself contains the AOTed machine code and relocation info, but doesn't have the info of WASM initialization data, e.g. function type, memory/table size, memory/table init data, global, import info and so on. So object file is not enough for wasm runtime. There might be one way to support that:

Load aot_file + object_file: use aot_file's initialization data and object_file's machine code (text), replace the mmap and AOT function pointers initialization with the OS system loader to load object file (e.g. dlopen) and resolve function pointer from it (e.g. dlsym), and normally the object file needs to be generated with PIC mode, and linked as shared library (e.g. .so file). 

There might be some efforts, we have no plan to support it yet, if you want, could you please try it by yourself? Thanks.
