### ISSUE TITLE
Please add iOS platform support

### ISSUE THREAD

**Issue by Feyewon** [bytecodealliance/wasm-micro-runtime#533]

**Comment by wenyongh** [comment]
Hi, currently there is no plan to support iOS platform yet, could you please try building it for platform linux with AOT mode disabled:
```
cd product-mini/platforms/linux
mkdir build && cd build
cmake .. -DWAMR_BUILD_INTERP=1 -DWAMR_BUILD_AOT=0
make
```
or porting the platform by yourself? Here is the reference [porting guide](https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/doc/port_wamr.md). Thanks.
