### ISSUE TITLE
command-line tool?

### ISSUE THREAD

**Issue by mvolkmann** [bytecodealliance/wasm-micro-runtime#538]
Can this be used as a command-line tool like wasm3 and wasmtime?
If so, the steps to build it seem very complicated.
Is there an easy way to build it as a command-line tool?

**Comment by wenyongh** [comment]
@mvolkmann yes, please ref to [build iwasm under Linux](https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/doc/build_wamr.md#linux), or try:
```bash
cd product-mini/platforms/linux/
mkdir build
cd build
cmake ..
make
```
to generate the binary file iwasm.
