### ISSUE TITLE
How can I use function like vsprintf_s in wasm app

### ISSUE THREAD

**Issue by xingkaiyu** [bytecodealliance/wasm-micro-runtime#546]

**Comment by xingkaiyu** [comment]
As the title.
I want to use vsprintf_s. but I got compile error when put it directly in my code.
I want to import it from native, but I don't know how to deal with the param va_list or ...

**Comment by Paril** [comment]
You'll need a libc implementation - most of that stuff is built into a libc, like WASI, which will give you access to them.
