### ISSUE TITLE
Question about memory shrinking

### ISSUE THREAD

**Issue by AGreat1** [bytecodealliance/wasm-micro-runtime#557]
Hi all!

I'm wondering whether there is any way I can ask the runtime to shrink its memory footprint? Let's say I use WAMR for a plugin framework, and due to some things happening in the host system, some plugins do some hard work, and need to grow their memory with a few pages. Once this is over, I would like to leave more room for other things happening in the system. Does WAMR have an API, or some internal smarts to shrink the memory consumption e.g. when the complete stack is unwound? Is there any alternative to having to persist the plugin state and then restart it?

**Comment by xujuntwt95329** [comment]
Hi, the linear memory can't be shrinked once it is grown, but for your scenario, there may be two work around:

1. Export the `malloc/free` function from your wasm app, then the WAMR's `wasm_runtime_module_malloc` API will allocate memory space from wasm linear memory, so your host system can use the memory inside wasm linear memory, which means the extra pages in your wasm application is "not wasted".

2. Move your complex logic to native APIs, then you can malloc/free memory outside the wasm memory space, then you can avoid the memory grow in your wasm application.
