### ISSUE TITLE
In addition to relying on LLVM, what third-party libraries does wamr rely on?

### ISSUE THREAD

**Issue by leehee7** [bytecodealliance/wasm-micro-runtime#566]
In addition to relying on LLVM, what other third-party libraries does wamr rely on?
Can make a list? We want to do in-depth research on wamr.
    thanks.

**Comment by xujuntwt95329** [comment]
Seems LLVM is the only dependency, and if you build WAMR as pure interpreter, LLVM is not required.

Besides LLVM, if you want to use WASI on windows, then you will need `uvwasi` and `libuv`.

Some samples may need other libraries such as `lvgl`, but that is not related to WAMR.

So only three libraries are related to WAMR:
- `LLVM`  ----> needed by AOT/JIT
- `uvwasi` and `libuv`  ----> needed by Windows WASI support

**Comment by leehee7** [comment]
ok, thanks  very much
