### ISSUE TITLE
wasm_runtime_malloc failed with sufficient heap memory remaining

### ISSUE THREAD

**Issue by AfflatusX** [bytecodealliance/wasm-micro-runtime#568]
I'm running into a strange wasm_runtime_malloc failure -

 - My WASM runtime uses Alloc_With_Pool and have 275 KB static memory assigned to it. 
 - I'm setting APP_THREAD_STACK_SIZE_DEFAULT to 48 KB.
 - During WASM App load process, I print out memory allocation stats.
 - The initialization sequence fails when trying to allocate that 48 KB.
 - specifically this line fails: https://github.com/bytecodealliance/wasm-micro-runtime/blob/54e82ec439552018d0f26c60b0fd6cc9e36b42a8/core/shared/mem-alloc/ems/ems_alloc.c#L473
 - At that point I have more than 90 KB available in heap→total_free_size

1. What's the cause of this? Is it because those 48 KB needs to be consecutive, but the heap doesn't have one block that large?
2. Any way to work around this without allocating excessive memory pool?

**Comment by wenyongh** [comment]
Yes, there should be not one block large enough to use, maybe you can try modifying the value of macro `HMU_NORMAL_NODE_CNT` in ems_gc_internal.h, the default value is 32, maybe you can try changing it to 8-16. And please ref to [how to reduce footprint](https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/doc/build_wasm_app.md#2-how-to-reduce-the-footprint) for more options.
