### ISSUE TITLE
What is mini loader?

### ISSUE THREAD

**Issue by AfflatusX** [bytecodealliance/wasm-micro-runtime#569]
saw this in the config, curious what is the difference between mini-loader and normal loader.

**Comment by xujuntwt95329** [comment]
`Mini-loader` is designed for resource-constrained devices such as MCUs. In the normal loader, there are many const strings to indicate the errors during loading, these error messages are defined by WebAssembly SPEC. While in `mini-loader`, these strings are removed to reduce the footprint, and the developers should ensure thst the wasm module is valid.
