### ISSUE TITLE
Is wasm module must be reload when call wasm_runtime_call_wasm get exception

### ISSUE THREAD

**Issue by xingkaiyu** [bytecodealliance/wasm-micro-runtime#575]
Hi~
I used wamr and sometimes I will get runtime exception when called wasm_runtime_call_wasm (mostly it is my code bug). 
Such as "failed to call unlinked import function (env, XXXX)", "Exception: unreachable", "out of bounds memory access".
And I found that when I got any exception, I will not get success call anymore (these calls‘ code is right), unless I reload the wasm from get .wasm file (the runtime need not be reload)
So, is wamr always need to be reload when get false from wasm_runtime_call_wasm?

**Comment by lum1n0us** [comment]
Yeah, I am afraid so.

WAMR will quit ASAP when meeting any exception.
________________________________
From: xingkaiyu ***@***.***>
Sent: Tuesday, March 16, 2021 10:59 AM
To: bytecodealliance/wasm-micro-runtime ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [bytecodealliance/wasm-micro-runtime] Is wasm module must be reload when call wasm_runtime_call_wasm get exception (#575)


Hi~
I used wamr and sometimes I will get runtime exception when called wasm_runtime_call_wasm (mostly it is my code bug).
Such as "failed to call unlinked import function (env, XXXX)", "Exception: unreachable", "out of bounds memory access".
And I found that when I got any exception, I will not get success call anymore (these calls‘ code is right), unless I reload the wasm from get .wasm file (the runtime need not be reload)
So, is wamr always need to be reload when get false from wasm_runtime_call_wasm?

**Comment by xujuntwt95329** [comment]
You can use `wasm_runtime_set_exception(module_inst, NULL)` to clear the exception and then you can call your other functions.

**Comment by xingkaiyu** [comment]
It is ok now. Thanks ~
