### ISSUE TITLE
How to use AssemblyScript  as WASM module?

### ISSUE THREAD

**Issue by AfflatusX** [bytecodealliance/wasm-micro-runtime#620]
Hi - 

I'm looking for some guidance on how can I build an AssemblyScript lib and load it as a library instead of an app in WAMR.

My understanding is that AS app has its own runtime bundled, but what about AS libs? What configuration should I use to build it and how can I load/export it through WAMR to my main app?

Some high level guidance would be great! If we can add an example in the repo that would be even greater!

Thanks in advance

**Comment by wenyongh** [comment]
Hi @AfflatusX, do you mean that you want to build AS source code into two parts: AS app and AS lib, AS app depends on AS lib and WASM runtime can auto load AS lib while running AS app? To build AS app and AS lib, you might try using as with flag `--importTable` and `--exportTable` (see asc --help):
```bash
  --importTable         Imports the function table from 'env.table'.
  --exportTable         Exports the function table as 'table'.
```
To auto load the depended module while running WASM app, please enable the multi-module, refer to the [document](https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/doc/multi_module.md) and [sample](https://github.com/bytecodealliance/wasm-micro-runtime/tree/main/samples/multi-module). Note that this feature is only enabled by interpreter mode currently. Thanks.
