### ISSUE TITLE
FreeRTOS/ OpenRTOS support 

### ISSUE THREAD

**Issue by KaczmarczykMateusz** [bytecodealliance/wasm-micro-runtime#628]
Hello,
I would like to port WAMR into FreeRTOS running on M4Stack dev board powered by ESP32 (D0WDQ6-V3, dual core Xtensa 32-bit 240Mhz LX6 processor), however I still don't have hardware for testing.
I studied #134 and #121 comments. Later on pull request #451 came . 
I've noticed that @wenyongh was working on FreeRTOS/ OPENRTOS support. After mentioned pull request you've made further modifications to the module which I'm talking about.
Could you please tell me what is the progress of the work, specifically will I be able to run WAMR on my device (even unstable version will fit my purposes for now)?
What are your plans regarding FreeRTOS/ OpenRTOS support?

**Comment by wenyongh** [comment]
Hi, there is esp-idf platform `core/shared/platform/esp-idf` and an example `product-mini/platforms/esp-idf` with test source files and make files, which depend on freertos on `core/shared/platform/common` and are just for a reference, we haven't tested them yet. As FreeRTOS is not a complete system, maybe you need to implement the related missing APIs by yourself, e.g. printf. Thanks.
