### ISSUE TITLE
Compiler error when mem tracing is turned on

### ISSUE THREAD

**Issue by AfflatusX** [bytecodealliance/wasm-micro-runtime#637]
here: https://github.com/bytecodealliance/wasm-micro-runtime/blob/03d45f1d62dbcfdff1cb0893318ab5d4298f726a/core/shared/mem-alloc/ems/ems_kfc.c#L50

error: 'buf_size' undeclared (first use in this function)

**Comment by wenyongh** [comment]
Hi, thanks for reporting the issue!  It was fixed in #639.
