### ISSUE TITLE
Can WASI libc be built by GCC C99?

### ISSUE THREAD

**Issue by yj6c6565** [bytecodealliance/wasm-micro-runtime#645]
I want to porting iwasm with WASI support(WAMR_BUILD_LIBC_WASI = 1) to ARMv5TE Linux.

The toolchain is GCC 4.4.x (C99) so it cannot build C11 feature like _Static_assert, _Alignof, _Noreturn, stdatomic.h, etc.

And I cannot upgrade the toolchain to solve this.

Can WASI libc be built by GCC C99?

**Comment by wenyongh** [comment]
@yj6c6565 Maybe you can define these macros by yourself. Or try using the UVWASI implementation, ref to:
https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/doc/build_wamr.md#configure-libc

**Comment by yj6c6565** [comment]
@wenyongh Thanks your advisor.
