### ISSUE TITLE
the WAMR_BUILD_MEMORY_PROFILING option has not take effect

### ISSUE THREAD

**Issue by victortanjh** [bytecodealliance/wasm-micro-runtime#682]
use the following command to compile WAMR vmcore (iwasm) :
cmake .. -WAMR_BUILD_DUMP_CALL_STACK=1 -WAMR_BUILD_MEMORY_PROFILING=1
make

then, I use the following command to find the "wasm_runtime_dump_mem_consumption" function, but failed.

nm -g --defined-only libvmlib.a |grep wasm_runtime_dump_mem_consumption

And also, when I use the wasm_runtime_dump_mem_consumption in my code, I got the following error:

undefined reference to `wasm_runtime_dump_mem_consumption'

**Comment by wenyongh** [comment]
@victortanjh, please use -**D**WAMR_BUILD_DUMP_CALL_STACK=1 -**D**WAMR_BUILD_MEMORY_PROFILING=1, but not -WAMR_BUILD_DUMP_CALL_STACK=1 -WAMR_BUILD_MEMORY_PROFILING=1, thanks.

**Comment by victortanjh** [comment]
thank you very much! @wenyongh
