### ISSUE TITLE
Can I call  wasm_runtime_full_init many time?

### ISSUE THREAD

**Issue by victortanjh** [bytecodealliance/wasm-micro-runtime#689]
Can I call  wasm_runtime_full_init many time ?
Should t cause the program to crash ?

In my program, I set :
#define WASM_GLOBAL_HEAP_SIZE (1024 * 1024 * 12)
#define WASM_MODULE_INSTANCE_HEAP_SIZE (1024*1024)
#define WASM_MODULE_INSTANCE_STACK_SIZE (1024*1024)
#define WASM_ERROR_BUFF_SIZE (128*2)

If the number of wasm instance is too large, call wasm_runtime_instantiate will failed,
there will be a error:"WASM module instantiate failed: Exception: allocate memory failed".

So, I want to call wasm_runtime_full_init  again to alloc a larger memory for WASM_GLOBAL_HEAP, is that correct?

**Comment by xujuntwt95329** [comment]
No, you can't call `wasm_runtime_full_init` twice before you call `wasm_runtime_destroy`

If you are using `Alloc_With_Pool` mode during first initialization, then all the data are in the provided memory buffer (which is usually a global buffer), so if you call `wasm_runtime_full_init` again and provide a new buffer, then all the data such as the `wasm_module` are no longer useful as they are not in the new buffer.

There are two approaches for your case:
1. When you encounter an `allocate memory failed` error, call `wasm_runtime_destroy` to de-init the runtime, and then you can call `wasm_runtime_full_init` again to give a new buffer, you will need to do all the things again such as load the module from file
2. Also, you can use `Alloc_With_Allocator` mode then you can use all the memory provided by the system
``` C
    init_args.mem_alloc_type = Alloc_With_Allocator;
    init_args.mem_alloc_option.allocator.malloc_func = malloc;
    init_args.mem_alloc_option.allocator.realloc_func = realloc;
    init_args.mem_alloc_option.allocator.free_func = free;
```


Also we have some documents for how to reduce the footprint of the wasm module, please refer to [build_wasm_app](https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/doc/build_wasm_app.md#2-how-to-reduce-the-footprint) for more details.
