### ISSUE TITLE
Variable name `export` conflicting with C++11 keyword

### ISSUE THREAD

**Issue by csegarragonz** [bytecodealliance/wasm-micro-runtime#741]
Hi,

I am using WAMR in a C++ project, and the variable name `export` in [`core/iwasm/common/wasm_runtime_common.h`](https://github.com/bytecodealliance/wasm-micro-runtime/blob/db695fada42e6eed7cc9a94af7a48b4f1369009e/core/iwasm/common/wasm_runtime_common.h#L782) conflicts with the C++11 keyword, yielding a compilation error.

**Comment by xujuntwt95329** [comment]
Hi, thanks for reporting this, we'll fix this later.

As a quick workaround, you can use a macro to shadow `export` before including this file to make the compiler happy, for example:
``` cpp
extern "C" {
  /* shadow the C++ keyword "export" */
  #define export extern_export
  
  #include "../interpreter/wasm_runtime.h"
  
  #undef export
}
```

**Comment by csegarragonz** [comment]
Yes, I was doing that before, thanks.

I have issues a very small PR to fix this.
