### ISSUE TITLE
About benchmark matrix and gimli

### ISSUE THREAD

**Issue by lin7sh** [bytecodealliance/wasm-micro-runtime#761]
After checking out the benchmark on the wiki page, I'm curious about the "matrix" and "gimli"?

Is the gimli is the same as the hash function [gimli](https://gimli.cr.yp.to) by djb?

Could anyone provide a link about the benchmarks?

**Comment by wenyongh** [comment]
Hi, the benchmark can be found [here](https://github.com/bytecodealliance/sightglass/blob/main/benchmarks/shootout).

**Comment by lin7sh** [comment]
@wenyongh that's what I expect thanks
