### ISSUE TITLE
Is the uinit in binary size table correct?

### ISSUE THREAD

**Issue by majianjia** [bytecodealliance/wasm-micro-runtime#774]
Hi, 
I am currently doing a preview of wasm running on MCU/RT-Thread. 
The size of binary data is our major concern. 

The wiki pages shows those numbers are in KB but they are quite simple codes. And the size of GCC binary doesn't make sense to me. I wonder if the units are wrong here?

https://github.com/bytecodealliance/wasm-micro-runtime/wiki/Performance#wasm-application-binary-size

Thanks.

**Comment by wenyongh** [comment]
Hi, thanks for reporting the issue! The units should be Bytes but not KB, we have updated the wiki page. Thanks.
