### ISSUE TITLE
Invalid relocation type 282 for AOT on aarch64

### ISSUE THREAD

**Issue by robinvanemden** [bytecodealliance/wasm-micro-runtime#867]
On compiling to `WASM` using

```
WASM_FLAGS = --sysroot=${WASM_SYSROOT} -O3 -fno-exceptions -mbulk-memory -m32 -fno-rtti -ffast-math -fno-math-errno
```
and then compiling AOT with either `wamrc_v0` (May 2021) and `wamrc_v1` (current version, 12/5/2021)

```
wamrc_v0 --target=aarch64 --enable-bulk-memory -o model.aarch64_0.aot mode.wasm
wamrc_v1 --target=aarch64                      -o model.aarch64_1.aot model.wasm
```
we receive the following error when running the `model.aarch64_1` compiled by the current `wamrc_v1` version with a up to date WAMR application
```
Error: Load wasm runtime_core.module failed. error: Load relocation section failed: invalid relocation type 282.
```
The older `wamrc_v0` generated `model.aarch64_0.aot` does not generate this error when it is run. Nor does compiling AOT for targets `x64` and `armv7` with either `wamrc_v0` (May 2021) or `wamrc_v1` (current version, 12/5/2021).

**Comment by wenyongh** [comment]
@robinvanemden relocation type 282 is R_AARCH64_JUMP26, the relocation for it should be same as for R_AARCH64_CALL26, could you please try whether patch #873 works?

**Comment by robinvanemden** [comment]
@wenyongh yes, patch #873 resolves this issue. Thanks!

**Comment by Jiax-cn** [comment]
I encountered a similar issue: `Load relocation section failed: invalid relocation type 261.` Is there any plan to support this relocation type? Thank you very much!

**Comment by lum1n0us** [comment]
To my knowledge, there isn't a plan in place for *data relocation*(including `R_AARCH64_ABSxxx` and `R_AARCH64_PRELxxx`) as seen in the Linux source (https://elixir.bootlin.com/linux/v4.9.12/source/arch/arm64/kernel/module.c#L232). However, you are welcome to contribute to this area.

**Comment by yamt** [comment]
> [@wenyongh](https://github.com/wenyongh) I encountered a similar issue: `Load relocation section failed: invalid relocation type 261.` Is there any plan to support this relocation type? Thank you very much!

i guess you can file a new bug with a recipe to reproduce.
