### ISSUE TITLE
Build for esp32 fails

### ISSUE THREAD

**Issue by 1c3t3a** [bytecodealliance/wasm-micro-runtime#883]
Hi there! First of all thanks for putting together WAMR! 
I am trying to build the demo in `product-mini/platforms/esp-idf`, but get an error concerning the headers in `core/shared/platform/esp-idf`.
When I execute the following in my build folder:
```
cmake .. -DCMAKE_TOOLCHAIN_FILE=$IDF_PATH/tools/cmake/toolchain-esp32.cmake -DTARGET=esp32 -GNinja
cmake --build .
```

I get the error
```
/../wasm-micro-runtime/product-mini/platforms/esp-idf/../../../core/shared/platform/esp-idf/platform_internal.h:18:10: fatal error: FreeRTOS.h: No such file or directory
 #include <FreeRTOS.h>
          ^~~~~~~~~~~~
compilation terminated.
```

When trying to resolve this by putting `freertos/FreeRTOS.h`, I end up with the following error:
```
/platform/esp-idf/platform_internal.h:21:10: fatal error: os_api.h: No such file or directory
 #include <os_api.h>
          ^~~~~~~~~~
compilation terminated.
```

I neither found the header `os_api.h` in WAMR nor in ESP-IDF.

**Comment by wenyongh** [comment]
Hi, the esp-idf platform is just for a reference, it wasn't completely tested yet, you might need to port it by yourself, normally you can refer to [WAMR porting guide](https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/doc/port_wamr.md) and other closed issues before #628, #449.
