### ISSUE TITLE
Any plans for wasm64 support?

### ISSUE THREAD

**Issue by qinkunbao** [bytecodealliance/wasm-micro-runtime#911]
Are there any plans to support wasm64?

It looks to me that WASMTIME has begun to implement supports for WASM64, which allows a wasm application to use more than 4GB of memory. I am aware that WASI-SDK is not ready for 64 bits. I just wonder if WAMR has any plan to support wasm64 in the future.

**Comment by wenyongh** [comment]
@qinkunbao currently there is no plan to support wasm64 yet.

**Comment by qinkunbao** [comment]
> @qinkunbao currently there is no plan to support wasm64 yet.

Thank you for your reply.
