### ISSUE TITLE
win_thread.c timed wait always return 0

### ISSUE THREAD

**Issue by xingkaiyu** [bytecodealliance/wasm-micro-runtime#990]
hi~
I am using thread with wasm and wamr on windows. And I find that pthread_cond_timedwait always return 0 no matter timed out or realy success.
I think we can return the wait result in os_cond_wait_internal. I tryed it and it works ok.
Here is my patch.
[win_thread-patch.zip](https://github.com/bytecodealliance/wasm-micro-runtime/files/7957202/win_thread-patch.zip)

**Comment by wenyongh** [comment]
Yes, could you please help submit a PR to fix it? Thanks.

**Comment by xingkaiyu** [comment]
like this https://github.com/bytecodealliance/wasm-micro-runtime/pull/994 ?
