### ISSUE TITLE
pthread_setspecific_wrapper and pthread_getspecific_wrapper return value suggestion

### ISSUE THREAD

**Issue by xingkaiyu** [bytecodealliance/wasm-micro-runtime#995]
1- pthread_setspecific return an int value to show if it is success. So I think the pthread_setspecific_wrapper should always return -1 when goto wrong. But now it will return 0 when key_values is null.
2- pthread_getspecific return an address of the thread local value. So I think the pthread_getspecific_wrapper should always return NULL(0) when goto wrong. But now it will return -1 when info is null.

**Comment by xujuntwt95329** [comment]
Thanks for the suggestion, I've submitted a PR #999 to fix this
