### ISSUE TITLE
MC JIT does not execute compression program correctly, but Lazy JIT does

### ISSUE THREAD

**Issue by kimbethstonehouse** [bytecodealliance/wasm-micro-runtime#997]
I've been compiling a subset of the SPEC CPU 2017 benchmarks into WebAssembly and running them using various WebAssembly runtimes, mainly to compare the performance of different JIT compilers.

I've run into issues with the 557.xz_r benchmark, a compression program. When building with Lazy JIT enabled, the program executes correctly and gives the desired output. However, when building with Lazy JIT disabled (and so MC JIT enabled), the data becomes corrupted.

Here's an example input:

> iwasm  --dir=. xz_r_base.mytest-m32 cpu2006docs.tar.xz 1 055ce243071129412e9dd0b3b69a21654033a9b723d874b2015c774fac1553d9713be561ca86f74e4f16f22e664fc17a79f30caa5ad2c04fbc447549c2810fae 650156 -1 0

Here's the expected output, which is also given by Lazy JIT:

> SPEC CPU XZ driver: input=cpu2006docs.tar.xz insize=1
> Loading Input Data
> Compressed size: 1287176; Uncompressed size: 9041920
> SHA-512 of decompressed data compared successfully!
> Decompressed data too large; truncating to requested size 1048576
> SHA-512 of input file: 08f45ee14f1e624ef4ac5accaf791cabc25834995f66954ffb6e6f0a92755070560f0ae276ff1517ce513dfffeda8eb455c3ed54121f0b22d85d0aba954bb202
> Input data 1048576 bytes in length
> Compressing Input Data, level 0
> Compressed data length is 650156 bytes in length
> Finished compressing data
> Uncompressing previously compressed data
> Uncompressed data 1048576 bytes in length
> Uncompressed data compared correctly
> Tested 1 MiB buffer: OK!

Here's MC JIT's output:

> SPEC CPU XZ driver: input=cpu2006docs.tar.xz insize=1
> Loading Input Data
> Compressed size: 1287176; Uncompressed size: 9041920
> SHA-512 of decompressed data compared successfully!
> Decompressed data too large; truncating to requested size 1048576
> SHA-512 of input file: 08f45ee14f1e624ef4ac5accaf791cabc25834995f66954ffb6e6f0a92755070560f0ae276ff1517ce513dfffeda8eb455c3ed54121f0b22d85d0aba954bb202
> Input data 1048576 bytes in length
> Compressing Input Data, level 0
> Compressed data length of 650468 does not match expected length of 650156 bytes
> Finished compressing data
> Uncompressing previously compressed data
> Decompression decoder error: Compressed data is corrupt (code 9)
> Uncompressed data 547840 bytes in length
> Computed SHA-512 sum for decompression step did not match expected
>   Generated: d63e6f65f9d19f3a0fc176233c22f3c166a9e17e337e059014e594252f376c2c6143e586e33aeb02d3a1715147203334ea1bab8fdb5fe4deb1b6123b3f30f46c
>    Expected: 08f45ee14f1e624ef4ac5accaf791cabc25834995f66954ffb6e6f0a92755070560f0ae276ff1517ce513dfffeda8eb455c3ed54121f0b22d85d0aba954bb202

I'm running on Linux Mint 20.2 and compiling the benchmarks using the wasi-sdk clang. [Attached](https://github.com/bytecodealliance/wasm-micro-runtime/files/7996487/557.zip)
 is the input file cpu2006docs.tar, the source code and the compiled WebAssembly (xz_r_base.mytest-m32).

**Comment by wenyongh** [comment]
@kimbethstonehouse not sure how you build the workload into wasm bytecode, could you help upload the build script? I replaced "/usr/local/gcc" with "/opt/wasi-sdk/bin/clang" in simple-build-xz_r-557.sh and removed the "-m64" option to build the wasm file, and then run it with MCJIT, it works. See [557.zip](https://github.com/bytecodealliance/wasm-micro-runtime/files/8057723/557.zip).
